// 具身智能研究图谱 · 数据文件 2/4：VLA 基础模型、动作表征与学习范式
window.EAI_MODULES = window.EAI_MODULES || [];

window.EAI_MODULES.push({
  id: "vla", type: "loop", order: 3, icon: "🦾", color: "#d0603a",
  name: "VLA 基础模型",
  tagline: "视觉-语言-动作端到端大模型如何炼成、如何泛化？",
  difficulties: [
    {
      id: "vla_pioneer", name: "端到端 VLA 开创与规模化",
      question: "把动作当 token、用 VLM 底座直接输出控制，这条路是怎么走通的？",
      papers: [
        { id: "rt1", name: "RT-1", title: "RT-1: Robotics Transformer for Real-World Control at Scale", year: 2022, venue: "RSS 2023", status: "已发表", url: "https://arxiv.org/abs/2212.06817",
          summary: "13 万条真机演示训练的多任务 Transformer 策略，机器人大模型的起点。",
          purpose: "验证「大数据 + 大模型」配方能否像 NLP/CV 一样在机器人控制上成立。",
          method: "EfficientNet+TokenLearner 编码观测，Transformer 输出离散化动作 token，17 个月采集 700+ 任务真机数据。",
          contribution: "97% 已见任务成功率与显著零样本泛化，确立真机规模化数据路线，是整个 RT 系与 VLA 谱系的根。" },
        { id: "rt2", name: "RT-2", title: "RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control", year: 2023, venue: "CoRL 2023", status: "已发表", url: "https://arxiv.org/abs/2307.15818",
          summary: "首次把互联网级 VLM 直接微调成机器人策略，提出 VLA 这一术语。",
          purpose: "让机器人策略继承网络规模的语义知识（图标、名人、符号推理），突破机器人数据的语义覆盖上限。",
          method: "把动作离散化为文本 token，与 VQA 数据共同微调 PaLI-X/PaLM-E（至 55B），动作即「另一种语言」。",
          contribution: "涌现语义泛化与初步推理（如「捡起灭绝动物」→恐龙玩具），定义了 VLA 范式与命名。" },
        { id: "openvla", name: "OpenVLA", title: "OpenVLA: An Open-Source Vision-Language-Action Model", year: 2024, venue: "CoRL 2024 (Stanford/Berkeley等)", status: "已发表", url: "https://arxiv.org/abs/2406.09246",
          summary: "7B 开源 VLA，97 万真机演示训练，性能超 55B 的 RT-2-X。",
          purpose: "打破闭源垄断，给社区一个可微调、可复现的 VLA 底座。",
          method: "Llama 2 + DINOv2/SigLIP 双视觉编码，Open X-Embodiment 97 万条轨迹训练，支持 LoRA 低成本适配。",
          contribution: "以 7 倍小的参数量超越 RT-2-X 16.5%，成为学界事实标准基线与无数后续工作的起点。" },
        { id: "rtx", name: "Open X-Embodiment / RT-X", title: "Open X-Embodiment: Robotic Learning Datasets and RT-X Models", year: 2024, venue: "ICRA 2024 (Best Paper)", status: "已发表", url: "https://arxiv.org/abs/2310.08864",
          summary: "22 种机器人、百万级轨迹的跨具身数据联盟与正迁移证据。",
          purpose: "验证跨机器人形态的数据合并训练能否产生「通才红利」。",
          method: "34 个实验室汇集 100 万+ 轨迹统一成 RLDS 格式，在其上训练 RT-1-X/RT-2-X 并跨平台评测。",
          contribution: "跨具身正迁移提升 50%，奠定「数据联盟 + 通才模型」的行业协作范式。" },
        { id: "pi0", name: "π0", title: "π0: A Vision-Language-Action Flow Model for General Robot Control", year: 2024, venue: "arXiv 2024 (Physical Intelligence)", status: "预印本", url: "https://arxiv.org/abs/2410.24164",
          summary: "VLM 骨干 + flow matching 动作专家，输出 50Hz 连续动作块，可叠衣服。",
          purpose: "解决离散动作 token 频率低、精度差，无法支撑灵巧连续操作的问题。",
          method: "PaliGemma 骨干外挂动作专家模块，flow matching 生成高频动作块，7 种机器人 68 类任务预训练+任务后训练。",
          contribution: "在叠衣、清桌等长程灵巧任务上远超 OpenVLA 等基线，把 VLA 推进到「连续高频控制」时代。" },
        { id: "pi05", name: "π0.5", title: "π0.5: A Vision-Language-Action Model with Open-World Generalization", year: 2025, venue: "arXiv 2025 (Physical Intelligence)", status: "预印本", url: "https://arxiv.org/abs/2504.16054",
          summary: "异构数据共训 + 分层推理，机器人进没见过的真实家庭做整套清理。",
          purpose: "攻真机 VLA 最痛的开放世界泛化：全新家庭、全新物体布局下的长程任务。",
          method: "多机器人/多环境/网页多模态数据联合训练，模型先输出高层子任务语义再解码低层动作，知识隔离训练技巧。",
          contribution: "首次展示移动操作机器人在完全未见家庭中执行 10-15 分钟长程任务，是开放世界泛化的标志性证据。" },
        { id: "gr00t", name: "GR00T N1", title: "GR00T N1: An Open Foundation Model for Generalist Humanoid Robots", year: 2025, venue: "arXiv 2025 (NVIDIA)", status: "技术报告", url: "https://arxiv.org/abs/2503.14734",
          summary: "人形机器人开放基础模型：VLM 慢系统 + 扩散动作快系统双架构。",
          purpose: "给人形/通用机器人提供开放、可后训练的双系统 VLA 底座。",
          method: "System 2（VLM 理解规划）与 System 1（扩散 Transformer 输出高频动作）端到端联训，数据金字塔混合真机/人视频/合成数据。",
          contribution: "开放权重人形 VLA 标杆，「双系统 + 数据金字塔」成为行业通用设计词汇。" },
        { id: "gemini_robotics", name: "Gemini Robotics", title: "Gemini Robotics: Bringing AI into the Physical World", year: 2025, venue: "arXiv 2025 (Google DeepMind)", status: "技术报告", url: "https://arxiv.org/abs/2503.20020",
          summary: "Gemini 2.0 直接长出动作输出，配套具身推理模型 Gemini Robotics-ER。",
          purpose: "验证前沿多模态大模型可平滑扩展为物理智能体，兼得推理与灵巧。",
          method: "在 Gemini 之上训练 VLA 输出平滑动作，ER 版本强化空间/物理理解，支持折纸鹤等精细任务与快速任务适配。",
          contribution: "展示「前沿 LLM → VLA」的直通路线与少样本适配能力，2026 年 1.5 版引入跨具身动作迁移与思考模式。" },
        { id: "g05", name: "G0.5", title: "G0.5: One Autoregressive Stream for Robot Reasoning and Action", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.11739",
          summary: "单流自回归统一推理与动作，质疑「VLM 编码器 + 动作专家」的分体配方。",
          purpose: "主流 VLA 把 VLM 降格为上下文编码器、动作交给外挂专家，推理与行动被割裂。",
          method: "统一自回归流中同时输出推理 token 与动作 token，让「想」和「做」共享同一计算路径。",
          contribution: "对 π0 式双模块架构的根本性挑战，2026 年 VLA 架构反思的代表。" },
        { id: "cometvla", name: "CometVLA", title: "CometVLA: Co-Training on an Embodied Data Pyramid towards Physical Understanding", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.30289",
          summary: "用「具身数据金字塔」共训补物理常识：物理 VQA 与动作域对齐。",
          purpose: "现有物理 VQA 数据脱离机器人动作域，VLA 学了常识却用不到控制上。",
          method: "构造与机器人动作域对齐的分层具身数据金字塔共训 VLA，弥合常识与操作的鸿沟。",
          contribution: "延续 GR00T 数据金字塔思想并落到公开训练配方，物理理解型 VLA 的 2026 代表。" },
        { id: "refactorvla", name: "REFACTOR-VLA", title: "REFACTOR-VLA: Unsupervised Library Learning of Typed Motor Programs", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.01215",
          summary: "把 VLA 的动作重构成「带类型的运动程序库」，无监督学可复用技能抽象。",
          purpose: "OpenVLA/π0/RDT 等单体 VLA 直接吐动作块，没有可复用的行为抽象，长程任务易碎。",
          method: "无监督地从轨迹中发现带类型签名的运动程序并组织成库，VLA 调用组合而非逐 token 输出。",
          contribution: "把「技能库」思想重新注入 VLA 主线，衔接程序化操作与终身学习。" },
        { id: "bimanual1500", name: "Bimanual 1500h + On-Policy", title: "Scaling Bimanual Household Manipulation from 1,500 hours of Demonstrations to On-Policy Corrections", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03591",
          summary: "开源 1500 小时双臂家务演示数据，演示→在线纠错的完整扩展路径。",
          purpose: "双臂通用策略卡在高质量大规模人类演示数据的稀缺。",
          method: "发布 1500 小时多样化双臂家务演示，并给出从演示学习到在线策略纠错的扩展管线。",
          contribution: "迄今最大规模的双臂家务数据发布之一，数据引擎路线的 2026 新标杆。" }
      ]
    },
    {
      id: "vla_ttt", name: "测试时训练与测试时计算 (TTT/TTC)",
      question: "2026 年新主线：部署时不重训，靠测试时训练、上下文扩展、推理时搜索把策略变得更强？",
      papers: [
        { id: "robottt", name: "RoboTTT", title: "RoboTTT: Context Scaling for Robot Policies", year: 2026, venue: "arXiv 2026.07 (NVIDIA GEAR)", status: "预印本", url: "https://arxiv.org/abs/2607.15275",
          summary: "机器人策略的「上下文扩展」：测试时训练配方让策略吃长时程视觉运动上下文。",
          purpose: "现有机器人基础模型只用单步或短历史上下文，无法从部署流中积累经验。",
          method: "提出 Test-Time-Training Robot Policies：模型架构与训练配方一起设计，使 visuomotor 上下文可随测试时数据规模化扩展。",
          contribution: "把 LLM 的上下文 scaling 思想搬进机器人策略，确立 TTT 为机器人基础模型的新训练维度。" },
        { id: "wamttt", name: "WAM-TTT", title: "WAM-TTT: Steering World-Action Models by Watching Human Play at Test Time", year: 2026, venue: "arXiv 2026.07 (NVIDIA等)", status: "预印本", url: "https://arxiv.org/abs/2607.06988",
          summary: "测试时「看人类玩」就能校准世界-动作模型，无需机器人演示。",
          purpose: "把机器人基础模型导向新任务变体或用户偏好，通常需要额外机器人演示或长链微调。",
          method: "在测试时用无动作标注的人类操作视频对 WAM 做测试时训练，把人类行为先验注入世界-动作预测。",
          contribution: "「人类视频 × 测试时训练 × WAM」三线交汇的代表作，演示成本为零的行为校准。" },
        { id: "tau0vla", name: "τ₀-VLA", title: "τ₀-VLA: A Hierarchical Robot Foundation Model with World-Model-Guided Test-Time Computation", year: 2026, venue: "arXiv 2026.08 (清华等)", status: "预印本", url: "https://arxiv.org/abs/2608.16885",
          summary: "世界模型引导的测试时计算 + 分层 VLA：技能执行与长程编排分层提分。",
          purpose: "长程操作既要单技能可靠执行，又要多技能连贯衔接，现有分层 VLA 两头都弱。",
          method: "分层机器人基础模型，高层用世界模型引导的测试时计算做技能编排，低层保证执行可靠性。",
          contribution: "τ 系（τ₀-VLA/τ₀-WM）把「测试时计算」显式写进基础模型架构，2026 分层 VLA 的新标杆。" },
        { id: "tttvla", name: "TTT-VLA", title: "TTT-VLA: Test-Time Latent Prompt Optimization for Vision-Language-Action Models", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.03127",
          summary: "测试时潜提示优化：不动权重，在潜空间连续初始化提示对抗分布偏移。",
          purpose: "VLA 部署时遇到分布偏移即脆弱，提示微调是离散 token、表达力受限。",
          method: "将提示视为连续潜变量在测试时优化，逐样本适配而不更新模型权重。",
          contribution: "轻量级测试时适配 VLA 的代表方案，与 RoboTTT 的全上下文路线互补。" },
        { id: "vane", name: "VANE", title: "VANE: Reliable Test-Time Training for Vision-Language-Action Models via Future Visual Representation Prediction", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.09448",
          summary: "用「未来视觉表征预测」做可靠 TTT：无标签部署流上闭环可用的测试时训练。",
          purpose: "TTT 在闭环操作里容易跑飞：自监督目标与控制任务不一致时越训越差。",
          method: "以未来视觉表征预测为测试时训练目标，并解决可靠性问题（何时停止、如何防漂移）。",
          contribution: "把 TTA/TTT 从「能涨点」推进到「闭环可信赖」，TTT 工程化的重要一环。" },
        { id: "evolvevla", name: "EVOLVE-VLA", title: "EVOLVE-VLA: Test-Time Training from Environment Feedback for Vision-Language-Action Models", year: 2026, venue: "arXiv 2025.12", status: "预印本", url: "https://arxiv.org/abs/2512.14666",
          summary: "从环境反馈做测试时训练：不止模仿静态演示，而在交互中持续变强。",
          purpose: "真正的自适应具身智能需要在部署交互中自我改进，而非只靠离线演示。",
          method: "把环境反馈（成败/物理信号）转化为测试时训练信号，在线更新 VLA。",
          contribution: "TTT 最早的 VLA 落地尝试之一（2025.12），开启 2026 TTT 论文潮。" },
        { id: "rl2vla", name: "RL²-VLA", title: "RL²-VLA: Adaptive RL Latent Compositional Steering with Test-Time Scaling for Vision-Language-Action Models", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.26991",
          summary: "RL² 式潜变量自适应控制搬到 VLA：测试时按任务组合潜策略并规模化计算。",
          purpose: "VLA 在挑战性/分布外任务上退化，单一静态策略无法按任务难度调配算力。",
          method: "自适应 RL 潜组合引导 + 测试时 scaling，按任务在潜策略空间中组合搜索。",
          contribution: "「快慢自适应 + 测试时规模化」同时实现，接通 meta-RL 与 VLA 两个社区。" },
        { id: "etts", name: "E-TTS", title: "E-TTS: A New Embodied Test-Time Scaling Framework for Robotic Manipulation", year: 2026, venue: "ECCV 2026", status: "已发表", url: "https://arxiv.org/abs/2606.27268",
          summary: "具身测试时规模化框架：推理与动作两条轴同时扩算力。",
          purpose: "测试时 scaling 在具身任务刚起步：推理提分但动作生成不扩、且计算常常不可控。",
          method: "统一框架沿推理与生成两条轴分配测试时算力，均衡精度与时延。",
          contribution: "首个系统的具身 TTS 框架（ECCV 2026），定义了该方向的问题空间。" },
        { id: "elastic", name: "ELASTIC", title: "ELASTIC: Efficiently Learning to Adaptively Scale Test-Time Compute for Generative Control Policies", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.31132",
          summary: "学习「该花多少测试时算力」：生成式控制策略的自适应计算分配。",
          purpose: "扩散/流式策略的测试时计算（采样步数×批量）怎么分配没人知道，盲目放大浪费。",
          method: "学习一个计算分配器，按状态难度自适应决定采样预算。",
          contribution: "把「adaptive computation」从 LLM 层搬到动作生成层，控频与精度的帕累托改进。" },
        { id: "instinct", name: "Trust Your Instincts", title: "Trust Your Instincts: Confidence-Driven Test-Time RL for Vision-Language-Action Models", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.29892",
          summary: "自信驱动的测试时 RL：无需外部环境评分，用自身置信度当奖励。",
          purpose: "测试时 RL 通常需要外部环境反馈（成功判定），部署场景不可得。",
          method: "以模型自身置信度为内在奖励信号做测试时强化学习。",
          contribution: "去掉 TTT/RL 对环境评判的依赖，「自评自练」路线的代表。" },
        { id: "tttparkour", name: "TTT-Parkour", title: "TTT-Parkour: Rapid Test-Time Training for Perceptive Robot Parkour", year: 2026, venue: "arXiv 2026.02", status: "预印本", url: "https://arxiv.org/abs/2602.02331",
          summary: "人形跑酷的快速测试时训练：几分钟适配未见复杂地形。",
          purpose: "通才运动策略覆盖广但难臻极致，未见地形上高动态跑酷仍会失败。",
          method: "部署现场快速 TTT：以少量在线交互适配通才感知运动策略。",
          contribution: "TTT 从操作扩展到高动态运动控制，NVIDIA 系 TTT 布局的一环。" },
        { id: "lookb4leap", name: "Look Before You Leap", title: "Look Before You Leap: Distilling Tree Search into Action Evaluation for Frozen VLA Models", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.03751",
          summary: "把树搜索蒸馏成动作评估器：冻结 VLA 也能「三思而后行」。",
          purpose: "VLA 泛化脆弱，测试时搜索有效但推理太慢，无法实时。",
          method: "离线树搜索的知识蒸馏为轻量动作评估函数，测试时对冻结 VLA 的候选动作快速打分选择。",
          contribution: "「搜索→蒸馏→轻量评估」范式让测试时搜索实时化。" },
        {"id": "vlareasoner", "name": "VLA-Reasoner", "title": "VLA-Reasoner: Empowering Vision-Language-Action Models with Reasoning via Online Monte Carlo Tree Search", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2509.22643", "summary": "在线 MCTS 给现成 VLA 装上「预想未来」的推理能力，即插即用。", "purpose": "VLA 逐动作短视预测在长时程任务中误差累积。", "method": "在线蒙特卡洛树搜索包住冻结 VLA，前瞻未来状态再决策。", "contribution": "测试时搜索赋能 VLA 的 ICRA 2026 代表，与 Look-Before-You-Leap 互补。"}
      ]
    },
    {
      id: "vla_action", name: "动作表征与解码",
      question: "动作该用离散 token、扩散还是 flow？动作块怎么设计才又快又准？",
      papers: [
        { id: "diffusionpolicy", name: "Diffusion Policy", title: "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion", year: 2023, venue: "RSS 2023 / IJRR", status: "已发表", url: "https://arxiv.org/abs/2303.04137",
          summary: "把策略建模为条件去噪过程，多峰动作分布的标准解法。",
          purpose: "模仿学习中人类演示天然多峰，回归式策略会「平均成错误动作」。",
          method: "条件扩散模型生成动作序列块，配合滚动时域执行；视觉条件化与时序 U-Net/Transformer 骨干。",
          contribution: "12 项任务平均提升 46.9%，成为操作策略的默认动作头，直接影响 π0、RDT 等大模型设计。" },
        { id: "act", name: "ACT / ALOHA", title: "Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware (ACT)", year: 2023, venue: "RSS 2023", status: "已发表", url: "https://arxiv.org/abs/2304.13705",
          summary: "动作分块 + CVAE Transformer，5 千美元硬件学会精细双臂操作。",
          purpose: "低成本遥操作硬件上的模仿学习受复合误差困扰，需要高频精细控制方案。",
          method: "CVAE 编码演示风格，Transformer 一次预测一段动作块（action chunking），时间集成平滑执行。",
          contribution: "动作分块从此成为 VLA 标配技术；ALOHA 平台催生 Mobile ALOHA 与大量双臂研究。" },
        { id: "fast", name: "FAST", title: "FAST: Efficient Action Tokenization for Vision-Language-Action Models", year: 2025, venue: "RSS 2025 (Stanford)", status: "已发表", url: "https://arxiv.org/abs/2501.09747",
          summary: "基于 DCT 压缩的动作 tokenizer，自回归 VLA 训练提速 5 倍。",
          purpose: "朴素逐维离散化在高频灵巧任务上完全学不动，动作 token 化需要重新设计。",
          method: "离散余弦变换 + BPE 压缩动作块，得到信息密度均匀的动作词表，可作通用 tokenizer（FAST+）。",
          contribution: "让自回归 VLA 在高频任务上追平扩散 VLA 且训练快 5 倍，被 π0-FAST 等直接采用。" },
        { id: "rdt", name: "RDT-1B", title: "RDT-1B: A Diffusion Foundation Model for Bimanual Manipulation", year: 2025, venue: "ICLR 2025 (清华)", status: "已发表", url: "https://arxiv.org/abs/2410.07864",
          summary: "1.2B 扩散 Transformer + 统一动作空间，双臂操作基础模型。",
          purpose: "双臂数据稀缺且各机器人动作空间不一，难以规模化预训练。",
          method: "设计跨机器人统一动作空间以吸收 46 个数据集预训练，扩散建模连续动作，6K 双臂遥操数据微调。",
          contribution: "零样本泛化新物体/场景、1~5 条演示学新技能，是开源双臂 VLA 的代表。" },
        { id: "onetwovla", name: "CogACT", title: "CogACT: A Foundational Vision-Language-Action Model for Synergizing Cognition and Action", year: 2024, venue: "arXiv 2024 (北大等)", status: "预印本", url: "https://arxiv.org/abs/2411.19650",
          summary: "认知（VLM）与动作（扩散头）组件化分工的 VLA 架构研究。",
          purpose: "系统回答「VLM 输出直接当动作」与「专用动作模块」哪种更优。",
          method: "VLM 处理认知层，专门设计的扩散动作 Transformer 消化动作信号，组件化联训并做架构消融。",
          contribution: "大幅超越 OpenVLA（+35% 真机成功率），给出「动作模块必须专门设计」的实证依据。" },
        { id: "pir2", name: "πR²", title: "πR²: Reactive Real-time Flow Policies", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.26055",
          summary: "让流策略「边走边看」：动作块执行中实时响应传感输入（PI 出品）。",
          purpose: "动作块流策略开环执行，块内无法对感官变化做出反应。",
          method: "实时流策略架构，在动作块生成/执行过程中注入传感反馈实现闭环反应。",
          contribution: "解决 flow 系 VLA 的开环顽疾，是 π 系列在 2026 年的关键演进。" },
        { id: "driftingvla", name: "DriftingVLA", title: "DriftingVLA: Native One-Step Vision-Language-Action Generation via Per-Dimension Temporal Drifting", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29749",
          summary: "按维度时间漂移的单步流生成，砍掉多步去噪的在线延迟。",
          purpose: "流式 VLA 依赖多步迭代细化生成动作块，在线控制延迟高。",
          method: "逐维度时间漂移机制让流匹配一步出动作，保持表达力同时原生单步生成。",
          contribution: "流式 VLA 实时化的重要一步，与 ActionCache 共同构成 2026 推理加速支线。" },
        { id: "actioncache", name: "ActionCache", title: "ActionCache: Training-Free Acceleration for Vision-Language-Action Models with Action Caching and Refinement", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.06370",
          summary: "免训练的 VLA 加速：缓存历史动作块，复用 + 细化代替从零生成。",
          purpose: "流匹配 VLA 每个控制周期都要完整去噪一遍，算力浪费巨大。",
          method: "跨周期缓存动作块并在新观测下低成本细化，无需重训模型。",
          contribution: "即插即用给出数倍推理加速，「免训练加速」成为 VLA 部署标配议题。" },
        { id: "stopchunk", name: "Adaptive Action Chunking", title: "Knowing When to Stop: Adaptive Action Chunking via Internal Cross-Attention Dynamics in VLAs", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.00908",
          summary: "用 VLA 内部交叉注意力动态自适应决定动作块何时终止执行。",
          purpose: "固定执行时域的动作块在效率与精度间两难：块短了碎、长了迟钝。",
          method: "读取模型内部交叉注意力信号判断当前动作块的可信度，自适应截断执行并重规划。",
          contribution: "把「可解释性探针」变成控制信号，动作分块研究的新范式。" },
        { id: "symvd", name: "SymVD", title: "SymVD: Symmetric Vision Language Action Distillation for Robot Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29828",
          summary: "对称式 VLA 蒸馏：任务适应时保留预训练的泛化能力。",
          purpose: "预训练 VLA 适配新环境/新任务时容易遗忘泛化能力。",
          method: "对称蒸馏框架约束学生同时保留教师的任务能力与泛化表征。",
          contribution: "解决 VLA「微调掉泛化」的痛点，轻量适配方向 2026 代表。" },
        {"id": "arvla", "name": "AR-VLA", "title": "AR-VLA: True Autoregressive Action Expert for Vision-Language-Action Models", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.10126", "summary": "真正的自回归动作专家：提升动作生成的时间一致性。", "purpose": "主流动作专家在块内一次性生成，跨块时间一致性差。", "method": "设计真自回归的动作专家架构，逐 token 生成保持时序连贯。", "contribution": "RSS 2026 动作解码方向代表，与 G0.5 的单流自回归主张呼应。"},
        {"id": "lps", "name": "LPS", "title": "Latent Policy Steering through One-Step Flow Policies", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.05296", "summary": "单步流策略 + 潜空间策略引导：流策略快而稳的新解法。", "purpose": "多步流匹配策略推理慢，单步蒸馏又损表达力。", "method": "训练单步流策略，并在潜空间中对其做策略引导式修正。", "contribution": "RSS 2026 流策略效率路线代表，与 DriftingVLA/ActionCache 同题。"},
        {"id": "forcevla2", "name": "ForceVLA2", "title": "ForceVLA2: Unleashing Hybrid Force-Position Control with Force Awareness for Contact-Rich Manipulation", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.15169", "summary": "VLA 显式力觉感知 + 力-位混合控制，接触密集任务更稳。", "purpose": "VLA 只会位置控制，插拔擦拭等任务需要力觉层面的调节。", "method": "端到端引入力觉提示与混合力-位控制头的 VLA 框架。", "contribution": "CVPR 2026 力觉 VLA 代表，与 FD-VLA、FWBC-VLA 构成力控支线。"},
        {"id": "fdvla", "name": "FD-VLA", "title": "FD-VLA: Force-Distilled Vision-Language-Action Model for Contact-Rich Manipulation", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.02142", "summary": "力蒸馏：不用力传感器，把力觉信息蒸馏进 VLA。", "purpose": "给 VLA 加力觉通常需要物理力传感器，硬件成本高。", "method": "可学习 query token 把力觉知识从教师蒸馏进视觉-语言流。", "contribution": "无传感器力感知的 ICRA 2026 方案，力控支线的轻量实现。"},
        {"id": "guidedvla", "name": "GuidedVLA", "title": "GuidedVLA: Specifying Task-Relevant Factors via Plug-and-Play Action Attention Specialization", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2605.12369", "summary": "即插即用的动作注意力特化：指定「看哪里、忽略哪里」。", "purpose": "VLA 难以按任务指定应关注的视觉因素，干扰物易劫持注意力。", "method": "动作注意力特化模块即插即用地注入任务相关因素约束。", "contribution": "RSS 2026 注意力可控性代表，提升抗干扰操作。"}
      ]
    },
    {
      id: "vla_reason", name: "具身推理与思维链",
      question: "让 VLA 在动手前「先想一想」，推理链如何注入与变现？",
      papers: [
        { id: "ecot", name: "ECoT", title: "Robotic Control via Embodied Chain-of-Thought Reasoning", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2407.08693",
          summary: "训练 VLA 先输出任务/子任务/gripper 位置等推理链再出动作。",
          purpose: "VLA 端到端映射缺乏中间推理，失败难解释、泛化受限。",
          method: "自动流水线为机器人数据合成具身推理标注（计划、子任务、视觉 grounding），微调 OpenVLA 逐步推理。",
          contribution: "绝对成功率提升 28%，且推理链可被人工干预纠错，开创具身 CoT 训练路线。" },
        { id: "embodiedcotsurvey", name: "RAD", title: "Training Strategies for Efficient Embodied Reasoning (RAD)", year: 2025, venue: "CoRL 2025", status: "已发表", url: "https://arxiv.org/abs/2505.08243",
          summary: "把推理蒸馏进快速执行：训练时用 CoT，推理时可跳过。",
          purpose: "具身 CoT 推理链太慢，真机高频控制等不起。",
          method: "推理蒸馏与混合训练策略，让模型内化推理收益而无需推理时逐 token 生成。",
          contribution: "保留大部分 CoT 增益同时恢复实时性，回答「推理与速度不可兼得」的质疑。" },
        { id: "pi_hirobot", name: "Hi Robot", title: "Hi Robot: Open-Ended Instruction Following with Hierarchical Vision-Language-Action Models", year: 2025, venue: "ICML 2025 (Physical Intelligence)", status: "已发表", url: "https://arxiv.org/abs/2502.19417",
          summary: "「系统 2」VLM 分解复杂指令与实时反馈，「系统 1」π0 执行。",
          purpose: "处理开放式复杂指令（多步骤、约束、中途打断纠正）超出扁平 VLA 能力。",
          method: "高层 VLM 持续把复杂提示与用户反馈翻译成原子指令流，低层 VLA 执行，合成对话数据训练。",
          contribution: "在多阶段真实任务（清桌、做三明治）中显著优于扁平 π0 与 GPT-4o 规划器，确立分层 VLA 范式。" },
        { id: "magma", name: "Magma", title: "Magma: A Foundation Model for Multimodal AI Agents", year: 2025, venue: "CVPR 2025", status: "已发表", url: "https://arxiv.org/abs/2502.13130",
          summary: "数字（UI）与物理（机器人）智能体统一底座，SoM/ToM 标注桥接理解与行动。",
          purpose: "智能体能力被割裂在 UI 导航与机器人操作两个社区，希望一个模型通吃。",
          method: "用 Set-of-Mark（可操作点标记）与 Trace-of-Mark（运动轨迹标记）统一标注图像/视频/机器人数据并联合预训练。",
          contribution: "单模型同时在 UI 导航与真机操作上达到或超过专用模型，验证「行动基础模型」的统一性假说。" },
        { id: "hint26", name: "HINT", title: "HINT: Human-Intent Inception for Long-Horizon Robot Manipulation", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.02653",
          summary: "从一条总指令持续「孵化」人类意图，随视觉演化自适应的长程 VLA。",
          purpose: "人给一句简单总意图就能完成复杂操作并随环境演化持续调整，现有 VLA 做不到。",
          method: "人类意图嵌入式设计，把总指令与演化观测持续耦合生成分阶段行为。",
          contribution: "长程意图保持的 2026 代表方案，推进「指令→持续推理」的研究议程。" },
        { id: "lmx", name: "LM-X", title: "LM-X: Explainable Action Modeling with Progress, Event, and Uncertainty Prediction for Generalist Robot Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.25757",
          summary: "给通才 VLA 加三个可解释头：进度、事件与不确定性预测。",
          purpose: "VLA 只靠短时程动作预测学长程行为，输出不透明、失败不可预期。",
          method: "在动作建模之上联合预测任务进度、关键事件与不确定性，形成结构化解释信号。",
          contribution: "把可解释性与不确定性带入 VLA 主线，服务监控、纠错与人机协作。" },
        { id: "languagetrainfree", name: "Language-Feedback 纠错", title: "Training-Free Action Correction for VLA Model Failures via Language Feedback", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29967",
          summary: "免训练用语言反馈纠正 VLA 系统性失败，并刻画失败条件边界。",
          purpose: "VLA 部署中的系统性失败能否不经重训、用语言反馈就地修复？",
          method: "系统分析失败发生的条件分布，用语言反馈在推理时校正动作输出。",
          contribution: "「免训练自愈」路线的 2026 代表，闭环纠错从训练时推向推理时。" },
        {"id": "avavla", "name": "AVA-VLA", "title": "AVA-VLA: Improving Vision-Language-Action Models with Active Visual Attention", "year": 2026, "venue": "CVPR 2026 (Highlight)", "status": "已发表", "url": "https://arxiv.org/abs/2511.18960", "summary": "把 VLA 重构为部分可观测决策：基于递归信念状态主动重加权视觉注意力。", "purpose": "多数 VLA 逐帧独立处理视觉，隐含马尔可夫假设，历史信息被浪费。", "method": "将策略学习重构为 POMDP，递归信念状态对视觉 token 做主动注意力重加权。", "contribution": "LIBERO/CALVIN 领先并迁移真机双臂，CVPR 2026 Highlight。"},
        {"id": "hifvla", "name": "HiF-VLA", "title": "HiF-VLA: Hindsight, Insight and Foresight through Motion Representation for Vision-Language-Action Models", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2512.09928", "summary": "用「运动」做时序上下文：事后-当下-事前三重视角治 VLA 时间短视。", "purpose": "VLA 缺乏时序记忆与世界动态表征，长时程操作前后不一致。", "method": "以运动表征为桥梁构建 hindsight/insight/foresight 三段式时间上下文注入 VLA。", "contribution": "长时程操作时间一致性显著提升，CVPR 2026 时间建模方向代表。"},
        {"id": "acotvla", "name": "ACoT-VLA", "title": "ACoT-VLA: Action Chain-of-Thought for Vision-Language-Action Models", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2601.11404", "summary": "动作本身就是思维链：用 Action CoT 取代语言/图像中间推理。", "purpose": "语言 CoT 与最终动作之间存在语义鸿沟，推理得对不代表做得对。", "method": "以动作序列自身作为链式思维中间载体，推理与执行统一在同一表示空间。", "contribution": "通用操作策略性能提升，具身 CoT 路线在 CVPR 2026 的延续（接 ECoT）。"},
        {"id": "fastthinkact", "name": "Fast-ThinkAct", "title": "Fast-ThinkAct: Efficient Vision-Language-Action Reasoning via Verbalizable Latent Planning", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2601.09708", "summary": "可言语化的潜规划：推理型 VLA 既保留泛化又砍掉长 CoT 延迟。", "purpose": "推理型 VLA 的长思维链推理延迟过高，真机不可用。", "method": "把推理轨迹压缩为可言语化验证的潜在规划 token，兼顾可解释与高效。", "contribution": "推理型 VLA 实时化代表（CVPR 2026），与 RAD/ELASTIC 同题。"},
        {"id": "st4vla", "name": "ST4VLA", "title": "ST4VLA: Spatially Guided Training for Vision-Language-Action Models", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.10109", "summary": "空间定位预训练 + 空间引导动作后训练，唤醒 VLM 的空间知识。", "purpose": "VLM 预训练的空间知识未被动作学习利用，VLA 空间泛化弱。", "method": "两阶段训练：先空间定位预训练，再以空间信号引导的动作后训练对齐。", "contribution": "SimplerEnv Google Robot 66.1→84.6，ICLR 2026 空间接地代表。"}
      ]
    },
    {
      id: "vla_latent", name: "潜动作与无动作视频学习",
      question: "没有动作标签的海量人类视频，如何变成 VLA 的训练燃料？",
      papers: [
        { id: "lapa", name: "LAPA", title: "LAPA: Latent Action Pretraining from Videos", year: 2025, venue: "ICLR 2025 (MIT-IBM等)", status: "已发表", url: "https://arxiv.org/abs/2410.11758",
          summary: "VQ-VAE 从相邻帧学离散潜动作，无动作标注视频预训练 VLA。",
          purpose: "真机动作标注数据太贵太少，人类视频没有动作标签却近乎无限。",
          method: "先学帧间潜动作量化器，再让 VLM 预测潜动作完成预训练，最后少量真机数据把潜动作映射到真实控制。",
          contribution: "超越用真实动作标签训练的 SOTA（+6.2%），预训练效率比 OpenVLA 高 30 倍，打开「视频→动作」大门。" },
        { id: "gr2", name: "GR-2", title: "GR-2: A Generative Video-Language-Action Model with Web-Scale Knowledge for Robot Manipulation", year: 2024, venue: "arXiv 2024 (ByteDance)", status: "预印本", url: "https://arxiv.org/abs/2410.06158",
          summary: "3800 万视频片段生成式预训练，再联合微调视频生成与动作预测。",
          purpose: "用互联网视频里的「世界如何演化」知识武装操作策略。",
          method: "GPT 式视频生成预训练捕捉时序动态，微调时同时生成未来视频与动作轨迹，视频预测充当世界模型正则。",
          contribution: "105 任务 97.7% 成功率与强泛化，证明「视频生成预训练 → 动作微调」配方的威力。" },
        { id: "univla_latent", name: "UniVLA", title: "UniVLA: Learning to Act Anywhere with Task-Centric Latent Actions", year: 2025, venue: "RSS 2025 (Best Paper Finalist)", status: "已发表", url: "https://arxiv.org/abs/2505.06111",
          summary: "任务中心潜动作分离「任务相关/无关」动态，跨具身通用策略。",
          purpose: "潜动作预训练会被镜头运动等无关动态污染，且需服务多种机器人形态。",
          method: "语言引导的潜动作模型剥离任务无关动态，在跨具身视频上预训练通才策略，再接各形态解码头。",
          contribution: "以 1/20 预训练算力超越 OpenVLA，导航与操作通吃，潜动作路线的集大成者。" },
        { id: "moto", name: "Moto", title: "Moto: Latent Motion Token as the Bridging Language for Robot Manipulation", year: 2025, venue: "ICCV 2025 (北大等)", status: "已发表", url: null,
          summary: "以「运动 token」为中介语言桥接视频预训练与动作微调。",
          purpose: "同 LAPA 动机：视频里蕴含操作知识但缺少动作标签。",
          method: "无监督学习运动 tokenizer，GPT 式预训练运动序列，微调时对齐真实控制。",
          contribution: "与 LAPA/UniVLA 共同构成潜动作三部曲，验证该路线的可重复性。" },
        { id: "acrosswam", name: "AcrossWAM / LaWAM 系", title: "AcrossWAM 1.0: A Modular Latent World-Action Stack for Compact Robot Policies", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29937",
          summary: "潜空间世界-动作栈的模块化实现：在特征空间预测动作相关子目标。",
          purpose: "LaWAM 提出的潜 WAM 形式化此前缺少完整的模块化实现与开源栈。",
          method: "以动作相关的视觉子目标（特征空间）替代像素未来，模块化组合世界模型与策略。",
          contribution: "把「潜 WAM」从概念变成可复用技术栈，与 DELE-w0.5 共推非像素化 WAM 路线。" },
        {"id": "como", "name": "CoMo", "title": "CoMo: Learning Continuous Latent Motion from Internet Videos for Scalable Robot Learning", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2505.17006", "summary": "连续潜运动表征：避开 VQ 离散化信息损失的视频-机器人预训练。", "purpose": "离散潜动作（LAPA 系）的 VQ 量化丢失细粒度动态。", "method": "从互联网视频无监督学习连续潜在运动表征并迁移机器人学习。", "contribution": "CVPR 2026 潜动作路线升级，连续化是 LAPA→UniVLA 之后的下一步。"},
        {"id": "vipra", "name": "ViPRA", "title": "ViPRA: Video Prediction for Robot Actions", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2511.07732", "summary": "视频预测模型提取运动中心潜动作，100-200 条演示即可上手。", "purpose": "潜动作预训练与流匹配解码如何以最少真机数据对接？", "method": "无动作视频预训练视频-语言模型预测未来，提取运动中心潜动作，少量演示微调流匹配头。", "contribution": "SIMPLER +16%、真机 +13%，ICLR 2026 数据效率标杆。"},
        {"id": "tap_icml", "name": "TAP", "title": "Learning to Move Before Learning to Do: Task-Agnostic Pretraining for VLAs", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2607.02466", "summary": "先学动再学做：无标注交互数据自监督学运动先验。", "purpose": "VLA 依赖百万级专家轨迹，无标注机器人数据被浪费。", "method": "自监督逆动力学从无标注交互数据学运动先验，再少量专家数据做语言接地。", "contribution": "SIMPLER 上匹敌百万演示模型，相机扰动下真机仍保留 25% 成功率（基线归零），ICML 2026。"}
      ]
    },
    {
      id: "vla_efficient", name: "高效 VLA 与实时推理",
      question: "VLA 太大太慢，如何在边缘设备上跑到控制频率？",
      papers: [
        { id: "tinyvla", name: "TinyVLA", title: "TinyVLA: Towards Fast, Data-Efficient Vision-Language-Action Models for Robotic Manipulation", year: 2025, venue: "RA-L 2025 (北大)", status: "已发表", url: "https://arxiv.org/abs/2409.12514",
          summary: "亚十亿参数 + 扩散动作头，无需机器人预训练即可快速上手。",
          purpose: "现有 VLA 推理慢、还依赖昂贵的大规模机器人数据预训练。",
          method: "高效小型 VLM 骨干直接微调 + 扩散策略解码器，跳过机器人数据预训练阶段。",
          contribution: "速度与数据效率双赢且性能可比 OpenVLA，证明「小而快」路线可行。" },
        { id: "smolvla", name: "SmolVLA", title: "SmolVLA: A Vision-Language-Action Model for Affordable and Efficient Robotics", year: 2025, venue: "arXiv 2025 (Hugging Face)", status: "预印本", url: "https://arxiv.org/abs/2506.01844",
          summary: "450M 参数、消费级 GPU 可训、社区数据训练的开源 VLA。",
          purpose: "把 VLA 的训练与部署门槛降到个人开发者水平。",
          method: "小型 VLM + flow matching 动作专家，跳层特征、视觉 token 缩减、异步推理栈解耦感知与执行。",
          contribution: "性能媲美 10 倍大的 VLA，异步推理提速 30%，成为 LeRobot 社区标准模型。" },
        { id: "openvlaoft", name: "OpenVLA-OFT", title: "Fine-Tuning Vision-Language-Action Models: Optimizing Speed and Success", year: 2025, venue: "RSS 2025 (Stanford/Berkeley等)", status: "已发表", url: "https://arxiv.org/abs/2502.19645",
          summary: "系统研究 VLA 微调配方：并行解码+连续动作+L1 目标，快 26 倍。",
          purpose: "自回归 VLA 微调后依旧慢且成功率不稳，缺少被验证的适配配方。",
          method: "消融解码方式/动作表示/学习目标，提出优化微调（OFT）配方并在 LIBERO 与真机 ALOHA 验证。",
          contribution: "LIBERO 97.1% SOTA、吞吐提升 26 倍，OFT 配方被社区广泛沿用。" },
        { id: "deervla", name: "DeeR-VLA", title: "DeeR-VLA: Dynamic Inference of Multimodal Large Language Models for Efficient Robot Execution", year: 2024, venue: "NeurIPS 2024 (北大等)", status: "已发表", url: null,
          summary: "按场景难度动态早退的 VLA 推理框架，算力省 5.2-6 倍。",
          purpose: "多数控制时刻并不需要全模型容量，恒定满血推理浪费严重。",
          method: "多出口架构 + 动态终止准则，简单情形浅层出动作，复杂情形走全深度。",
          contribution: "LLM 算力降至 1/5.2~1/6 且性能不降，确立「自适应计算」在 VLA 的价值。" },
        { id: "minerva26", name: "MINERVA", title: "MINERVA: How Small Can a Manipulation Policy Be and Still Solve LIBERO?", year: 2026, venue: "arXiv 2026.09 (MIT等)", status: "预印本", url: "https://arxiv.org/abs/2609.03715",
          summary: "冷静测量：LIBERO 到底需要多大的模型？答案远小于十亿级。",
          purpose: "VLA 军备竞赛动辄数十亿参数，但基准真正需要的容量从未被测量。",
          method: "系统性压缩实验寻找 LIBERO 可解的最小策略容量与关键设计要素。",
          contribution: "对 VLA 规模竞赛的当头棒喝，引发「基准容量 vs 模型规模」的领域反思。" },
        { id: "fewerlayers", name: "Fewer Layers", title: "Finetuning Vision-Language-Action Models Requires Fewer Layers Than You Think", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.20246",
          summary: "VLA 微调只需动用远少于想象的层数，算力可大幅节省。",
          purpose: "数十亿参数 VLA 的全参数微调成本高昂，阻碍广泛适配。",
          method: "层选择分析找出微调真正需要更新的子集，用极小可训练参数达成可比效果。",
          contribution: "给社区一个实用的「穷微调」配方，参数高效适配 VLA 的 2026 代表。" },
        { id: "phyai", name: "PhyAI", title: "PhyAI: Real-Time Physical AI at the Edge, Scalable Rollouts in the Cloud", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.03682",
          summary: "物理 AI 全生命周期推理系统：云端 rollout、边缘服务与板载部署统一。",
          purpose: "评测、云 RL rollout、边缘 GPU 服务与板载部署对推理系统的需求截然不同却常被割裂。",
          method: "统一推理基础设施横跨云-边-端，兼顾规模化 rollout 与实时板载控制。",
          contribution: "把「推理系统工程」立为 VLA 落地的一等公民。" }
      ]
    },
    {
      id: "vla_dual", name: "双系统与全身控制",
      question: "慢思考 VLM 与高频全身控制器如何协同？人形机器人怎么办？",
      papers: [
        { id: "helix", name: "Helix", title: "Helix: A Vision-Language-Action Model for Generalist Humanoid Control", year: 2025, venue: "Figure AI 技术报告 (Figure AI)", status: "技术报告", url: "https://www.figure.ai/news/helix",
          summary: "首个人形上身高频（200Hz）全身 VLA，双机器人协作收杂货。",
          purpose: "人形机器人需要同时控制头/躯干/双臂/手指 35+ 自由度且要泛化到新物体。",
          method: "S2（7B VLM，7-9Hz 语义规划）+ S1（80M 视觉运动策略，200Hz 连续全身控制）异步双系统，端到端联训。",
          contribution: "单套权重完成多机器人协作与千类新物体抓取，商用级双系统全身 VLA 的第一个公开范例。" },
        { id: "groot_dreams", name: "GR00T N1.5 / Dreams", title: "GR00T N1.5 and GR00T-Dreams: Neural Trajectories for Humanoid Learning", year: 2025, venue: "NVIDIA 技术报告 (NVIDIA)", status: "技术报告", url: null,
          summary: "用视频世界模型生成「神经轨迹」合成数据，36 小时更新人形基础模型。",
          purpose: "人形真机数据采集极慢，需要合成数据飞轮压缩迭代周期。",
          method: "Cosmos 世界模型按指令生成机器人执行视频，逆动力学提取伪动作，混合真实数据后训练 N1.5。",
          contribution: "新物体/新指令泛化显著提升，展示「世界模型造数据 → VLA 变强」的闭环。" },
        { id: "lbm", name: "LBM", title: "A Careful Examination of Large Behavior Models for Multitask Dexterous Manipulation", year: 2025, venue: "arXiv 2025 (Toyota Research Institute)", status: "预印本", url: "https://arxiv.org/abs/2507.05331",
          summary: "TRI 大行为模型的严谨评测：1800 次真机试验的统计学结论。",
          purpose: "行业宣称多任务预训练有效，但缺乏统计严谨的对照证据。",
          method: "扩散 Transformer 多任务策略在 1700+ 任务预训练，盲测 A/B + 置信区间分析微调收益。",
          contribution: "证实预训练可用 15% 数据达到单任务性能且更稳健，为「规模化行为预训练」提供最严格证据。" },
        { id: "being0", name: "Being-0", title: "Being-0: A Humanoid Robotic Agent with Vision-Language Models and Modular Skills", year: 2025, venue: "arXiv 2025 (清华/银河通用等)", status: "预印本", url: "https://arxiv.org/abs/2503.12533",
          summary: "基础模型 + 模块化技能库的人形智能体框架，边缘设备实时运行。",
          purpose: "全端到端人形控制成本高、脆弱，探索分层模块化替代方案。",
          method: "云端 LLM 规划、板载 VLM 做连接器（把计划翻译成技能调用），底层预训练运动/操作技能库执行。",
          contribution: "在真实楼宇长程任务中高成功率运行，给出「分层混合式人形智能体」的完整参考设计。" },
        { id: "psi0", name: "Ψ₀", title: "Ψ₀: An Open Foundation Model Towards Universal Humanoid Loco-Manipulation", year: 2026, venue: "arXiv 2026.03", status: "预印本", url: "https://arxiv.org/abs/2603.12263",
          summary: "面向通用人形 loco-manipulation 的开放基础模型。",
          purpose: "人形全身移动操作缺少不依赖超大多样数据的开放基座。",
          method: "针对高难度 loco-manipulation 任务的训练配方（避免大而杂共训的常见陷阱）。",
          contribution: "2026 年人形全身控制开源基座的代表之一。" },
        { id: "haf", name: "HAF", title: "HAF: Adapting Generalist VLAs to Humanoid Whole-Body Loco-manipulation via Hierarchical Action Flow and Spectral Latent RL", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.16837",
          summary: "把通用 VLA 适配到人形全身：分层动作流 + 谱潜空间 RL。",
          purpose: "通用 VLA 基础模型无法直接驱动人形全身 loco-manipulation。",
          method: "分层动作流结构化全身行为，谱潜空间强化学习精化低层控制。",
          contribution: "「通才 VLA → 人形专才」适配路径的 2026 代表。" },
        { id: "bfm_scale", name: "BFM Scaling", title: "Scaling Behavior Foundation Model for Humanoid Robots", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.15163",
          summary: "行为基础模型（BFM）的人形规模化：全身协调 + 实时响应 + 泛化。",
          purpose: "人形控制需要自然全身协调、对控制信号的精确实时响应与跨环境泛化同时成立。",
          method: "大规模动作数据上规模化训练行为基础模型，统一参考运动跟踪与泛化控制。",
          contribution: "确立 BFM（行为基础模型）作为 2026 人形控制的主流术语与路线。" },
        { id: "reactivebfm", name: "ReactiveBFM", title: "ReactiveBFM: Reactive Closed-Loop Motion Planning Towards Universal Humanoid Whole-Body Control", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.30362",
          summary: "给行为基础模型装上「反应式闭环规划」，摆脱只重放预定义动作的局限。",
          purpose: "现有 BFM 只执行预定义参考运动，环境变化即失效、无法反应。",
          method: "闭环反应式规划与 BFM 控制先验结合，在线应对环境偏移。",
          contribution: "BFM 从「动作回放器」进化为「可反应控制器」的关键一步。" },
        { id: "clift", name: "CLIFT", title: "CLIFT: Turning Gemini Robotics On-Device into Humanoid Specialists via Non-Invasive Closed-Loop Iterative Fine-Tuning", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.29172",
          summary: "非侵入式闭环迭代微调，把 Gemini Robotics On-Device 改造成人形专才。",
          purpose: "最强的机器人基础模型闭源且难以下游适配新任务/新本体。",
          method: "不动权重的闭环迭代微调（数据筛选-评估-再收集循环），适配端侧闭源模型。",
          contribution: "「闭源基础模型 + 非侵入适配」的工程范式样本，云端大模型落地人形的路径参考。" },
        { id: "fwbcvla", name: "FWBC-VLA", title: "FWBC-VLA: Force-Aware Whole-Body Compensation for Contact-Rich Loco-Manipulation", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03889",
          summary: "力感知全身补偿：在语义动作生成与物理交互控制之间架桥。",
          purpose: "VLA 生成任务级动作，但接触密集 loco-manipulation 需要力觉层面的物理适配。",
          method: "VLA 语义动作之上叠加力感知全身补偿层，实时调节接触力与姿态。",
          contribution: "「语义 VLA + 物理补偿层」双层架构的 2026 代表，向力控社区伸出接口。" },
        { id: "unit26", name: "UniT", title: "UniT: Toward a Unified Physical Language for Human-to-Humanoid Policy Learning and World Modeling", year: 2026, venue: "arXiv 2026.04", status: "预印本", url: "https://arxiv.org/abs/2604.19734",
          summary: "人→人形迁移的统一「物理语言」：策略学习与世界模型共享表征。",
          purpose: "海量第一人称人类数据与机器人之间隔着本体鸿沟，逐点重定向脆弱。",
          method: "学习统一物理语言（物理一致的中间表征），同时服务人-机策略迁移与世界建模。",
          contribution: "跨具身迁移的表征层方案，连接人类视频、世界模型与人形控制三条线。" },
        {"id": "humanoidgpt", "name": "Humanoid-GPT", "title": "Humanoid-GPT: Scaling Data and Structure for Zero-Shot Motion Tracking", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2606.03985", "summary": "20 亿帧动作语料 + GPT 式因果 Transformer 的人形零样本跟踪。", "purpose": "浅层 MLP 跟踪器在敏捷性与泛化之间两难。", "method": "统一 mocap 与大规模自采的重定向语料上预训练因果注意力 Transformer。", "contribution": "零样本人形全身跟踪新标杆（CVPR 2026），BFM 系的规模化跃迁。"},
        {"id": "signbot", "name": "SignBot", "title": "SignBot: Learning Human-to-Humanoid Sign Language Interaction", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2505.24266", "summary": "人形手语交互：动作重定向 + 运动策略 + 生成模块全栈。", "purpose": "让人形机器人用手语与听障人士自然交流。", "method": "人体动作重定向到人形、学习型运动控制策略与手语翻译/回应/生成模块集成。", "contribution": "ICRA 2026 人形社会价值落地样本。"}
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "learning", type: "loop", order: 4, icon: "🎓", color: "#2e8b6d",
  name: "技能学习范式",
  tagline: "模仿、强化、仿真到真机——技能从哪里来？",
  difficulties: [
    {
      id: "l_il", name: "模仿学习与遥操作",
      question: "如何低成本采集高质量演示并稳定克隆成策略？",
      papers: [
        { id: "mobilealoha", name: "Mobile ALOHA", title: "Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2401.02117",
          summary: "3.2 万美元的全身遥操作平台，50 条演示学会炒虾、进电梯。",
          purpose: "把双臂模仿学习从桌面扩展到移动全身任务。",
          method: "移动底座 + 全身遥操作接口采集数据，与静态 ALOHA 数据联合训练动作分块策略。",
          contribution: "证明复杂移动操作任务只需几十条演示 + 联合训练即可 80%+ 成功率，硬件方案全面开源引爆社区。" },
        { id: "umi", name: "UMI", title: "Universal Manipulation Interface: In-The-Wild Robot Teaching Without In-The-Wild Robots", year: 2024, venue: "RSS 2024", status: "已发表", url: "https://arxiv.org/abs/2402.10329",
          summary: "手持夹爪 + GoPro 的野外数据采集接口，人走到哪教到哪。",
          purpose: "机器人数据采集被实验室和真机绑死，无法覆盖真实世界多样性。",
          method: "手持式夹爪装置配鱼眼相机与 SLAM 位姿恢复，策略接口设计保证「人采数据→机器人执行」零差距迁移。",
          contribution: "动态、双手、野外任务的演示成本降一个量级，成为 DexUMI、FastUMI 等生态的源头。" },
        { id: "dexcap", name: "DexCap", title: "DexCap: Scalable and Portable Mocap Data Collection System for Dexterous Manipulation", year: 2024, venue: "RSS 2024", status: "已发表", url: null,
          summary: "便携手部动捕系统，把人手灵巧操作数据直接喂给多指手策略。",
          purpose: "多指灵巧手数据比夹爪更稀缺，遥操作门槛更高。",
          method: "动捕手套 + SLAM 相机记录人手-环境交互，重定向到机械手并用点云策略训练，支持人机协同纠错。",
          contribution: "打通「人手动作→灵巧手技能」采集链路，推动灵巧操作数据规模化。" },
        { id: "hilserl", name: "HIL-SERL", title: "Precise and Dexterous Robotic Manipulation via Human-in-the-Loop Reinforcement Learning", year: 2024, venue: "arXiv 2024 (UC Berkeley)", status: "预印本", url: "https://arxiv.org/abs/2410.21845",
          summary: "人在环 RL 真机 1-2.5 小时练成近 100% 成功率精密技能。",
          purpose: "纯模仿有天花板、纯 RL 真机不安全不高效，寻找工程可用的折中。",
          method: "RLPD 式离线+在线 RL，人类演示与在线纠偏共同塑形，视觉 RL 直接在真机训练。",
          contribution: "主板装配、皮带装配等工业级任务近满分且超人速度，真机 RL 实用化的代表作。" },
        {"id": "unidex", "name": "UniDex", "title": "UniDex: A Robot Foundation Suite for Universal Dexterous Hand Control from Egocentric Human Videos", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.22264", "summary": "灵巧手控制全家桶：大规模数据 + 统一策略 + 第一人称视频采集流。", "purpose": "真机遥操贵、灵巧手异构、控制维度高，通用灵巧操作难成。", "method": "机器人中心数据集 + 统一 VLA 策略 + 自我中心人类视频采集流程三件套。", "contribution": "CVPR 2026 灵巧手基础套件，DexCap 之后的集大成。"},
        {"id": "onehand", "name": "One Hand to Rule Them All", "title": "Canonical Representations for Unified Dexterous Manipulation", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.16712", "summary": "规范表示统一灵巧手：单策略跨手型，零样本迁移三指小手。", "purpose": "每种灵巧手各训一策略不可持续。", "method": "参数化规范表示 + 统一 URDF 格式，策略与手型解耦。", "contribution": "RSS 2026 跨灵巧手泛化代表，「灵巧手的 OXE」。"},
        {"id": "drex", "name": "D-REX", "title": "D-REX: Differentiable Real-to-Sim-to-Real Engine for Learning Dexterous Grasping", "year": 2026, "venue": "ICLR 2026 (Poster)", "status": "已发表", "url": "https://arxiv.org/abs/2603.01151", "summary": "高斯泼溅的可微 real-to-sim-to-real 引擎，力感知灵巧抓取。", "purpose": "灵巧抓取的 sim-to-real 鸿沟与物理参数缺失。", "method": "从真实观测与控制信号辨识物体质量等物理量，可微引擎闭环训练。", "contribution": "ICLR 2026 可微仿真路线在灵巧操作落地。"}
      ]
    },
    {
      id: "l_sim2real", name: "仿真训练与 Sim-to-Real",
      question: "GPU 大规模并行仿真 + 域随机化，能把多少技能搬进现实？",
      papers: [
        { id: "eureka", name: "Eureka", title: "Eureka: Human-Level Reward Design via Coding Large Language Models", year: 2024, venue: "ICLR 2024", status: "已发表", url: "https://arxiv.org/abs/2310.12931",
          summary: "LLM 自动写奖励函数并进化搜索，转笔等超难灵巧任务成为可能。",
          purpose: "RL 的奖励工程是最依赖专家的瓶颈环节。",
          method: "GPT-4 读环境源码生成奖励代码，仿真并行评估后进化式自我改进，输出人类水平奖励。",
          contribution: "83% 任务超人类专家奖励（平均改进 52%），确立「LLM 当奖励工程师」范式。" },
        { id: "dextreme", name: "DeXtreme", title: "DeXtreme: Transfer of Agile In-Hand Manipulation from Simulation to Reality", year: 2023, venue: "ICRA 2023", status: "已发表", url: "https://arxiv.org/abs/2210.13702",
          summary: "GPU 仿真 + 极限域随机化，手内转魔方技能真机复现。",
          purpose: "验证不依赖特制硬件（对比 OpenAI 五指手）也能做 sim-to-real 灵巧操作。",
          method: "Isaac Gym 上亿级样本训练姿态重定向策略，视觉与动力学全面随机化后零样本上真机。",
          contribution: "把灵巧手 sim-to-real 从「奇迹」变成「配方」，推动 GPU 仿真成为标准基础设施。" },
        { id: "anymal_parkour", name: "ANYmal Parkour / Extreme Parkour", title: "Extreme Parkour with Legged Robots", year: 2024, venue: "ICRA 2024", status: "已发表", url: "https://arxiv.org/abs/2309.14341",
          summary: "纯仿真训练的视觉跑酷策略，低成本四足完成跳跃攀爬。",
          purpose: "极限地形运动需要视觉-运动紧耦合，经典控制难以设计。",
          method: "教师-学生蒸馏：特权信息教师在仿真练成，蒸馏给仅用深度相机的学生策略，域随机化迁移真机。",
          contribution: "四足运动能力的展示天花板，教师-学生+域随机化成为 legged locomotion 标准管线。" },
        { id: "hover", name: "HOVER", title: "HOVER: Versatile Neural Whole-Body Controller for Humanoid Robots", year: 2025, venue: "ICRA 2025", status: "已发表", url: "https://arxiv.org/abs/2410.21229",
          summary: "统一多种控制模式的人形全身神经控制器，一网多用。",
          purpose: "人形的运动跟踪、遥操作、导航各用一套控制器，切换与维护成本高。",
          method: "在动捕数据上训练全身跟踪教师，蒸馏成支持多命令空间（关节/根速度/末端位姿）的统一学生策略。",
          contribution: "单一策略覆盖多控制模式并零样本真机，成为人形全身控制的通用底座思路。" },
        { id: "simplerenv", name: "GenSim / RoboGen 路线", title: "RoboGen: Towards Unleashing Infinite Data for Automated Robot Learning via Generative Simulation", year: 2024, venue: "ICML 2024", status: "已发表", url: "https://arxiv.org/abs/2311.01455",
          summary: "生成式仿真：LLM 自动提任务、搭场景、写奖励、产数据。",
          purpose: "仿真任务与场景本身的构建也需要自动化，否则数据多样性受限于人力。",
          method: "基础模型驱动「提议任务→生成场景→定义训练监督→学技能」全自动循环。",
          contribution: "展示无限任务生成的可能性，是「生成式仿真造数据」路线的代表宣言。" },
        {"id": "xloco", "name": "X-Loco", "title": "X-Loco: Towards Generalist Humanoid Locomotion Control via Synergetic Policy Distillation", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.03733", "summary": "协同策略蒸馏的通用人形运动控制。", "purpose": "人形运动控制技能割裂，通用控制器难统一。", "method": "多专家策略协同蒸馏为单一通才运动控制器。", "contribution": "RSS 2026 通才 locomotion 代表，接 HOVER/ReactiveBFM 谱系。"},
        {"id": "polygmap", "name": "PolygMap", "title": "PolygMap: A Perceptive Locomotion Framework for Humanoid Robot Stair Climbing", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2510.12346", "summary": "实时多边形楼梯语义地图：看到哪儿踩到哪儿。", "purpose": "未知楼梯的落脚点规划依赖精确感知。", "method": "实时构建楼梯平面多边形语义地图并据此规划落脚点。", "contribution": "ICRA 2026 感知式爬楼代表，感知-运动接口的经典回归。"},
        {"id": "hf_pretrain", "name": "人形预训练-微调", "title": "Towards Bridging the Gap between Large-Scale Pretraining and Efficient Finetuning for Humanoid Control", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2601.21363", "summary": "SAC 大批量预训练 + 世界模型内高效微调的人形范式。", "purpose": "大规模人形预训练与部署侧高效微调之间缺桥。", "method": "SAC 高 UTD 大批量预训练零样本上真机，再在物理先验世界模型中样本高效微调。", "contribution": "ICLR 2026 人形预训练范式，把「预训练-后训练」叙事完整搬到运动控制。"},
        {"id": "limmt", "name": "LIMMT", "title": "LIMMT: Less is More for Motion Tracking", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2606.06953", "summary": "数据为中心的运动跟踪：3% AMASS 胜过全量。", "purpose": "人形运动跟踪默认堆数据，数据质量被忽视。", "method": "按物理可行性/多样性/复杂度定义数据质量并筛选。", "contribution": "ICML 2026「less is more」证据，数据工程的反直觉发现。"}
      ]
    },
    {
      id: "l_rl_vla", name: "VLA 的强化与后训练",
      question: "SFT 之后呢？RL/偏好优化如何继续压榨 VLA 的性能上限？",
      papers: [
        { id: "grape", name: "GRAPE", title: "GRAPE: Generalizing Robot Policy via Preference Alignment", year: 2025, venue: "ICML 2025", status: "已发表", url: "https://arxiv.org/abs/2411.19309",
          summary: "轨迹级偏好优化对齐 VLA，可按安全/效率等目标定制。",
          purpose: "SFT 只克隆成功演示，模型看不到失败、也无法按目标取舍。",
          method: "轨迹级 DPO 变体，成败轨迹对比 + 阶段性时空约束由 LLM 自动生成代价，迭代偏好优化。",
          contribution: "已见/未见任务成功率 +51.8%/+58.2%，且可灵活切换对齐目标（安全率 -37.5% 碰撞），VLA 偏好对齐开山作。" },
        { id: "rldg", name: "ConRFT", title: "ConRFT: A Reinforced Fine-tuning Method for VLA Models via Consistency Policy", year: 2025, venue: "RSS 2025", status: "已发表", url: null,
          summary: "一致性策略做真机强化微调，VLA 成功率 55%→90%+。",
          purpose: "SFT 后的 VLA 在接触密集任务上不稳定，需要真机 RL 继续打磨。",
          method: "离线+在线两阶段强化微调，一致性目标统一行为克隆与 Q 学习，人在环安全干预。",
          contribution: "45-90 分钟真机训练平均成功率 96.3%，展示 VLA「后训练强化」的巨大空间。" },
        { id: "vlarl_simple", name: "SimpleVLA-RL", title: "SimpleVLA-RL: Scaling VLA Training via Reinforcement Learning", year: 2025, venue: "arXiv 2025", status: "预印本", url: "https://arxiv.org/abs/2509.09674",
          summary: "把 LLM 的 RLVR（可验证奖励强化学习）配方搬到 VLA，1 条演示起步。",
          purpose: "VLA 依赖大规模演示，SFT 数据枯竭后如何继续 scaling？",
          method: "仅用任务成败作为可验证奖励，veRL 框架上对 OpenVLA-OFT 做大规模交互式 RL，探索增强技巧。",
          contribution: "LIBERO 达 SOTA 且单演示冷启动下 RL 大幅超越 SFT，发现「pushcut」等 RL 涌现新行为。" },
        { id: "rlvla_gen", name: "RIPT-VLA", title: "Interactive Post-Training for Vision-Language-Action Models (RIPT-VLA)", year: 2025, venue: "NeurIPS 2025", status: "已发表", url: null,
          summary: "稀疏二值奖励的交互式后训练范式，一条演示救活近乎失败的模型。",
          purpose: "让 VLA 摆脱「离线数据分布」束缚，在交互中自我改进。",
          method: "动态轨迹采样 + leave-one-out 优势估计的交互式 RL，仅用成功/失败信号。",
          contribution: "QueST 从 4% 提到 97%（+93 点），确立交互式后训练作为 VLA 第三训练阶段。" },
        { id: "pave", name: "PAVE", title: "PAVE: Predictive Alignment and Value-Guided Evolution for World-Action Policies", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.30378",
          summary: "用世界模型对齐 + 价值引导进化后训练世界-动作策略，补行为克隆两大缺口。",
          purpose: "行为克隆既不要求表征懂「动作后果」，也无法从失败信号中进化。",
          method: "预测对齐（动作表征对齐世界模型）与价值引导进化（进化搜索 + 价值评估）双机制。",
          contribution: "把世界模型监督与类 RL 进化统一进后训练框架，2026 WM×RL 融合代表。" },
        { id: "retailvla", name: "Retail 人形 VLA", title: "Closing the Lab-to-Store Gap: A Data-Efficient Post-Training and Experience-Driven Learning VLA Framework for Retail Humanoids", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.20345",
          summary: "零售人形的「实验室→门店」闭环：数据高效后训练 + 经验驱动持续学习。",
          purpose: "基准分数与真实门店可靠运营之间存在鸿沟（执行错误、分布偏移、人员交互）。",
          method: "数据高效后训练叠加部署经验回流的经验驱动学习框架，面向零售场景工程化。",
          contribution: "VLA 商业化落地的完整案例研究，展示部署后学习飞轮的实际形态。" },
        {"id": "timerewarder", "name": "TimeRewarder", "title": "TimeRewarder: Learning Dense Reward from Passive Videos via Frame-wise Temporal Distance", "year": 2026, "venue": "ICML 2026 (Spotlight)", "status": "已发表", "url": "https://arxiv.org/abs/2509.26627", "summary": "被动视频学逐帧时距当稠密奖励：Meta-World 9/10 近满分。", "purpose": "RL 后训练缺稠密奖励，人工设计不可扩展。", "method": "从被动视频学习帧间时距函数作为任务进度奖励。", "contribution": "ICML 2026 Spotlight，视频先验→奖励信号的代表作。"},
        {"id": "badbehavior", "name": "Bad Behavior Data", "title": "Position: Good Embodied Reward Models Need Bad Behavior Data", "year": 2026, "venue": "ICML 2026 (Position Spotlight)", "status": "已发表", "url": "https://arxiv.org/abs/2606.01036", "summary": "立场论文：具身奖励模型必须喂「坏机器人数据」。", "purpose": "只用成功数据训练的奖励模型系统性高估不安全动作。", "method": "论证失败/次优/危险行为数据对奖励模型的价值并呼吁社区发布。", "contribution": "ICML 2026 Position Spotlight，为数据生态提出新议程。"}
      ]
    },
    {
      id: "l_data", name: "数据引擎与合成数据",
      question: "真机数据永远不够——生成、增广、重定向如何造出下一个数量级？",
      papers: [
        { id: "mimicgen", name: "MimicGen", title: "MimicGen: A Data Generation System for Scalable Robot Learning using Human Demonstrations", year: 2023, venue: "CoRL 2023", status: "已发表", url: "https://arxiv.org/abs/2310.17596",
          summary: "200 条人类演示自动扩成 5 万条，跨场景跨物体自动改编。",
          purpose: "遥操作演示太贵，希望机器自己「改写」少量演示适配新情境。",
          method: "把演示切成以物体为中心的片段，按新场景中物体位姿变换拼接并闭环执行验证。",
          contribution: "合成数据训练效果媲美更多人类数据，成为 RoboCasa 等大规模仿真数据管线的核心组件。" },
        { id: "rovi_aug", name: "RoVi-Aug", title: "RoVi-Aug: Robot and Viewpoint Augmentation for Cross-Embodiment Robot Learning", year: 2024, venue: "CoRL 2024 (Oral)", status: "已发表", url: null,
          summary: "扩散模型把演示「换机器人、换视角」，零样本跨具身部署。",
          purpose: "跨具身数据分布失衡，想用生成模型直接改写数据里的机器人本体。",
          method: "细调扩散模型对轨迹视频做机器人替换与视角增广，增广后数据直接训练目标机器人策略。",
          contribution: "无需测试时跨具身对齐即可零样本换机器人，展示「生成式数据编辑」的具身价值。" },
        { id: "dreamgen", name: "DreamGen", title: "DreamGen: Unlocking Generalization in Robot Learning through Neural Trajectories", year: 2025, venue: "arXiv 2025 (NVIDIA)", status: "预印本", url: "https://arxiv.org/abs/2505.12705",
          summary: "视频世界模型生成「神经轨迹」，22 个新动词、10 个新环境凭空解锁。",
          purpose: "让机器人学会从未遥操作采集过的新行为与新环境。",
          method: "微调视频世界模型→生成指令条件的机器人视频→潜动作/逆动力学提取伪动作→训练下游 VLA。",
          contribution: "只用一个环境的遥操数据实现行为与环境双泛化，把「世界模型造数据」推成标准管线（GR00T-Dreams 底层）。" },
        { id: "agibot", name: "AgiBot World / GO-1", title: "AgiBot World Colosseo: A Large-scale Manipulation Platform for Scalable and Intelligent Embodied Systems", year: 2025, venue: "IROS 2025 (Best Paper)", status: "已发表", url: "https://arxiv.org/abs/2503.06669",
          summary: "百万真机轨迹开源数据集（100 台机器人/217 任务）+ 分层 GO-1 模型。",
          purpose: "行业缺少「ImageNet 量级」的高质量真机操作数据底座。",
          method: "标准化场景中众包采集含长程/灵巧任务的百万轨迹，提出 ViLLA（视觉-潜动作-动作）分层预训练。",
          contribution: "数据规模与质量新标杆，GO-1 较 RDT 等提升 30%+，中国具身数据生态的代表。" },
        { id: "robotok", name: "RoboTok", title: "RoboTok: An Internet-Scale Data Engine for Human Demonstration Retrieval and Dexterous Manipulation Learning", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03199",
          summary: "互联网级人类演示检索引擎：从海量网络视频按需取灵巧操作示教。",
          purpose: "机器人数据采集贵且覆盖不了长尾，网络人类演示是唯一接近无限的数据源。",
          method: "互联网规模视频的演示检索引擎 + 灵巧操作学习管线，按任务语义匹配可迁移演示。",
          contribution: "把「检索即数据引擎」做到互联网尺度，2026 数据引擎路线的新范式。" },
        { id: "saber", name: "SABER", title: "SABER: A Scalable Action-Based Embodied Dataset for Real-World VLA Adaptation", year: 2026, venue: "arXiv 2026.05", status: "预印本", url: "https://arxiv.org/abs/2605.09613",
          summary: "面向真实 VLA 适配的大规模动作化具身数据集。",
          purpose: "通用基础模型在复杂未见任务上表现平平，缺的是领域真实的动作数据。",
          method: "大规模采集带动作标注的真实领域数据，专攻 VLA 下游适配。",
          contribution: "补齐「预训练语料易得、适配数据难求」的缺口。" },
        { id: "teleopit", name: "Teleopit", title: "Teleopit: A Full-Embodiment Humanoid Teleoperation System", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.01834",
          summary: "全本体人形遥操作：全身运动、灵巧手连续控制与视角控制一体化。",
          purpose: "人形示教采集需要全身-双手-视角协同，现有系统各缺一块。",
          method: "全身动位映射 + 连续灵巧手控制 + 主动视角控制的一体化遥操作系统。",
          contribution: "人形数据采集基础设施的 2026 代表，直接服务 BFM/WAM 数据管线。" },
        {"id": "robointer", "name": "RoboInter", "title": "RoboInter: A Holistic Intermediate Representation Suite Towards Robotic Manipulation", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.09973", "summary": "中间表示全家桶：标注工具 + 23 万轨迹稠密标注 + VQA 基准。", "purpose": "VLA 缺乏统一中间表示（几何/接触/语义）的标注与训练资产。", "method": "半自动标注流水线、稠密标注数据集、具身 VQA 基准与 plan-then-execute 框架打包。", "contribution": "ICLR 2026 表示层基建，中间表示研究的工具底座。"}
      ]
    }
  ]
});
