// 具身智能研究图谱 · 数据文件 1/4：多模态感知与表征、世界模型
window.EAI_MODULES = window.EAI_MODULES || [];

window.EAI_MODULES.push({
  id: "perception", type: "loop", order: 1, icon: "👁", color: "#3b7dd8",
  name: "多模态感知与表征",
  tagline: "机器人如何把像素、点云、触觉信号变成可供决策的结构化状态？",
  difficulties: [
    {
      id: "p_3d", name: "空间与 3D 理解",
      question: "如何让大模型真正理解三维空间关系、距离与物体几何？",
      papers: [
        { id: "threedllm", name: "3D-LLM", title: "3D-LLM: Injecting the 3D World into Large Language Models", year: 2023, venue: "NeurIPS 2023", status: "已发表", url: "https://arxiv.org/abs/2307.12981",
          summary: "把 3D 点云与特征注入 LLM，使其能做 3D 描述、问答与规划，开创 3D 基础模型路线。",
          purpose: "解决 LLM/VLM 只见 2D 图像、缺乏空间关系与 affordance 等 3D 世界概念的问题。",
          method: "用多视角渲染特征构建 3D 特征，配合 3D 定位机制把点云对齐进 LLM 输入空间，训练覆盖描述、问答、任务分解等 30 万条 3D-语言数据。",
          contribution: "首批把 3D 世界系统性接入 LLM 的工作，在 ScanQA 等基准显著超越 2D VLM 基线，奠定 3D-语言-具身的联合表征范式。" },
        { id: "pointllm", name: "PointLLM", title: "PointLLM: Empowering Large Language Models to Understand Point Clouds", year: 2024, venue: "ECCV 2024 (Best Paper Candidate)", status: "已发表", url: "https://arxiv.org/abs/2308.16911",
          summary: "点云编码器 + LLM 的物体级 3D 理解模型，配套人评协议。",
          purpose: "让 LLM 直接消化彩色物体点云，弥补图像视角遮挡导致的几何理解缺陷。",
          method: "点云编码器接入 LLaMA，两阶段（对齐 + 指令微调）训练，构建 66 万物体-文本指令数据集。",
          contribution: "在 3D 物体描述任务上人评超过人类标注者一半以上样本，并开源数据与基准，成为物体级 3D-LLM 的标准基线。" },
        { id: "leo", name: "LEO", title: "An Embodied Generalist Agent in 3D World", year: 2024, venue: "ICML 2024", status: "已发表", url: "https://arxiv.org/abs/2311.12871",
          summary: "统一 3D 感知、推理、规划与行动的具身通才智能体。",
          purpose: "回应「通才智能体必须活在 3D 世界」的命题，检验单一模型能否覆盖 3D 描述、问答、导航与操作。",
          method: "以 3D 场景为中心的两阶段训练（3D 视觉-语言对齐 → 视觉-语言-行动指令微调），共享 LLM 骨干输出文本与动作 token。",
          contribution: "单模型在 3D 描述/问答/具身推理/导航/操作全线可用，证明 3D 场景表征可以成为具身通才的统一底座。" },
        { id: "spatialvlm", name: "SpatialVLM", title: "SpatialVLM: Endowing Vision-Language Models with Spatial Reasoning Capabilities", year: 2024, venue: "CVPR 2024", status: "已发表", url: "https://arxiv.org/abs/2401.12168",
          summary: "用 20 亿级合成空间问答数据把定量空间推理灌入 VLM。",
          purpose: "解决 VLM 答不了「A 离 B 多远」「哪个更大」这类定量空间问题、拖累机器人任务的短板。",
          method: "自动化 3D 标注流水线从真实图像生成海量度量级空间 VQA 数据，直接微调 VLM。",
          contribution: "显著提升定性与定量空间推理，可作为机器人奖励标注器与链式空间推理器，催生 SpatialRGPT 等后续方向。" },
        { id: "robopoint", name: "RoboPoint", title: "RoboPoint: A Vision-Language Model for Spatial Affordance Prediction for Robotics", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2406.10721",
          summary: "让 VLM 输出图像上的可操作点坐标，桥接语言指令与低层控制。",
          purpose: "语言模型给出的自由文本动作难以落地，需要一种精确、通用的空间落点输出接口。",
          method: "合成数据指令微调 VLM，统一输出满足空间关系约束的 2D 点，再经深度反投影为 3D 目标。",
          contribution: "以「预测点」为通用接口，在真机导航与操作上超越 GPT-4V 类基线，成为空间 affordance 输出范式的代表。" }
      ]
    },
    {
      id: "p_afford", name: "Affordance 与可交互性",
      question: "如何从视觉中预测「哪里能抓、往哪儿推、怎么交互」？",
      papers: [
        { id: "where2act", name: "Where2Act", title: "Where2Act: From Pixels to Actions for Articulated 3D Objects", year: 2021, venue: "ICCV 2021", status: "已发表", url: "https://arxiv.org/abs/2101.02692",
          summary: "从像素/点云预测铰接物体每个点的可操作性与动作先验。",
          purpose: "机器人面对柜门、抽屉等铰接物体时，需要知道在哪个点施加什么原子动作才有效。",
          method: "在仿真中大规模交互试错，学习逐点的 actionability 打分与动作提议网络。",
          contribution: "确立「逐点 affordance 预测」范式，成为后续交互感知与操作预训练的经典起点。" },
        { id: "vrb", name: "VRB", title: "Affordances from Human Videos as a Versatile Representation for Robotics", year: 2023, venue: "CVPR 2023", status: "已发表", url: "https://arxiv.org/abs/2304.08488",
          summary: "从人类视频学接触点与轨迹方向，直接迁移到机器人。",
          purpose: "利用海量人类日常视频（而非昂贵机器人数据）获得可迁移的交互先验。",
          method: "从人视频中估计接触热点与手腕轨迹方向，训练视觉 affordance 模型，接入模仿/探索/RL 等多种下游范式。",
          contribution: "证明人类视频 affordance 可零改动服务四种机器人学习范式，推动「以人为师」的数据路线。" },
        { id: "ram_afford", name: "RAM", title: "RAM: Retrieval-Based Affordance Transfer for Generalizable Zero-Shot Robotic Manipulation", year: 2024, venue: "CoRL 2024", status: "已发表", url: null,
          summary: "检索异构数据中的 affordance 示例并迁移到新场景，实现零样本操作。",
          purpose: "单一模型难以覆盖开放世界物体，希望用检索机制复用异构 affordance 知识。",
          method: "构建跨来源（人视频、机器人数据、仿真）affordance 记忆库，检索-对齐-迁移到当前观测并生成操作。",
          contribution: "零样本泛化到多类新物体与场景，展示「检索式 affordance 记忆」在操作中的价值。" },
        { id: "graspanything", name: "SceneFun3D", title: "SceneFun3D: Fine-Grained Functionality and Affordance Understanding in 3D Scenes", year: 2024, venue: "CVPR 2024 (Oral)", status: "已发表", url: null,
          summary: "室内场景级细粒度功能交互元素（把手、按钮、旋钮）标注与基准。",
          purpose: "场景级操作需要定位「功能元素」而不只是物体框，此前缺少高质量 3D 功能标注。",
          method: "在高保真室内扫描上标注 1.4 万+ 功能交互元素及运动参数与语言描述，定义功能定位与技能预测任务。",
          contribution: "提供场景级 affordance 理解的标准基准，暴露现有 3D 模型在功能理解上的显著差距。" }
      ]
    },
    {
      id: "p_grasp", name: "抓取与位姿估计",
      question: "通用抓取检测与 6D 位姿估计如何做到开放物体、开箱即用？",
      papers: [
        { id: "graspnet", name: "GraspNet-1Billion", title: "GraspNet-1Billion: A Large-Scale Benchmark for General Object Grasping", year: 2020, venue: "CVPR 2020", status: "已发表", url: "https://graspnet.net",
          summary: "十亿级抓取姿态标注数据集 + 端到端抓取位姿预测网络。",
          purpose: "通用抓取缺少大规模真实标注与统一评测协议。",
          method: "真实杂乱场景采集 + 解析式力闭合标注生成超 10 亿抓取姿态，提出端到端点云抓取网络与在线评测。",
          contribution: "成为通用抓取的事实标准基准，支撑后续 AnyGrasp 等系列工作。" },
        { id: "anygrasp", name: "AnyGrasp", title: "AnyGrasp: Robust and Efficient Grasp Perception in Spatial and Temporal Domains", year: 2023, venue: "T-RO 2023", status: "已发表", url: "https://arxiv.org/abs/2212.08333",
          summary: "时空联合的通用抓取感知，达到接近人类挑选的抓取成功率。",
          purpose: "把抓取检测做成对任意刚体、动态场景都稳定可用的商用级组件。",
          method: "几何处理与抓取稳定性建模结合，时序上跟踪抓取假设，输出稠密 7-DoF 抓取。",
          contribution: "杂乱场景真机抓取成功率约 93%，被大量具身系统直接用作抓取底座。" },
        { id: "contactgraspnet", name: "Contact-GraspNet", title: "Contact-GraspNet: Efficient 6-DoF Grasp Generation in Cluttered Scenes", year: 2021, venue: "ICRA 2021", status: "已发表", url: "https://arxiv.org/abs/2103.14127",
          summary: "把 6-DoF 抓取表示为场景点上的接触，实现高效端到端生成。",
          purpose: "全 6-DoF 抓取生成在杂乱场景中搜索空间过大、效率低。",
          method: "以观测点云的接触点为锚，将抓取降维为逐点回归问题，端到端输出抓取分布。",
          contribution: "无需物体 CAD 即可在杂乱场景高效抓取，成为 6-DoF 抓取的高引用基线。" },
        { id: "foundationpose", name: "FoundationPose", title: "FoundationPose: Unified 6D Pose Estimation and Tracking of Novel Objects", year: 2024, venue: "CVPR 2024 (Highlight)", status: "已发表", url: "https://arxiv.org/abs/2312.08344",
          summary: "统一「有模型/无模型」两种设定的新物体 6D 位姿估计与跟踪基础模型。",
          purpose: "传统位姿估计依赖每个物体单独训练，无法即插即用于新物体。",
          method: "大规模合成数据 + LLM 辅助文本生成训练统一框架，神经隐式表征支持无 CAD 设定，位姿假设生成-打分。",
          contribution: "多基准大幅领先，成为操作/AR 中新物体位姿的默认选择，体现「位姿基础模型」路线。" }
      ]
    },
    {
      id: "p_map", name: "开放词汇语义地图与场景图",
      question: "如何把开放词汇视觉概念组织成可查询、可规划的空间记忆？",
      papers: [
        { id: "conceptgraphs", name: "ConceptGraphs", title: "ConceptGraphs: Open-Vocabulary 3D Scene Graphs for Perception and Planning", year: 2024, venue: "ICRA 2024", status: "已发表", url: "https://arxiv.org/abs/2309.16650",
          summary: "增量构建开放词汇 3D 场景图，供 LLM 规划直接查询。",
          purpose: "稠密语义地图难扩展、难推理，需要物体中心、关系显式的空间记忆。",
          method: "多视角融合 2D 基础模型的物体分割与特征，增量聚合为节点，用 LLM/VLM 补物体关系边。",
          contribution: "内存高效且可自然语言查询，成为具身规划中「场景图记忆」的代表实现。" },
        { id: "clipfields", name: "CLIP-Fields", title: "CLIP-Fields: Weakly Supervised Semantic Fields for Robotic Memory", year: 2023, venue: "RSS 2023", status: "已发表", url: "https://arxiv.org/abs/2210.05663",
          summary: "把 CLIP 特征蒸馏进隐式空间场，得到可语言查询的机器人语义记忆。",
          purpose: "机器人需要「哪里有什么」的可查询空间记忆，且不想依赖人工标注。",
          method: "学习从 3D 坐标到 CLIP/Detic 嵌入的隐式映射，弱监督训练，语言查询即最近邻检索。",
          contribution: "开创隐式「语义场」记忆路线，支撑语言导航与拾放任务。" },
        { id: "hovsg", name: "HOV-SG", title: "Hierarchical Open-Vocabulary 3D Scene Graphs for Language-Grounded Robot Navigation", year: 2024, venue: "RSS 2024", status: "已发表", url: null,
          summary: "楼层-房间-物体的分层开放词汇场景图，支持跨楼层语言导航。",
          purpose: "平铺地图在建筑级尺度失效，长指令导航需要层次化空间抽象。",
          method: "开放词汇分割 + 分层聚合构图（楼层/房间/物体），LLM 在图上解析指令并逐层定位。",
          contribution: "在大型多层环境实现语言目标导航，验证层次场景图对长程任务的必要性。" },
        { id: "hydra", name: "Hydra", title: "Hydra: A Real-time Spatial Perception System for 3D Scene Graph Construction and Optimization", year: 2022, venue: "RSS 2022", status: "已发表", url: "https://arxiv.org/abs/2201.13360",
          summary: "实时增量构建含房间/楼层的 3D 动态场景图的完整系统。",
          purpose: "场景图此前只能离线构建，机器人需要在线、闭环一致的空间抽象。",
          method: "分层 SLAM 前后端：实时网格与物体提取、房间分割、回环时全图一致性优化。",
          contribution: "首个实时 3D 场景图系统，成为空间感知-记忆一体化的系统级标杆。" }
      ]
    },
    {
      id: "p_touch", name: "触觉与多感官融合",
      question: "触觉/力觉/听觉如何补上视觉盲区，支撑接触密集型操作？",
      papers: [
        { id: "digit", name: "DIGIT", title: "DIGIT: A Novel Design for a Low-Cost Compact High-Resolution Tactile Sensor with Application to In-Hand Manipulation", year: 2020, venue: "RA-L 2020", status: "已发表", url: "https://arxiv.org/abs/2005.14679",
          summary: "低成本高分辨率视触觉传感器，触觉研究的硬件基石。",
          purpose: "触觉研究缺少便宜、紧凑、可量产的高分辨率传感器。",
          method: "基于凝胶成像的视触觉设计，专为手内操作的指尖集成优化，开源可制造。",
          contribution: "被 Meta 等广泛量产使用，直接催生 Sparsh 等触觉表征预训练生态。" },
        { id: "sparsh", name: "Sparsh", title: "Sparsh: Self-Supervised Touch Representations for Vision-Based Tactile Sensing", year: 2024, venue: "CoRL 2024", status: "已发表", url: null,
          summary: "跨传感器的视触觉自监督表征基础模型家族。",
          purpose: "触觉数据标注稀缺且传感器异构，逐任务训练无法规模化。",
          method: "在 46 万+ 触觉图像上做掩码/蒸馏式自监督预训练，统一支持 DIGIT、GelSight 等传感器与力估计、滑移检测等下游任务。",
          contribution: "建立触觉「预训练 backbone + 轻量微调」范式，多任务平均大幅超越端到端基线。" },
        { id: "unitouch", name: "UniTouch", title: "Binding Touch to Everything: Learning Unified Multimodal Tactile Representations", year: 2024, venue: "CVPR 2024", status: "已发表", url: null,
          summary: "把多种触觉传感器对齐到视觉-语言嵌入空间的统一触觉表征。",
          purpose: "触觉与视觉/语言模态割裂，无法复用大模型生态做零样本触觉理解。",
          method: "以图像嵌入为锚，对比学习把异构触觉信号绑定进 CLIP 式共享空间，配可学习传感器 token。",
          contribution: "实现零样本触觉分类、触觉-图像生成与跨传感器泛化，打通触觉与多模态大模型。" },
        { id: "seehearfeel", name: "See-Hear-Feel", title: "See, Hear, and Feel: Smart Sensory Fusion for Robotic Manipulation", year: 2022, venue: "CoRL 2022", status: "已发表", url: null,
          summary: "视觉+听觉+触觉三模态融合显著提升精细操作成功率。",
          purpose: "验证接触密集任务（如倒豆、插拔）中多感官互补的量化收益。",
          method: "自注意力跨模态融合三种传感流，模仿学习训练策略并做逐模态消融。",
          contribution: "系统量化听觉与触觉对操作的增益，推动多感官策略成为精细操作默认配置。" },
        { id: "n0foundation", name: "N₀-Foundation", title: "N₀-Foundation: Towards the Age of Tactile Intelligence", year: 2026, venue: "arXiv 2026.08 (北大/上交等)", status: "预印本", url: "https://arxiv.org/abs/2608.29601",
          summary: "触觉智能全景范式：传感硬件、大规模多模态数据、触觉表征学习与标准化评测四位一体。",
          purpose: "触觉是具身智能最滞后的感官，希望像视觉的「基础模型时代」一样系统性地启动触觉智能。",
          method: "整合触觉传感硬件、多模态数据采集、触觉表征预训练与统一评测协议，提出完整的范式路线图与配套基准。",
          contribution: "把「触觉智能」立为独立研究议程，被视为触觉基础模型时代的宣言性工作。" },
        { id: "hapticfm", name: "Haptic FM", title: "The Potential of Haptic Foundation Models", year: 2026, venue: "IEEE CE Magazine 2026", status: "已发表", url: "https://arxiv.org/abs/2608.28664",
          summary: "论证通用触觉感知基础模型的潜力、瓶颈与消费电子/具身落地路径。",
          purpose: "语言与视觉都有基础模型，触觉的泛化感知仍缺位，制约具身 AI 在接触密集场景的表现。",
          method: "系统梳理触觉数据、传感器异构性与跨设备迁移的障碍，给出触觉基础模型的构建路径与评估维度。",
          contribution: "为触觉基础模型确立可行性论证与研究坐标，与 N₀-Foundation 共同构成 2026 触觉智能双宣言。" },
        { id: "vtmuse", name: "VT-MUSE", title: "VT-MUSE: Multimodal Unified Sequential Visuotactile Representation Learning for Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.21290",
          summary: "视觉与触觉在统一序列模型里联合编码的表征学习框架。",
          purpose: "现有方法把视觉、触觉各自独立编码再拼接，丢失接触演化的时序耦合信息。",
          method: "多模态统一序列建模，让视觉 token 与触觉 token 在同一时序骨干中交互对齐，再服务操作策略。",
          contribution: "统一序列表征在接触密集操作上优于独立编码融合，成为视触一体的参考实现。" },
        { id: "tacforcing", name: "TacForcing", title: "TacForcing: Streaming Action Generation with Execution-Time Tactile Feedback", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.25798",
          summary: "让动作块生成在执行中随触觉流实时修正，打破开环动作块范式。",
          purpose: "动作块（action chunk）预测后开环执行，接触状态在块内演化时策略无法反应。",
          method: "以触觉流为条件的流式动作生成，执行时按实时触觉反馈逐步矫正剩余动作。",
          contribution: "在滑移、重抓等接触突变任务上显著提升成功率，确立「触觉闭环动作块」新范式。" },
        { id: "vistanew", name: "VISTA", title: "VISTA: Visually Inferred Spatial ConTact Attention for Contact-Rich Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.25872",
          summary: "从视觉推断空间接触注意力，为接触密集操作提供精细交互反馈。",
          purpose: "外视角视觉对接触状态的观察间接且含糊（尤其遮挡下），需要显式的接触位置监督信号。",
          method: "学习视觉到空间接触注意图的映射，作为策略的辅助监督/条件注入模仿学习管线。",
          contribution: "不增加触觉硬件即可显著改善接触密集任务，是「视觉推接触」路线的代表。" },
        { id: "blinddexterity", name: "Blind Dexterity", title: "Blind Dexterity: Whole-Body Humanoid Manipulation via Pure Proprioception", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29487",
          summary: "反直觉发现：不用相机只用本体感觉，人形也能学会全身灵巧操作。",
          purpose: "检验本体感觉信号对灵巧操作的实际上限，回应「视觉不可或缺」的默认假设。",
          method: "在 Unitree G1 上仅用本体感觉训练全身操作技能（无相机、标记、力矩与触觉传感）。",
          contribution: "纯本体感觉策略即可完成高难度全身操作，为传感器最小化设计提供强证据。" },
        { id: "missingtouch", name: "The Missing Touch", title: "The Missing Touch: Spatially Distributed Tactile Feedback Brings Teleoperation Closer to Human Dexterity", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.19372",
          summary: "给遥操作者的手套加上分布式触觉反馈，演示数据质量大幅提升。",
          purpose: "遥操作采集演示时操作者摸不到物体，示教质量天然低于人手直接操作。",
          method: "空间分布式触觉反馈设备让操作者「远程感受」机器手的接触，再采集其操控轨迹训练策略。",
          contribution: "触觉反馈遥操显著提升演示质量与下游策略成功率，把触觉从「机器人的感官」扩展为「人的接口」。" },
        { id: "softvtbench", name: "SoftVTBench", title: "SoftVTBench: A Deformation-Aware Visuo-Tactile Dataset and Benchmark for Deformable-Object Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.18701",
          summary: "首个面向可变形物体操作的形变感知视触基准。",
          purpose: "现有基准只看任务成败，忽视滑移、过度挤压等物理交互质量。",
          method: "带形变标注的视触数据集 + 交互质量指标（滑移、压缩度）联合评测协议。",
          contribution: "把「操作得好不好」从成败二元扩展到物理质量维度，填补柔性操作评测空白。" },
        { id: "spectratac", name: "SpectraTac", title: "SpectraTac: A Compact Camera-Free Optical Tactile Sensor with Distributed Color Sensing", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.30368",
          summary: "无相机、分布式彩色感知的紧凑低成本触觉传感器。",
          purpose: "视触觉传感器依赖相机与凝胶，体积大、成本高、算力开销大。",
          method: "分布式彩色光学感知替代成像方案，硬件紧凑且计算开销低。",
          contribution: "为触觉大规模部署（含指尖阵列）提供更便宜可行的硬件路径。" },
        {"id": "anytouch2", "name": "AnyTouch 2", "title": "AnyTouch 2: General Optical Tactile Representation Learning for Dynamic Tactile Perception", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.09617", "summary": "分层触觉数据 ToucHD + 跨光学传感器通用触觉表征。", "purpose": "触觉表征需覆盖动态感知（力、滑移）并跨传感器泛化。", "method": "构建触觉原子动作、真实操作与触-力配对的分层数据集，学通用光学触觉表征。", "contribution": "ICLR 2026 触觉表征代表，接 Sparsh/UniTouch 谱系。"},
        {"id": "seeingtouch", "name": "Seeing Through Touch", "title": "Seeing Through Touch: Tactile-Driven Visual Localization of Material Regions", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2604.11579", "summary": "摸一下就知道在哪儿：触觉驱动的材质区域视觉定位。", "purpose": "触觉与视觉的对应多为全局对齐，局部对应未解决。", "method": "学习局部视觉-触觉对应，由触觉输入定位图像中同材质区域，配高多样性数据集。", "contribution": "CVPR 2026 触-视局部对应新任务定义。"},
        {"id": "dotsim", "name": "DOT-Sim", "title": "DOT-Sim: Differentiable Optical Tactile Simulation with Precise Real-to-Sim Physical Calibration", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2604.27367", "summary": "可微分光学触觉仿真 + 精确 real-to-sim 物理校准。", "purpose": "视触觉仿真与真实传感器物理失配，sim-to-real 困难。", "method": "软体弹性建模 + 光学性质精确捕获的可微分触觉仿真。", "contribution": "ICRA 2026 触觉仿真基建，触觉版「Isaac Gym」的雏形。"},
        {"id": "vitacman", "name": "Vi-TacMan", "title": "Vi-TacMan: Articulated Object Manipulation via Vision and Touch", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2510.06339", "summary": "视觉推断铰接运动学 + 触觉局部精修的铰接物体操作。", "purpose": "纯视觉估计铰接不精、纯触觉需要精确初始化。", "method": "视觉全局引导与触觉接触反馈分层融合的操作框架。", "contribution": "ICRA 2026 视触协同操作代表。"},
        {"id": "tactic", "name": "TACTIC", "title": "TACTIC: Tactile and Vision Conditioned Contact-Centric Control for Whole-Arm Manipulation", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2607.09218", "summary": "全臂接触式操作：触觉+视觉条件的接触中心控制。", "purpose": "操作不只靠手爪，手臂本体的接触也可主动利用。", "method": "以接触为中心的控制范式，触觉与视觉双条件覆盖全臂表面。", "contribution": "RSS 2026 全臂操作新范式，接触利用率的重新定义。"},
        {"id": "semcontact", "name": "Semantic-Contact Fields", "title": "Semantic-Contact Fields for Category-Level Generalizable Tactile Tool Manipulation", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.13833", "summary": "语义接触场：类别级泛化的触觉工具操作。", "purpose": "工具操作需知「功能部位在哪、怎么接触」，类别级泛化难。", "method": "学习语义-接触联合场表示，指导同类未见工具的触觉操作。", "contribution": "RSS 2026 工具 affordance × 触觉交汇代表。"},
        { id: "tacpac", name: "TacPAC", title: "TacPAC: Tactile Prediction and Real-Time Action Correction in World-Action Models for Contact-Rich Manipulation", year: 2026, venue: "arXiv 2026.09 (上交等)", status: "预印本", url: "https://arxiv.org/abs/2609.05266",
          summary: "把触觉预测改造成对 WAM 动作的实时纠错：接触密集操作的新范式。",
          purpose: "WAM 的未来预测以视觉为中心，看不到决定接触操作成败的局部触觉线索；直接把未来触觉当额外视角预测只能拿回约三分之一收益。",
          method: "缓存基座模型规划动作块时依赖的预测接触与规划自身表征，触觉专家对照缓存读取新触觉图像，实时修正尚未执行的动作。",
          contribution: "指出「预测先于执行、触觉却在执行中到达」的时序错配并给出修正机制，WAM × 触觉交叉方向的代表作。" }
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "worldmodel", type: "loop", order: 2, icon: "🌍", color: "#7a5cd6",
  name: "世界模型 (WM/WAM)",
  tagline: "从预测世界的模拟器到「既预测世界又输出动作」的世界-动作模型，具身智能的想象力底座。",
  difficulties: [
    {
      id: "wm_video", name: "视频生成式世界模型",
      question: "视频生成模型能否成为通用的世界模拟器？物理一致性还差多远？",
      papers: [
        { id: "sora", name: "Sora", title: "Video Generation Models as World Simulators", year: 2024, venue: "OpenAI 技术报告", status: "技术报告", url: "https://openai.com/research/video-generation-models-as-world-simulators",
          summary: "大规模视频扩散 Transformer，提出「视频生成即世界模拟」的纲领。",
          purpose: "检验规模化视频生成能否涌现 3D 一致性、物体恒存等世界模拟能力。",
          method: "时空 patch 化的扩散 Transformer 在海量可变分辨率视频上训练，支持分钟级生成。",
          contribution: "把「世界模拟器」推为行业叙事，同时暴露物理交互失真等核心短板，划定后续研究议程。" },
        { id: "gaia1", name: "GAIA-1", title: "GAIA-1: A Generative World Model for Autonomous Driving", year: 2023, venue: "arXiv 2023 (Wayve)", status: "预印本", url: "https://arxiv.org/abs/2309.17080",
          summary: "自动驾驶生成式世界模型，视频/文本/动作条件生成逼真驾驶场景。",
          purpose: "驾驶系统需要能预测「如果我这样开会发生什么」的可控场景生成器。",
          method: "把世界建模转成序列建模：图像 token 化 + 自回归世界模型 + 视频扩散解码器，支持动作与文本控制。",
          contribution: "证明世界模型可涌现几何、交互规则等结构，成为驾驶世界模型（GAIA-2、Vista 等）的开端。" },
        { id: "vista", name: "Vista", title: "Vista: A Generalizable Driving World Model with High Fidelity and Versatile Controllability", year: 2024, venue: "NeurIPS 2024 (Wayve)", status: "已发表", url: "https://arxiv.org/abs/2405.17398",
          summary: "高分辨率、可多形式控制、可当奖励函数用的开源驾驶世界模型。",
          purpose: "已有驾驶世界模型分辨率低、泛化差、控制形式单一且闭源。",
          method: "大规模驾驶视频训练视频扩散模型，引入运动学动作接口与损失强化动态/结构学习，支持零样本跨场景泛化。",
          contribution: "开源高保真驾驶世界模型标杆，且可无真值评估候选动作（世界模型当评委）。" },
        { id: "gaia2", name: "GAIA-2", title: "GAIA-2: A Controllable Multi-View Generative World Model for Autonomous Driving", year: 2025, venue: "arXiv 2025 (Wayve)", status: "预印本", url: "https://arxiv.org/abs/2503.20523",
          summary: "多相机一致、细粒度可控（自车/他车/天气/长尾事件）的驾驶世界模型。",
          purpose: "驾驶验证需要可精确编排的多视角合成数据，尤其是安全关键长尾场景。",
          method: "潜空间扩散世界模型，条件涵盖自车动作、他车布局、道路结构与环境因素，多视角联合生成。",
          contribution: "把世界模型推向「可编排的合成数据工厂」，服务训练与安全评估闭环。" },
        { id: "cosmos", name: "Cosmos", title: "Cosmos World Foundation Model Platform for Physical AI", year: 2025, venue: "arXiv 2025 (NVIDIA)", status: "技术报告", url: "https://arxiv.org/abs/2501.03575",
          summary: "面向物理 AI 的开源世界基础模型平台（扩散 + 自回归双路线）。",
          purpose: "机器人/驾驶开发者缺少可微调的通用世界模型底座与配套工具链。",
          method: "2000 万小时视频清洗管线 + 视频 tokenizer + 预训练世界基础模型，支持后训练成下游专用世界模型。",
          contribution: "以开放权重把世界模型「平台化」，成为物理 AI 领域被广泛微调的底座。" },
        { id: "wham", name: "WHAM / Muse", title: "World and Human Action Models towards Gameplay Ideation (WHAM)", year: 2025, venue: "Nature 2025 (Microsoft)", status: "已发表", url: "https://www.nature.com/articles/s41586-025-08600-3",
          summary: "在真实 3A 游戏数据上训练的世界-人类行为联合模型，登上 Nature。",
          purpose: "检验世界模型能否既一致又多样地生成可玩序列，辅助游戏创意迭代。",
          method: "50 万+ 小时人类对局训练自回归世界+动作模型，评估一致性、多样性与可持续编辑性。",
          contribution: "证明世界+动作联合建模可支撑创作工作流，是 WAM（世界-动作模型）路线的标志性成果。" }
      ]
    },
    {
      id: "wm_latent", name: "潜空间动力学与基于模型的 RL",
      question: "在紧凑潜空间里学动力学并「在想象中训练策略」，上限在哪？",
      papers: [
        { id: "dreamerv3", name: "DreamerV3", title: "Mastering Diverse Domains through World Models (DreamerV3)", year: 2023, venue: "Nature 2025 / arXiv 2023", status: "已发表", url: "https://arxiv.org/abs/2301.04104",
          summary: "单套超参横扫 150+ 任务的世界模型 RL，零人类数据挖到 Minecraft 钻石。",
          purpose: "让基于世界模型的 RL 摆脱逐域调参，成为开箱即用的通用算法。",
          method: "RSSM 潜空间世界模型 + 想象轨迹上训练 actor-critic，symlog 归一化等技巧保证跨域稳定。",
          contribution: "确立潜空间世界模型作为通用 RL 骨干的地位，是 WM→决策路线的里程碑。" },
        { id: "tdmpc2", name: "TD-MPC2", title: "TD-MPC2: Scalable, Robust World Models for Continuous Control", year: 2024, venue: "ICLR 2024", status: "已发表", url: "https://arxiv.org/abs/2310.16828",
          summary: "隐式（无解码器）世界模型 + MPC，单模型多任务连续控制可扩展。",
          purpose: "解决基于模型的连续控制在任务规模与稳健性上的瓶颈。",
          method: "学习面向控制的隐式潜动力学，在潜空间做模型预测控制，单套超参训练 317M 参数多任务智能体。",
          contribution: "104 个任务单模型可用，展示「面向决策的世界模型」随参数与数据的可扩展性。" },
        { id: "iris", name: "IRIS", title: "Transformers are Sample-Efficient World Models (IRIS)", year: 2023, venue: "ICLR 2023 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2209.00588",
          summary: "离散 token + Transformer 世界模型，2 小时游戏经验达到超人 Atari 表现。",
          purpose: "验证「LLM 式序列建模」能否成为样本高效世界模型的通用配方。",
          method: "VQ 自编码器离散化观测，自回归 Transformer 学动力学，策略完全在想象中训练。",
          contribution: "把世界模型带入 token 序列建模时代，为 Genie 等生成式交互环境铺路。" },
        { id: "storm", name: "STORM", title: "STORM: Efficient Stochastic Transformer based World Models for Reinforcement Learning", year: 2023, venue: "NeurIPS 2023", status: "已发表", url: "https://arxiv.org/abs/2310.09615",
          summary: "随机 Transformer 世界模型，在效率与性能上刷新 Atari-100k。",
          purpose: "兼顾 Transformer 世界模型的表达力与训练效率。",
          method: "变分随机潜变量 + Transformer 序列模型联合建模不确定性动力学，想象中训练策略。",
          contribution: "以更低训练成本取得当时无查找 MBRL 最优，成为轻量 Transformer WM 的常用基线。" },
        {"id": "eighttokens", "name": "Planning in 8 Tokens", "title": "Planning in 8 Tokens: A Compact Discrete Tokenizer for Latent World Model", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2603.05438", "summary": "每帧压到 8 个 token：潜世界模型里的规划提速一个数量级。", "purpose": "潜世界模型规划仍嫌慢，token 冗余是主要瓶颈。", "method": "紧凑离散 tokenizer 将每帧观测压至约 8 token，动作条件潜模型内做近实时规划。", "contribution": "CVPR 2026 世界模型效率代表作，「token 经济学」视角。"},
        {"id": "geoworld", "name": "GeoWorld", "title": "GeoWorld: Geometric World Models", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.23058", "summary": "几何结构化潜空间：治能量式世界模型的欧氏漂移病。", "purpose": "欧氏潜空间忽略状态间几何/层次结构，多步预测漂移。", "method": "在能量预测式世界模型中引入几何结构化潜空间。", "contribution": "CVPR 2026 几何世界模型代表，与 GeoWAM/4DGS-WAM 空间化支线呼应。"},
        { id: "pointzero", name: "PointZero", title: "PointZero: 3D Point Track Completion for Learning Transferable 3D Dynamics", year: 2026, venue: "arXiv 2026.09 (NVIDIA等)", status: "预印本", url: "https://arxiv.org/abs/2609.19142",
          summary: "3D 点轨迹补全作为预训练目标：无需机器人动作标签学会可迁移的 3D 动力学。",
          purpose: "动作条件 3D 动力学模型需要机器人动作标注，把海量网络视频排除在训练池之外。",
          method: "给定单帧 RGB-D 与稀疏部分 3D 轨迹，预测所有观测点的未来 3D 轨迹；构建 290 万帧合成数据集（变形/铰接/刚体）从零训练。",
          contribution: "证明自监督点轨迹补全即可产生丰富 3D 动力学先验并迁移下游，与 ModAR「点轨迹优于 RGB」的发现互相印证。" },
        { id: "worldcontact", name: "WorldContact", title: "WorldContact: A Contact-Centric World Model for Scalable Robot Learning", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.19600",
          summary: "接触中心的世界模型：从少量轨迹学会物体动力学，10 倍速生成训练数据。",
          purpose: "机器人适配新物体/任务需要交互经验，真机采集昂贵；数值仿真小步长积分太慢。",
          method: "以接触为中心建模可变形物体（购物袋等）动力学，用远大于源仿真器的时间步做状态推演，单张 H100 上比源仿真快 10 倍；生成数据直接微调 VLA 并真机部署。",
          contribution: "「世界模型即数据工厂」的落地样本：16 个购物袋任务验证生成数据可用性。" }
      ]
    },
    {
      id: "wm_jepa", name: "表征预测式世界模型 (JEPA)",
      question: "不生成像素、只预测表征的世界模型，是否更适合理解与控制？",
      papers: [
        { id: "vjepa", name: "V-JEPA", title: "Revisiting Feature Prediction for Learning Visual Representations from Video (V-JEPA)", year: 2024, venue: "TMLR 2024 (Meta FAIR)", status: "已发表", url: "https://arxiv.org/abs/2404.08471",
          summary: "纯特征预测（不重建像素）的视频自监督预训练，验证 JEPA 假说。",
          purpose: "检验 LeCun 的联合嵌入预测架构：预测抽象表征而非像素能否学到更好的世界理解。",
          method: "掩码视频区域，在潜空间预测其表征，无像素重建、无文本监督，200 万视频训练。",
          contribution: "冻结骨干即在动作理解任务上表现强劲，确立表征预测式世界模型路线。" },
        { id: "vjepa2", name: "V-JEPA 2", title: "V-JEPA 2: Self-Supervised Video Models Enable Understanding, Prediction and Planning", year: 2025, venue: "arXiv 2025 (Meta FAIR)", status: "预印本", url: "https://arxiv.org/abs/2506.09985",
          summary: "百万小时视频预训练 + 少量机器人数据后训练，零样本迁移到真机规划。",
          purpose: "打通「互联网视频学世界知识 → 机器人零样本规划」的完整链路。",
          method: "V-JEPA 扩到 1M 小时/1B 参数；用 62 小时无标注机器人视频后训练动作条件世界模型 V-JEPA 2-AC，部署时在表征空间做模型预测控制。",
          contribution: "新环境零样本完成抓放操作，证明表征世界模型可以直接驱动真机规划。" },
        { id: "dinowm", name: "DINO-WM", title: "DINO-WM: World Models on Pre-trained Visual Features Enable Zero-Shot Planning", year: 2024, venue: "arXiv 2024 / ICML 2025", status: "已发表", url: "https://arxiv.org/abs/2411.04983",
          summary: "直接在冻结 DINOv2 特征上学动力学，任务无关且可零样本规划。",
          purpose: "世界模型通常绑定任务与奖励，希望得到「离线训练、任意目标即插即用」的世界模型。",
          method: "冻结视觉基础模型特征作为状态，学习动作条件的特征转移模型，测试时以目标图像做推演优化。",
          contribution: "无需专家示教或奖励即可零样本达成新目标，展示「视觉基础模型 + 轻量动力学」的高性价比配方。" },
        { id: "physjeap", name: "Physically-Grounded JEPA", title: "Toward Physically Grounded JEPA World Models for Goal-Conditioned Robotic Planning", year: 2026, venue: "IROS 2026 Workshop (PWMS)", status: "已发表", url: "https://arxiv.org/abs/2609.03565",
          summary: "给 JEPA 世界模型补上物理落地：潜空间预测也要保留物理量。",
          purpose: "动作条件 JEPA 能面向视觉目标规划，但纯潜预测不保证表征保留物理属性。",
          method: "在 JEPA 训练目标中注入物理接地约束，使潜空间显式携带物理相关信息。",
          contribution: "修正 JEPA 路线「重预测、轻物理」的缺陷，V-JEPA 系 2026 的重要补强。" },
        { id: "ivideogpt", name: "iVideoGPT", title: "iVideoGPT: Interactive VideoGPTs are Scalable World Models", year: 2024, venue: "NeurIPS 2024", status: "已发表", url: null,
          summary: "把交互性（动作、奖励）纳入可扩展视频 GPT，服务基于模型的 RL。",
          purpose: "视频生成世界模型多为被动预测，交互式训练所需的动作条件与奖励预测缺失。",
          method: "压缩 tokenizer 处理视觉观测，自回归 Transformer 统一建模观测-动作-奖励序列，先大规模预训练再适配控制。",
          contribution: "在视觉 MBRL 基准上与 Dreamer 系竞争，验证「视频 GPT 作为交互世界模型」的可扩展性。" },
        { id: "wallss", name: "WALL-SS", title: "WALL-SS: Scaling Long-horizon World Models via Next-Scale Autoregression", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.26239",
          summary: "用「逐尺度自回归」突破世界模型的长时程墙：小时级一致想象。",
          purpose: "生成式世界模型在长时程任务（仿真、策略评估、机器人学习）中受限于预测一致性随时间崩塌。",
          method: "下一尺度自回归（next-scale autoregression）建模多尺度时空表征，逐层由粗到细预测未来。",
          contribution: "把世界模型的可信预测时长推到新量级，2026 长时程世界模型的代表突破。" },
        { id: "anyworld", name: "AnyWorld", title: "AnyWorld: Factorized Egocentric World Models for Cross-Embodiment Generalization", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.29242",
          summary: "因子化的第一视角世界模型：拆解本体/视角/场景以泛化到新机器人。",
          purpose: "接触丰富的机器人经验难以规模化采集，跨本体复用是世界模型的关键出路。",
          method: "把第一视角动态因子化（本体、视角、场景解耦），在新本体上重组复用世界知识。",
          contribution: "世界模型层面的跨具身泛化方案，与 AnyGrasp 式「AnyX」命名一脉相承。" }
      ]
    },
    {
      id: "wm_interactive", name: "交互式生成环境",
      question: "能否直接「生成」一个可实时游玩/交互的虚拟世界？",
      papers: [
        { id: "genie", name: "Genie", title: "Genie: Generative Interactive Environments", year: 2024, venue: "ICML 2024 (Best Paper)", status: "已发表", url: "https://arxiv.org/abs/2402.15391",
          summary: "从无标注网络视频学出「可玩」的生成式交互环境，动作空间无监督涌现。",
          purpose: "无需动作标注，能否从纯视频学到可被逐帧控制的基础世界模型？",
          method: "时空 Transformer + 无监督潜动作模型 + 视频 tokenizer，11B 参数在 20 万小时游戏视频上训练。",
          contribution: "开创「生成式交互环境」类别，潜动作机制成为 LAPA 等机器人潜动作路线的源头。" },
        { id: "genie2", name: "Genie 2", title: "Genie 2: A Large-Scale Foundation World Model", year: 2024, venue: "DeepMind 博客 (DeepMind)", status: "技术报告", url: "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
          summary: "单张图生成可键鼠交互的 3D 世界，物体恒存与物理效果涌现。",
          purpose: "为通用智能体提供无限多样的可交互训练环境。",
          method: "大规模视频训练的潜扩散世界模型，支持长达分钟级的动作条件 3D 世界模拟。",
          contribution: "展示「世界模型即训练场」的可行性，被用于 SIMA 等智能体的评测与训练。" },
        { id: "genie3", name: "Genie 3", title: "Genie 3: A New Frontier for World Models", year: 2025, venue: "DeepMind 博客 (DeepMind)", status: "技术报告", url: "https://deepmind.google/discover/blog/genie-3-a-new-frontier-for-world-models/",
          summary: "720p/24fps 实时交互、数分钟视觉记忆、可提示世界事件的世界模型。",
          purpose: "把生成式世界推进到实时、持久、可编导的水平，服务智能体训练与评估。",
          method: "（未公开细节）自回归实时世界生成，支持文本提示动态改变世界事件，保持多分钟环境一致性。",
          contribution: "实时性+持久性+可提示性的组合树立世界模型新标杆，明确指向具身智能体训练用途。" },
        { id: "unisim", name: "UniSim", title: "Learning Interactive Real-World Simulators (UniSim)", year: 2024, venue: "ICLR 2024 (Outstanding Paper)", status: "已发表", url: "https://arxiv.org/abs/2310.06114",
          summary: "聚合异构数据学「真实世界模拟器」，反哺策略与 VLM 训练后零样本上真机。",
          purpose: "真实交互数据昂贵，能否学一个统一模拟器让智能体在其中「做中学」？",
          method: "视频扩散模型统一吸收机器人、人类活动、导航等异构数据，条件于语言/动作生成下一步观测。",
          contribution: "纯模拟器内训练的策略可零样本迁移真实机器人，论证「生成式模拟器闭环」的可行性。" },
        { id: "oasis", name: "Oasis", title: "Oasis: A Universe in a Transformer", year: 2024, venue: "Decart / Etched 技术报告 (Decart)", status: "技术报告", url: null,
          summary: "首个实时（20fps）开放可玩的生成式 Minecraft 世界模型。",
          purpose: "验证端到端 Transformer 世界模型能否达到可公开游玩的实时交互水准。",
          method: "自回归扩散混合架构逐帧生成，键鼠输入条件化，针对推理芯片深度优化。",
          contribution: "把「AI 生成的可玩世界」第一次交到公众手里，凸显实时世界模型的工程可行性与漂移问题。" },
        { id: "clap", name: "CLAP", title: "CLAP: Cross-Embodiment Video World Models are Zero-Shot Physical Simulators", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.27406",
          summary: "跨本体视频世界模型 = 零样本物理模拟器：吃异构视频，仿真任意机器人。",
          purpose: "动作条件视频模型通常绑定单一机器人本体，浪费了海量异构视频中的物理信号。",
          method: "在多本体异构数据上训练动作条件视频世界模型，零样本迁移到未见机器人形态做物理仿真。",
          contribution: "「世界模型即通用模拟器」的直接证据， UniSim 路线在 2026 的完全体。" },
        {"id": "astra", "name": "Astra", "title": "Astra: General Interactive World Model with Autoregressive Denoising", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2512.08931", "summary": "自回归去噪 + 动作专家混合的通用交互式世界模型。", "purpose": "交互式世界模型需兼顾长时程预测与多动作模态对齐。", "method": "自回归去噪架构、时序因果注意力与动作专家混合，统一多机器人动作模态。", "contribution": "ICLR 2026 交互世界模型代表，接 Genie/UniSim 谱系。"}
      ]
    },
    {
      id: "wm_policy", name: "世界模型驱动的机器人决策",
      question: "如何把世界模型的预测/想象能力变成真实机器人的策略与规划？",
      papers: [
        { id: "unipi", name: "UniPi", title: "Learning Universal Policies via Text-Guided Video Generation (UniPi)", year: 2023, venue: "NeurIPS 2023 (Spotlight)", status: "已发表", url: "https://arxiv.org/abs/2302.00111",
          summary: "把决策问题转成「文本条件视频生成 + 逆动力学提取动作」。",
          purpose: "利用互联网规模视频知识做跨环境通用策略，绕开动作标注瓶颈。",
          method: "文本条件视频扩散模型生成未来执行画面（视频即计划），再用逆动力学模型从相邻帧解码动作。",
          contribution: "确立「video-as-policy」范式，组合泛化与多任务迁移显著，启发 SuSIE、GR 系列等后续。" },
        { id: "susie", name: "SuSIE", title: "Zero-Shot Robotic Manipulation with Pretrained Image-Editing Diffusion Models (SuSIE)", year: 2024, venue: "ICLR 2024", status: "已发表", url: "https://arxiv.org/abs/2310.10639",
          summary: "用图像编辑扩散模型生成子目标图，低层策略只管「够得着的」目标。",
          purpose: "让互联网预训练的图像模型承担语义推理，缓解语言条件策略的泛化瓶颈。",
          method: "InstructPix2Pix 式模型按指令生成未来子目标图像，目标条件低层策略逐段执行。",
          contribution: "在 CALVIN 与真机上零样本泛化到新物体/场景，展示「生成子目标 + 短视策略」分工的威力。" },
        { id: "nwm", name: "NWM", title: "Navigation World Models", year: 2025, venue: "CVPR 2025 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2412.03572",
          summary: "可控视频生成世界模型直接用于导航轨迹的想象与打分。",
          purpose: "让导航智能体获得「先在脑内走一遍」的规划能力，并能利用无动作视频数据。",
          method: "条件扩散 Transformer（1B 参数）在第一视角视频上学动作条件预测，规划时生成候选轨迹并评估目标达成。",
          contribution: "已知环境可凭想象规划、未知环境可想象探索，把视频世界模型落到导航决策上。" },
        { id: "worldvla", name: "WorldVLA", title: "WorldVLA: Towards Autoregressive Action World Model", year: 2025, venue: "arXiv 2025 (上海AI Lab)", status: "预印本", url: "https://arxiv.org/abs/2506.21539",
          summary: "把 VLA 与世界模型统一进单个自回归框架，动作与图像互相增益。",
          purpose: "VLA 只学「怎么做」、世界模型只学「会怎样」，二者割裂浪费互补信息。",
          method: "统一 token 空间联合训练动作生成与动作条件图像预测，注意力掩码策略缓解动作块自回归误差累积。",
          contribution: "动作与世界预测互相提升，是「世界-动作模型（WAM）一体化」趋势的直接代表。" },
        { id: "genie_envisioner", name: "Genie Envisioner", title: "Genie Envisioner: A Unified World Foundation Platform for Robotic Manipulation", year: 2025, venue: "arXiv 2025 (AgiBot)", status: "预印本", url: null,
          summary: "操作专用的视频世界模型平台：预测、策略、评测一体。",
          purpose: "把「视频生成世界模型」产品化为操作研发的统一底座。",
          method: "大规模操作视频训练视频世界模型（想象引擎），衍生动作头做闭环控制，并附世界模型评测套件。",
          contribution: "提供世界模型驱动操作的端到端参考实现与评测基准，推动 WM→VLA 融合落地。" },
        { id: "wise26", name: "WISE", title: "WISE: World-model-guided Imagination Scheduling for Efficient Post-training of Vision-Language-Action Models", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03681",
          summary: "世界模型当「训练场调度器」：在想象中安排 VLA 后训练，省真机数据与探索。",
          purpose: "VLA 后训练要么烧专家演示（SFT）要么冒险真机探索（RL），两头都贵。",
          method: "用世界模型引导的想象调度生成受控训练经验，在想象中高效后训练 VLA 策略。",
          contribution: "WM×VLA 融合的 2026 代表作：世界模型从「评测器/造数据」升级为「后训练调度器」。" },
        { id: "motus2", name: "Motus2", title: "Motus2: A Self-Evolving General World Model for Dexterous Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.30237",
          summary: "感知-预测-行动-评估-改进一体化的自进化灵巧操作世界模型。",
          purpose: "通用具身智能体应在一个系统内闭环自我改进，现有世界模型只外挂动作头。",
          method: "统一框架内联合世界预测、动作生成与自我评估，形成自进化循环。",
          contribution: "「自进化世界模型」概念的落地样本，指向世界模型与终身学习的合流。" },
        { id: "worldgymnast", name: "World-Gymnast", title: "World-Gymnast: Training Robots with Reinforcement Learning in a World Model", year: 2026, venue: "arXiv 2026.02", status: "预印本", url: "https://arxiv.org/abs/2602.02454",
          summary: "在世界模型里做 RL：物理交互成本被「想象中的试错」替代。",
          purpose: "机器人 RL 被物理交互成本卡死；SFT 受演示分布限制，真机 RL 又贵又慢。",
          method: "在学习到的世界模型内进行强化学习训练，策略再迁移回真机。",
          contribution: "「WM 内 RL」的系统性配方，延续 Dreamer 思想并对接现代视频世界模型。" },
        { id: "weaver", name: "WEAVER", title: "WEAVER, Better, Faster, Longer: An Effective World Model for Robotic Manipulation", year: 2026, venue: "arXiv 2026.06", status: "预印本", url: "https://arxiv.org/abs/2606.13672",
          summary: "更好更快更长：一个世界模型同时服务策略评估、策略改进与测试时规划。",
          purpose: "学习型模拟器（WM）对机器人潜力巨大，但现有模型在操作任务上精度/速度/时程不足。",
          method: "针对操作优化的世界模型设计，兼顾 rollout 保真度、推理速度与长时程一致性。",
          contribution: "把 WM 的三大用途（评估/改进/规划）统一到一个高效实现，操作 WM 的基准之作。" },
        { id: "tau0wm", name: "τ₀-WM", title: "τ₀-WM: A Unified Video-Action World Model for Robotic Manipulation", year: 2026, venue: "arXiv 2026.05 (清华等)", status: "预印本", url: "https://arxiv.org/abs/2606.01027",
          summary: "统一视频-动作世界模型：生成可执行动作，也在执行前预估后果。",
          purpose: "操作模型需要既出动作、又能在物理执行前预测与评估动作的未来后果。",
          method: "统一 video-action 架构联合训练动作生成与未来预测，支撑执行前评估。",
          contribution: "τ 系基础模型的世界模型半壁，与 τ₀-VLA 配套构成 2026 分层+测试时计算全家桶。" },
        { id: "cosmospolicy", name: "Cosmos Policy", title: "Cosmos Policy: Fine-Tuning Video Models for Visuomotor Control and Planning", year: 2026, venue: "arXiv 2026.01 (NVIDIA)", status: "预印本", url: "https://arxiv.org/abs/2601.16163",
          summary: "把 Cosmos 视频基础模型微调成视觉运动控制器与规划器。",
          purpose: "视频生成模型蕴含丰富时空物理先验，但如何转成控制能力缺少配方。",
          method: "系统研究视频模型的控制微调配方，产出 visuomotor 控制与规划两种能力。",
          contribution: "「视频 FM → 控制」官方配方，Cosmos 生态在机器人侧的落地代表。" },
        {"id": "dust", "name": "DUST", "title": "DUST: Dual-Stream Diffusion for World-Model Augmented Vision-Language-Action Model", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2510.27607", "summary": "双流扩散统一世界模型与 VLA：真机成功率 +10%。", "purpose": "世界模型与 VLA 联训时多模态目标互相干扰。", "method": "双流独立噪声扰动 + 解耦流匹配损失的世界模型增强 VLA。", "contribution": "ICML 2026 WM×VLA 融合代表作（接 WorldVLA/PAVE 一线）。"},
        {"id": "mola", "name": "MoLA", "title": "From Imagined Futures to Executable Actions: Mixture of Latent Actions for Robot Manipulation", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2605.12167", "summary": "想象未来 → 混合潜动作 → 可执行动作的三段式管线。", "purpose": "生成模型想象的未来视频如何可靠转成动作？", "method": "语义/深度/光流三路潜动作的混合逆动力学模型解码想象未来。", "contribution": "LIBERO/CALVIN 与真机时序一致性提升，ICML 2026 想象-执行桥梁。"},
        {"id": "westworld", "name": "WestWorld", "title": "WestWorld: A Knowledge-Encoded Scalable Trajectory World Model for Diverse Robotic Systems", "year": 2026, "venue": "ICML 2026 (Spotlight)", "status": "已发表", "url": "https://arxiv.org/abs/2603.14392", "summary": "知识编码的可扩展轨迹世界模型：89 环境预训练直上真机四足。", "purpose": "世界模型跨机器人形态扩展难，形态知识缺失。", "method": "系统感知 MoE + 机器人形态学知识结构嵌入的轨迹世界模型。", "contribution": "ICML 2026 Spotlight，部署真实 Unitree Go1 稳定行走。"},
        {"id": "rise26", "name": "RISE", "title": "RISE: Self-Improving Robot Policy with Compositional World Model", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.11075", "summary": "组合式世界模型驱动的自我改进策略。", "purpose": "策略自我改进需要世界模型提供反事实与评估信号。", "method": "组合式世界模型分解场景动态，支撑策略 rollout 评估与迭代改进。", "contribution": "RSS 2026 自改进路线，与 Motus2 自进化主张呼应。"},
        {"id": "lda1b", "name": "LDA-1B", "title": "Scaling Latent Dynamics Action Model via Universal Embodied Data Ingestion", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.12215", "summary": "万物皆可吃：通用具身数据摄取规模化潜动力学动作模型。", "purpose": "潜动力学动作模型（LaWAM 系）需要更大更杂的数据与形态覆盖。", "method": "统一格式摄取异构具身数据（1B 级）规模化训练潜动力学动作模型。", "contribution": "RSS 2026 潜 WAM 的规模化实证（北大 EPIC），接 AcrossWAM/LaWAM 谱系。"}
      ]
    },
    {
      id: "wm_wam", name: "世界-动作模型 (WAM)",
      question: "2026 年爆发的 WAM 路线：让一个模型同时「想象未来」与「输出动作」，到底该怎么做、边界在哪？",
      papers: [
        { id: "riemann10", name: "Riemann-1.0", title: "Riemann-1.0: An Embodied World Action Model for Physical AI", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.27033",
          summary: "全因果自回归的具身世界-动作模型：多视角视觉、机器人状态与本体动作统一建模。",
          purpose: "把世界预测与动作生成合并进单一因果序列模型，服务物理 AI。",
          method: "多视角观测、机器人状态与本体特定动作 token 化后进入统一自回归流，全因果训练。",
          contribution: "给出 WAM 的统一自回归参考实现，被视为该路线的基座型工作之一。" },
        { id: "zimablue", name: "ZimaBlue", title: "ZimaBlue: Evolving Generalizable World Action Models through Scalable Video Pre-training", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2609.00188",
          summary: "用海量第一视角视频预训练并持续进化的可泛化世界-动作模型。",
          purpose: "动作标注轨迹昂贵且多样性不足，WAM 的泛化需要更可扩展的数据源。",
          method: "大规模第一视角视频预训练 + 可进化的 WAM 训练框架，让模型在部署中持续吸收新经验。",
          contribution: "证明视频规模预训练可以直接养成泛化 WAM，是「视频→WAM」路线的代表。" },
        { id: "delew05", name: "DELE-w0.5", title: "DELE-w0.5: Inferring Action from Future Latent State for Robotic Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.22067",
          summary: "质疑视频生成中间产物：直接从「未来潜状态」推断动作，跳过逐帧生成。",
          purpose: "现有 WAM 建立在视频生成骨干上， dense 视频轨迹生成是昂贵的中间对象。",
          method: "预测任务相关的未来潜状态，再从潜状态解码动作，无需生成像素级未来。",
          contribution: "对「WAM 必须生成视频」提出根本性反思，大幅降低推理成本。" },
        { id: "hydra_wam", name: "Hydra", title: "Hydra: A Navigation World Action Model with Discrete Latent Planning and Continuous Flow-Matching Execution", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.28995",
          summary: "导航 WAM：离散潜空间做规划、流匹配做连续执行的「双头」设计。",
          purpose: "世界模型的生成表征与规划器所在流形不一致，想象能力难以变现为实时控制。",
          method: "统一 WAM 内并行离散潜规划头与连续流匹配执行头，对齐「想象」与「行动」的表征。",
          contribution: "把 WAM 落到实时导航控制，给出想象-规划-执行一致的架构模板。" },
        { id: "glancewam", name: "GlanceWAM", title: "GlanceWAM: Sparse Test-Time Imagination for World-Action Models", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.23927",
          summary: "测试时「偶尔瞄一眼未来」：稀疏想象破解 WAM 延迟与能力两难。",
          purpose: "按控制频率同步生成视频延迟爆炸，完全放弃想象又损失物理先验。",
          method: "稀疏触发的测试时想象——仅在关键决策点生成未来，平时直接出动作。",
          contribution: "在延迟与想象收益间取得工程最优解，WAM 实时化的代表方案。" },
        { id: "wamopd", name: "WAM-OPD", title: "WAM-OPD: On-Policy Distillation for World Action Models", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.22364",
          summary: "WAM 的在线策略蒸馏：加速版学生不丢任务能力。",
          purpose: "蒸馏出的轻量 WAM 会丢失任务能力，且在训练未覆盖的状态上崩坏。",
          method: "在线策略蒸馏：学生 rollout 遇到的分布外状态回流给教师补课，持续校正。",
          contribution: "解决 WAM 压缩部署的核心痛点，确立「on-policy 蒸馏」为 WAM 标配。" },
        { id: "4dgswam", name: "4DGS-WAM", title: "4DGS-WAM: Bridging Past and Future with an Object-Centric World Action Model based on 4D Gaussian Splatting", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.25956",
          summary: "把 WAM 从 2D 视频搬进 4D 高斯溅射的物体中心显式空间。",
          purpose: "2D 视频空间缺少显式物体级空间结构，重复处理静态区域浪费容量。",
          method: "以 4D 高斯溅射表示场景的过去观测与未来预测，物体中心组织 WAM 的想象与动作。",
          contribution: "WAM 显式几何化的先行者，连接 3D 重建社区与世界模型社区。" },
        { id: "ld4wam", name: "LD4WAM", title: "LD4WAM: Learning Latent Dynamics from Human Videos for World Action Models", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.22403",
          summary: "从人类视频学 WAM 潜动力学，解动作标注数据的渴。",
          purpose: "人类视频多样且便宜，但 WAM 从中学习的方式此前停留在表层。",
          method: "在人类视频上学习任务相关潜动力学并迁移到机器人 WAM，对齐人-机动作语义。",
          contribution: "把「人类视频喂 WAM」做成系统方法，延续 LAPA/UniVLA 的数据哲学。" },
        { id: "worldcoherent", name: "World-Coherent Decoding", title: "World-Coherent Decoding: Self-Verifying Test-Time Planning for World Action Models", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.02159",
          summary: "WAM 采样哪个未来就出什么动作——用自验证解码消除这种随机性。",
          purpose: "WAM 随机生成视觉未来再解码动作，结果强依赖「抽中哪个未来」，不稳定。",
          method: "测试时对候选未来做自一致性/可执行性验证，仅从世界连贯的未来中解码动作。",
          contribution: "把测试时验证引入 WAM，显著稳定策略行为，属「WAM 推理时规模化」新方向。" },
        { id: "spatialwam", name: "Spatially-Aware WAM", title: "Spatially Aware World Action Model via Geometric Latent Diffusion", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.02531",
          summary: "几何潜扩散让 WAM 继承视频先验的同时保有空间结构。",
          purpose: "视频扩散 WAM 继承了互联网视觉先验，却丢掉显式几何与空间感知。",
          method: "在几何结构化的潜空间做扩散式未来预测与动作生成。",
          contribution: "代表 WAM 的「空间化」改良支线，与 4DGS-WAM 呼应。" },
        { id: "hitacwam", name: "HiTac-WAM", title: "HiTac-WAM: A Hierarchical Tactile World Action Model for Contact-Rich Robot Manipulation", year: 2026, venue: "arXiv 2026.08 (上交等)", status: "预印本", url: "https://arxiv.org/abs/2608.19574",
          summary: "触觉 WAM：层次化建模未来接触的物理依赖，而不只是预测触觉图像。",
          purpose: "现有触觉感知 WAM 把未来触觉当图像/潜流预测，忽略接触的物理依赖结构。",
          method: "层次化触觉世界建模（接触事件→力觉演化→动作）联合训练的世界-动作模型。",
          contribution: "首个成体系的触觉 WAM，把 2026 两大热点（触觉×WAM）正式交汇。" },
        { id: "n0twam", name: "N₀-TWAM", title: "N₀-TWAM: Scaling Tactile-Native World-Action Model for Contact-Rich Manipulation", year: 2026, venue: "arXiv 2026.07 (北大等)", status: "预印本", url: "https://arxiv.org/abs/2607.23783",
          summary: "触觉原生的世界-动作模型：同时预测未来视觉与未来接触，规模化训练。",
          purpose: "接触密集操作的关键物理线索（压力、滑移、摩擦）在视觉里几乎不可见。",
          method: "以触觉为一等公民的 WAM 架构与 scaling 配方，联合预测未来视觉流与未来接触流并生成动作。",
          contribution: "首个强调 tactile-native scaling 的 WAM，与 N₀-Foundation 共同构成触觉智能系列的模型侧支柱。" },
        { id: "vtwam", name: "VT-WAM", title: "VT-WAM: Visual-Tactile World Action Model for Contact-Rich Manipulation", year: 2026, venue: "arXiv 2026.07 (中科院自动化所等)", status: "预印本", url: "https://arxiv.org/abs/2607.02503",
          summary: "视触双流世界-动作模型：捕捉形变、压力、滑移等时间稀疏线索。",
          purpose: "接触线索时间上稀疏且视觉不可见，纯视觉 WAM 在精细接触任务上失明。",
          method: "视觉与触觉双流联合的世界-动作建模，让动作生成条件于预测的未来接触状态。",
          contribution: "与 N₀-TWAM、Dream-Tac、HiTac-WAM 共同构成 2026 触觉 WAM 四部曲。" },
        { id: "dreamtac", name: "Dream-Tac", title: "Dream-Tac: A Unified Tactile World Action Model for Contact-Rich Robot Manipulation", year: 2026, venue: "arXiv 2026.06 (清华等)", status: "预印本", url: "https://arxiv.org/abs/2606.08737",
          summary: "统一触觉世界-动作模型：动作生成由「预想到的未来触觉」引导。",
          purpose: "现有 WAM 主要依赖视觉，接触密集任务中触觉前瞻才是成败关键。",
          method: "把触觉预测嵌入 WAM 的想象循环，动作生成显式条件于预期的未来触觉序列。",
          contribution: "「触觉想象」概念的先行实现，证明触觉前瞻可引导动作生成。" },
        { id: "gamewam", name: "GameWAM", title: "GameWAM: A World Action Model for Video Games", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.26200",
          summary: "游戏领域的 WAM：第一视角、快视觉变化、持久状态与异构控制的统一建模。",
          purpose: "游戏智能体直接从上下文映射到动作，缺乏对世界状态演化的显式建模。",
          method: "把 WAM 框架迁移到游戏场景，联合预测画面演化与原生控制输入。",
          contribution: "证明 WAM 范式可泛化到机器人之外的第一视角交互领域。" },
        { id: "decowam", name: "DECOWAM", title: "DECOWAM: Decoupled Whole-Body World-Action Model for Legged Mobile Manipulation", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.20114",
          summary: "腿足移动操作的解耦全身 WAM：运动与操作对未来的影响分开建模。",
          purpose: "现有 WAM 基本面向固定基座，移动操作需要同时预测「走路」与「动手」如何改变未来。",
          method: "解耦式全身世界-动作建模，分离 locomotion 与 manipulation 对观测演化的贡献。",
          contribution: "把 WAM 推向腿足全身移动操作，覆盖更完整的具身形态。" },
        { id: "wamcapability", name: "WAM 能力边界研究", title: "On the Capability Separation Between World-Model Policy Learning and Imitated World-Action Models", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.22197",
          summary: "冷静追问：WAM「先预测未来再出动作」的分解真的比直接策略更强吗？",
          purpose: "WAM 的因子化号称改善表征与数据效率，但控制能力是否真有提升缺乏对照证据。",
          method: "在世界模型策略学习与模仿式 WAM 之间做系统的能力分离对照实验。",
          contribution: "为过热的 WAM 浪潮提供批判性基准，帮助厘清哪些收益来自分解、哪些来自数据。" },
        { id: "svwam", name: "SV-WAM", title: "SV-WAM: An Efficient Surround-View World-Action Model for End-to-End Autonomous Driving", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03602",
          summary: "全车六相机环视 WAM：把未来视频预测从推理输出降级为训练监督，换取可部署效率。",
          purpose: "驾驶 WAM 推理时生成未来视频开销过大，主流做法退回单前视相机，换道/汇入等安全关键场景空间覆盖不足。",
          method: "保留六相机环视输入；未来视频预测仅作为共享生成模型内动作学习的稠密训练监督，配合动作中心因果掩码阻断动作 token 对未来的窥视。",
          contribution: "WAM 在自动驾驶落地的效率代表工作，「预测为训不为推」的设计对机器人侧 WAM 同样有借鉴意义。" },
        { id: "hydra0", name: "Hydra-0", title: "Hydra-0: Action Flow for Generalist World Modeling and Control", year: 2026, venue: "arXiv 2026.08 (NVIDIA)", status: "预印本", url: "https://arxiv.org/abs/2608.18077",
          summary: "NVIDIA 的通才世界模型：把机器人动作表示为「动作流」（像素运动），用视觉接口统一世界建模与控制。",
          purpose: "异构本体/任务/环境的动作数据无法直接共享；若动作与视频共用同一「像素运动」语言，世界模型就能跨数据源学习动作后果。",
          method: "以动作流为条件在视频生成骨干上训练世界模型，支持零样本组合与数据高效适配；逆模式由期望物体流（如人类演示）预测兼容的机器人运动，动作头将潜特征映射为可执行动作，无需任务级专家演示。",
          contribution: "机器人运动误差较动作条件基线降 90.4%、物体运动误差降 60.2%；RoboLab 上重放与真实成功率相关 r=0.96（世界模型即开环评测器）；涌现的逆模式即 WAM——与 Riemann-1.0、ZimaBlue 并列的基座候选路线。" },
        { id: "openwam", name: "OpenWAM", title: "OpenWAM: An Open, Modular Exploration Towards Systematic World-Action Model Pretraining", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.07398",
          summary: "WAM 领域的「OpenRLAB 式」开源研究栈：把 WAM 预训练变成可控实验科学。",
          purpose: "现有 WAM 系统全是铁板一块——生成骨干/视觉表征/架构/信息流/推理过程/数据紧耦合，说不清哪些设计真正起作用。",
          method: "OpenWAM-Infra 把 WAM 设计空间因子化为可组合模块（统一训练/推理/部署/评测），OpenWAM-Study 在其上做对照实验：该继承什么、世界与动作学习如何交互、协同如何随规模变化。",
          contribution: "开源 + 模块化 + 系统消融，WAM 从「各家自吹」走向可复现比较的基础设施。" },
        { id: "xpace", name: "XPACE", title: "XPACE: Joint World and Action Modeling from Heterogeneous Experience", year: 2026, venue: "arXiv 2026.09 (CUHK等)", status: "预印本", url: "https://arxiv.org/abs/2609.17372",
          summary: "统一具身世界模型：既是 WAM（联合预测动作与未来视频），又是世界模拟器（预测给定动作的视觉后果）。",
          purpose: "通才机器人要会调用多样经验、选择动作并预判动作如何改变世界，但无动作视频/人类演示/机器人轨迹三类经验彼此割裂。",
          method: "策略与模拟器共享视频骨干：无动作视频学视觉动力学，带动作标注的人类与机器人演示联合学视频+动作预测；粗到细课程逐步聚焦机器人控制。",
          contribution: "「视频预测连接异构经验与动作学习、并自生成新经验」的代表路线，与 Hydra-0 的统一接口思想互补。" },
        { id: "modar", name: "ModAR", title: "Modality-Autoregressive World-Action Models", year: 2026, venue: "arXiv 2026.09 (CMU等)", status: "预印本", url: "https://arxiv.org/abs/2609.17524",
          summary: "首个多模态自回归 WAM：依次去噪深度/点轨迹/DINO 特征等多种未来模态后再预测动作。",
          purpose: "WAM 惯例把未来预测为 RGB 图像，但深度、预训练特征、点轨迹等模态捕获几何/语义/运动信息更高效，如何组合仍是开放问题。",
          method: "模态间自回归去噪（每种预测以先生成的模态为条件），从零训练系统研究数据配比、预测模态与 WAM 形式的影响。",
          contribution: "发现点轨迹+DINO 特征+深度最有益、额外预测未来 RGB 无一致增益——对「WAM 必须生成视频」的默认假设的直接挑战。" },
        { id: "mowam", name: "MoWAM", title: "MoWAM: Explicit Future Motion Prediction for Efficient World Action Models", year: 2026, venue: "arXiv 2026.09 (复旦等)", status: "预印本", url: "https://arxiv.org/abs/2609.20709",
          summary: "用显式未来运动预测取代未来视频生成：效率与分布外鲁棒兼得。",
          purpose: "WAM 推理时生成未来视频开销巨大；直接砍掉生成又让未来动力学只隐式存在于观测特征里，分布偏移下不够鲁棒。",
          method: "把结构化机器人运动作为未来的紧凑抽象显式预测；Mixture-of-Transformer 训练时学未来视觉动力学、联合预测运动与动作，推理时只出运动。",
          contribution: "与 SV-WAM 的「预测为训不为推」相互呼应：WAM 效率化的两条并行探索之一。" },
        { id: "dido", name: "DIDO", title: "DIDO: Distilling Interaction-Centric Dynamics into One-Step Denoising for World Action Models", year: 2026, venue: "arXiv 2026.09 (华中科大等)", status: "预印本", url: "https://arxiv.org/abs/2609.15570",
          summary: "把多步视频模型收敛后的交互动力学蒸馏进步去噪：WAM 闭环控制的延迟难题。",
          purpose: "WAM 用视频生成预测未来，但迭代去噪延迟大；直接截断到单步会保留场景结构、丢掉对操作最关键的夹爪-物体交互动力学。",
          method: "实证发现去噪中视觉内容收敛速率不同（背景早、交互晚）；用分布匹配蒸馏 + 交互中心监督，把多步模型收敛的动力学压进单步。",
          contribution: "「保留交互、压缩步数」的 WAM 加速代表，与 ActionCache 等推理加速线互补。" },
        { id: "wholebodywam", name: "WholeBodyWAM", title: "WholeBodyWAM: Learning Whole-Body World Action Models with Scalable Motion Priors", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.18197",
          summary: "人形全身 WAM：用海量异源运动先验替代昂贵的目标机器人轨迹。",
          purpose: "人形全身操作需要协调全身动力学，但目标机器人大规模轨迹昂贵难扩；人类与人形运动数据却取之不尽，只是不能直接当本体动作用。",
          method: "整理 UniMotion-4K（4000+ 小时人类视频/原生 3D 运动/异构人形平台），规范化为统一运动表示，先学可迁移的全身动力学预测先验再做目标机器人训练。",
          contribution: "「运动先验代替机器人数据」的人形 WAM 代表，数据策略上与 ZimaBlue 的视频预训练一脉相承。" }
      ]
    }
  ]
});
