// 具身智能研究图谱 · 数据文件 3/4：任务规划、导航移动、记忆与自我改进
window.EAI_MODULES = window.EAI_MODULES || [];

window.EAI_MODULES.push({
  id: "planning", type: "loop", order: 5, icon: "🧠", color: "#b8862d",
  name: "任务规划与长程推理",
  tagline: "LLM/VLM 如何把「收拾好厨房」拆成机器人能执行的步骤？",
  difficulties: [
    {
      id: "pl_llm", name: "LLM 任务规划与 Grounding",
      question: "语言模型的常识规划如何被机器人能力与物理现实约束？",
      papers: [
        { id: "saycan", name: "SayCan", title: "Do As I Can, Not As I Say: Grounding Language in Robotic Affordances", year: 2022, venue: "CoRL 2022", status: "已发表", url: "https://arxiv.org/abs/2204.01691",
          summary: "LLM 语义打分 × 技能价值函数打分，联合决定下一个技能。",
          purpose: "LLM 会给出机器人做不到的计划，需要用「可行性」约束「合理性」。",
          method: "对每个候选技能，用 LLM 概率（有多有用）乘以价值函数（有多可行）选择执行，循环推进长程任务。",
          contribution: "101 个真实厨房指令 84% 计划正确率，是「LLM + affordance grounding」范式的奠基作。" },
        { id: "innermonologue", name: "Inner Monologue", title: "Inner Monologue: Embodied Reasoning through Planning with Language Models", year: 2022, venue: "CoRL 2022", status: "已发表", url: "https://arxiv.org/abs/2207.05608",
          summary: "把成功检测、场景描述、人类反馈都写进 LLM 的「内心独白」闭环重规划。",
          purpose: "开环 LLM 规划无法应对执行失败与环境扰动。",
          method: "多源文本化反馈（成功/失败、可见物体、人类纠正）持续注入 LLM 上下文，动态调整后续计划。",
          contribution: "证明闭环语言反馈显著提升长程任务鲁棒性，是具身闭环推理的起点。" },
        { id: "codeaspolicies", name: "Code as Policies", title: "Code as Policies: Language Model Programs for Embodied Control", year: 2023, venue: "ICRA 2023", status: "已发表", url: "https://arxiv.org/abs/2209.07753",
          summary: "让 LLM 直接写策略代码：感知 API + 控制 API + 递归函数定义。",
          purpose: "自然语言计划表达不了空间几何精度与控制逻辑（循环、条件）。",
          method: "少样本提示 LLM 生成调用感知/控制库的 Python 程序，支持递归定义未见函数，代码即策略。",
          contribution: "空间推理精确、可组合、可解释，开创「语言→代码→行动」路线（后续 VoxPoser、ProgPrompt 等）。" },
        { id: "voxposer", name: "VoxPoser", title: "VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models", year: 2023, venue: "CoRL 2023 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2307.05973",
          summary: "LLM 写代码调 VLM，合成 3D 价值图供运动规划器零样本执行。",
          purpose: "跳过策略训练：能否直接从「LLM+VLM」合成每个新任务的操作轨迹？",
          method: "LLM 推断 affordance 与约束并生成代码，把 VLM 感知落到体素价值图，模型预测控制在其上求解轨迹。",
          contribution: "开放指令、开放物体的零样本操作，确立「基础模型合成价值图」的免训练路线。" },
        { id: "rekep", name: "ReKep", title: "ReKep: Spatio-Temporal Reasoning of Relational Keypoint Constraints for Robotic Manipulation", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2409.01652",
          summary: "把操作任务表示为关键点上的时空约束函数，VLM 自动生成。",
          purpose: "寻找比价值图更紧凑、可优化的任务表示以支撑「感知即约束」。",
          method: "DINOv2+SAM 提关键点，GPT-4o 把指令写成关键点约束的 Python 函数，分层优化实时求解动作。",
          contribution: "免训练完成倒茶、叠衣等需双臂协调的任务，「约束生成」成为操作规划新接口。" },
        { id: "agenticreal2sim", name: "Agentic Real2Sim", title: "Agentic Real2Sim: Physics-based World Modeling with Vision-Language Agents", year: 2026, venue: "arXiv 2026.07", status: "预印本", url: "https://arxiv.org/abs/2607.19190",
          summary: "VLA 智能体驱动的 real2sim：自动恢复几何、物体状态与物理参数。",
          purpose: "机器人-物体交互的 real2sim 不止视觉重建，还要推物理，人工流程极其费时。",
          method: "视觉语言智能体编排「重建-状态推断-参数辨识」循环，自动构建物理仿真资产。",
          contribution: "世界模型的仿真资产生产线自动化，连接真实数据与物理世界建模。" },
        { id: "decoupling_pc", name: "Decoupling Planning & Control", title: "Decoupling Planning and Control for Instructable Agents", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.26788",
          summary: "实证：指令微调 VLM 擅长出高层计划，但低延迟可靠执行需解耦。",
          purpose: "同一个 VLM 既做规划又做低层控制，两头不讨好。",
          method: "系统性对照「统一模型」与「规划/控制解耦」两种架构的可指令性。",
          contribution: "为双系统架构提供 2026 年的实证边界，回答「何时必须分层」。" }
      ]
    },
    {
      id: "pl_agent", name: "开放世界智能体与技能编排",
      question: "在开放世界里，智能体如何自主探索、积累技能、完成开放目标？",
      papers: [
        { id: "voyager", name: "Voyager", title: "Voyager: An Open-Ended Embodied Agent with Large Language Models", year: 2023, venue: "TMLR 2024", status: "已发表", url: "https://arxiv.org/abs/2305.16291",
          summary: "Minecraft 里 GPT-4 驱动的终身学习智能体：自动课程 + 技能库 + 自我验证。",
          purpose: "探索 LLM 智能体能否无人干预地持续探索、习得并复用技能。",
          method: "自动课程提出目标，生成可执行代码技能并存入向量化技能库，迭代提示 + 环境反馈自我修正。",
          contribution: "独特物品获取 3.3 倍、科技树解锁最快 15.3 倍，技能库机制成为智能体记忆的经典设计。" },
        { id: "sima", name: "SIMA", title: "Scaling Instructable Agents Across Many Simulated Worlds (SIMA)", year: 2024, venue: "DeepMind 技术报告 (DeepMind)", status: "技术报告", url: "https://arxiv.org/abs/2404.10179",
          summary: "跨 10 款商业 3D 游戏的通用指令跟随智能体，只用屏幕+键鼠。",
          purpose: "检验语言条件智能体能否在人类接口（像素进、键鼠出）下跨世界泛化。",
          method: "多游戏人类演示与标注训练统一策略，语言指令条件化，零新增游戏 API。",
          contribution: "跨游戏正迁移明显，为「虚拟世界通才 → 物理世界」的路径提供证据（SIMA 2 已接 Gemini）。" },
        { id: "okrobot", name: "OK-Robot", title: "OK-Robot: What Really Matters in Integrating Open-Knowledge Models for Robotics", year: 2024, venue: "RSS 2024 (NYU/Stanford等)", status: "已发表", url: "https://arxiv.org/abs/2401.12202",
          summary: "开放词汇导航+抓取的系统集成研究：真实家庭 58.5% 拾放成功率。",
          purpose: "开放知识模型（VLM/抓取模型）拼成完整系统后到底行不行、坑在哪？",
          method: "VoxelMap 语义记忆 + AnyGrasp 抓取 + 导航原语的零训练集成，10 个真实家庭 171 个物体系统评测。",
          contribution: "给出开放世界移动操作的第一份「系统级体检报告」，指出感知与鲁棒性为主要瓶颈。" },
        { id: "eqa_openeqa", name: "OpenEQA", title: "OpenEQA: Embodied Question Answering in the Era of Foundation Models", year: 2024, venue: "CVPR 2024", status: "已发表", url: null,
          summary: "开放词汇具身问答基准：视频记忆 EQA 与主动探索 EQA 双赛道。",
          purpose: "量化智能体「理解并记住环境后回答问题」的能力，暴露与人类差距。",
          method: "180+ 真实环境、1600+ 人写问题、LLM 自动评分协议，评测 GPT-4V 等前沿模型。",
          contribution: "GPT-4V 远低于人类（尤其空间理解），成为具身语义记忆与探索的重要标尺。" }
      ]
    },
    {
      id: "pl_dual", name: "分层与快慢系统架构",
      question: "慢推理与快控制之间的接口应该是语言、潜向量还是子目标图像？",
      papers: [
        { id: "palme", name: "PaLM-E", title: "PaLM-E: An Embodied Multimodal Language Model", year: 2023, venue: "ICML 2023", status: "已发表", url: "https://arxiv.org/abs/2303.03378",
          summary: "562B 多模态语言模型：传感器模态直接嵌入 LLM，规划输出给低层策略。",
          purpose: "把 LLM 的语义推理直接接到机器人感知上，验证「多具身联训」的正迁移。",
          method: "图像/状态向量作为「多模态语句」注入 PaLM，联合训练 VQA、描述与机器人规划任务。",
          contribution: "跨具身正迁移且保留通用 VLM 能力，是 RT-2 与后续 VLA 的直接前身。" },
        { id: "lcb", name: "LCB", title: "From LLMs to Actions: Latent Codes as Bridges in Hierarchical Robot Control", year: 2024, venue: "IROS 2024", status: "已发表", url: null,
          summary: "用可学习潜码替代语言作为分层接口，端到端可微调。",
          purpose: "语言接口表达不了「微调一点角度」这类细粒度意图，且分层系统难端到端优化。",
          method: "LLM 输出附加潜 token 作为低层策略条件，保留语言能力同时用梯度打通上下层。",
          contribution: "在长程任务上超越纯语言接口分层方案，论证「潜向量接口」的价值。" },
        { id: "gr00t_n15_dual", name: "LeVERB", title: "LeVERB: Humanoid Whole-Body Control with Latent Vision-Language Instruction", year: 2025, venue: "arXiv 2025", status: "预印本", url: null,
          summary: "人形全身控制的潜「动词」接口：视觉-语言→潜指令→全身动作。",
          purpose: "人形 VLA 多停留在上身操作，全身（含腿）语言控制缺少基准与方法。",
          method: "分层潜空间：高层把视觉语言映射为潜动词词表，低层 RL 全身控制器消费潜动词，配 sim-to-real 基准。",
          contribution: "首个面向人形全身控制的潜语言接口与基准，联通 VLA 与 locomotion 两个社区。" },
        { id: "robodual", name: "RoboDual", title: "Towards Synergistic, Generalized and Efficient Dual-System for Robotic Manipulation (RoboDual)", year: 2025, venue: "arXiv 2025", status: "预印本", url: null,
          summary: "通才 VLA（慢）+ 轻量扩散专家（快）的协同双系统模板。",
          purpose: "通才模型泛化好但慢，专家策略快但窄，如何两全？",
          method: "OpenVLA 类通才低频输出潜条件与离散动作，20M 参数扩散专家高频精化，异步协同。",
          contribution: "5% 数据适配新任务、控制频率大增，给出双系统的开源参考实现。" }
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "navigation", type: "loop", order: 6, icon: "🧭", color: "#3a8fa3",
  name: "导航与移动操作",
  tagline: "从「走到那儿」到「边走边干」：语言导航、通用导航与移动操作。",
  difficulties: [
    {
      id: "n_vln", name: "视觉语言导航 (VLN)",
      question: "如何按自然语言指令在从未见过的建筑里走到目的地？",
      papers: [
        { id: "navid", name: "NaVid", title: "NaVid: Video-based VLM Plans the Next Step for Vision-and-Language Navigation", year: 2024, venue: "RSS 2024", status: "已发表", url: "https://arxiv.org/abs/2402.15852",
          summary: "视频 VLM 端到端 VLN：只吃单目视频流，免地图免里程计。",
          purpose: "传统 VLN 依赖全景图、深度与里程计，与真实机器人部署脱节。",
          method: "视频式 token 化历史观测，VLM 直接输出下一步低层动作，51 万 VLN 样本+76 万 VQA 联训。",
          contribution: "R2R/RxR SOTA 并零样本 sim-to-real 成功，确立「视频 VLM 即导航策略」路线。" },
        { id: "navila", name: "NaVILA", title: "NaVILA: Legged Robot Vision-Language-Action Model for Navigation", year: 2025, venue: "RSS 2025", status: "已发表", url: "https://arxiv.org/abs/2412.04453",
          summary: "腿足机器人 VLN 双层框架：VLA 出中层语言动作，RL 控制器执行。",
          purpose: "把 VLN 从轮式/离散动作扩展到需要全身协调的腿足平台与复杂地形。",
          method: "VLM 输出「向前 75cm」类中层空间语言指令，视觉 RL 运动策略负责避障与地形通过，两层解耦训练。",
          contribution: "真实四足/人形穿越复杂场景，展示「语言中间表示 + RL 底层」在移动平台的通用性。" },
        { id: "etpnav", name: "ETPNav", title: "ETPNav: Evolving Topological Planning for Vision-Language Navigation in Continuous Environments", year: 2024, venue: "TPAMI 2024", status: "已发表", url: null,
          summary: "在线进化拓扑图 + 跨模态规划，连续环境 VLN 代表方法。",
          purpose: "连续环境 VLN 需要同时解决长程规划与避障控制。",
          method: "在线自组织路标拓扑图抽象环境，图上做跨模态目标推理，试错启发式避障控制器执行。",
          contribution: "R2R-CE/RxR-CE 大幅刷新 SOTA（+10%/+20%），拓扑记忆成为连续 VLN 标准组件。" },
        { id: "vlfm", name: "VLFM", title: "VLFM: Vision-Language Frontier Maps for Zero-Shot Semantic Navigation", year: 2024, venue: "ICRA 2024 (Best Paper Nominee)", status: "已发表", url: null,
          summary: "语言价值前沿地图：零样本语义导航直接上 Spot 真机。",
          purpose: "找语义目标（如「找到床」）通常要训练专用策略，希望零训练完成。",
          method: "占据图提取探索前沿，BLIP-2 给每个前沿打语义相关分构建价值图，贪心选择最有希望方向。",
          contribution: "HM3D/MP3D 零样本 SOTA 并真机即插即用，「基础模型打分 + 前沿探索」成为零样本导航模板。" },
        { id: "unilavira", name: "Uni-LaViRA", title: "Uni-LaViRA: Language-Vision-Robot Actions Translation for Unified Embodied Navigation", year: 2026, venue: "arXiv 2026.05", status: "预印本", url: "https://arxiv.org/abs/2605.27582",
          summary: "语言-视觉-机器人动作的统一「翻译」框架，横跨导航任务形态。",
          purpose: "主流做法靠堆视觉-语言数据再补机器人数据，导航专用对齐不足。",
          method: "把导航看作语言/视觉到空间动作流的统一翻译问题，跨任务统一训练。",
          contribution: "真实机器人未见环境导航的统一框架，2026 VLN 基础模型化代表。" },
        { id: "vernav", name: "VerNav", title: "VerNav: Verifier-First Low-Latency Vision-and-Language Navigation", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.00920",
          summary: "验证器优先的低延迟 VLN：显式推理与实时性不再二选一。",
          purpose: "显式推理改善指令理解但拖慢控制，低延迟模型又测不准语义。",
          method: "验证器优先架构，轻量策略主控 + 独立验证器按需介入纠偏。",
          contribution: "给「推理 vs 延迟」矛盾给出 2026 新解法。" },
        {"id": "msgnav", "name": "MSGNav", "title": "MSGNav: Unleashing the Power of Multi-modal 3D Scene Graph for Zero-Shot Embodied Navigation", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2511.10376", "summary": "多模态 3D 场景图的零样本具身导航：保留视觉证据不压成文本。", "purpose": "场景图压成纯文本关系会不可逆丢失视觉证据。", "method": "构建保留多模态视觉证据的 3D 场景图，降低建图成本并支持零样本导航。", "contribution": "CVPR 2026 场景图导航代表，接 ConceptGraphs/Embodied-RAG 谱系。"},
        {"id": "janusvln", "name": "JanusVLN", "title": "JanusVLN: Decoupling Semantics and Spatiality with Dual Implicit Memory for Vision-Language Navigation", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2509.22548", "summary": "语义/空间双隐式记忆替代显式地图与存帧，VLN 提升 10-35 点。", "purpose": "显式语义地图与关键帧存储各有信息瓶颈。", "method": "双重隐式神经记忆分别编码语义与空间几何，注入 3D 先验到 MLLM。", "contribution": "ICLR 2026 隐式导航记忆代表，与具身记忆模块直接相关。"},
        {"id": "openfly", "name": "OpenFly", "title": "OpenFly: A Comprehensive Platform for Aerial Vision-Language Navigation", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2502.18041", "summary": "空中 VLN 全栈平台：多渲染引擎 + 10 万轨迹基准。", "purpose": "地面 VLN 基准成熟，空中导航缺数据与工具链。", "method": "UE/GTA V/Google Earth/3DGS 多引擎渲染 + 自动标注工具链 + 关键帧感知智能体。", "contribution": "ICLR 2026 空中具身导航的奠基性平台。"},
        {"id": "sagenav", "name": "SAGE", "title": "Plan in Sandbox, Navigate in Open Worlds: Learning Physics-Grounded Abstracted Experience for Embodied Navigation", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2605.10118", "summary": "物理接地的抽象「沙盒」里蒸馏经验，再迁移开放世界导航。", "purpose": "照片级仿真训练导航代价高且难迁移。", "method": "语义抽象沙盒中 RL 蒸馏物理接地经验，零样本迁移开放世界与实体机器人。", "contribution": "ICML 2026，A-EQA +9.7 点并上实体机器人，抽象仿真新思路。"}
      ]
    },
    {
      id: "n_found", name: "通用导航基础模型",
      question: "存在「导航界的 GPT」吗？跨机器人、跨场景的通用导航策略如何炼？",
      papers: [
        { id: "nomad", name: "NoMaD", title: "NoMaD: Goal Masked Diffusion Policies for Navigation and Exploration", year: 2024, venue: "ICRA 2024 (Best Paper)", status: "已发表", url: "https://arxiv.org/abs/2310.07896",
          summary: "目标掩码 + 扩散策略统一「探索」与「找目标」两种行为。",
          purpose: "探索未知环境与导航到已知目标此前需要两套模型。",
          method: "统一 Transformer 骨干，目标图像可被掩码（无目标=探索），扩散头输出多峰动作分布。",
          contribution: "单模型双模式且性能更好、参数更省，成为通用导航策略的标志性工作。" },
        { id: "navfound", name: "ViNT", title: "ViNT: A Foundation Model for Visual Navigation", year: 2023, venue: "CoRL 2023 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2306.14846",
          summary: "跨 6 种机器人平台训练的视觉导航基础模型，支持提示式适配。",
          purpose: "验证导航领域的「基础模型配方」：大规模异构数据+统一目标接口。",
          method: "以图像目标为通用任务接口，Transformer 策略在异构导航数据上预训练，扩散子目标提议支持长程探索。",
          contribution: "零样本驱动新机器人形态，可下游适配到不同传感器与任务，导航基础模型的开端。" },
        { id: "mobilityvla", name: "Mobility VLA", title: "Mobility VLA: Multimodal Instruction Navigation with Long-Context VLMs and Topological Graphs", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2407.07775",
          summary: "长上下文 VLM 吃完整个导览视频当地图，拓扑图出底层路径。",
          purpose: "让机器人看一遍「带你逛一圈」的视频就能接受多模态指令导航。",
          method: "高层：Gemini 1.5 Pro 长上下文检索导览视频帧定位目标；低层：离线拓扑图规划到达。",
          contribution: "836㎡ 真实办公环境 86%+ 成功率（含手绘图指令），展示长上下文 VLM 作为环境记忆的可行性。" },
        { id: "citywalker", name: "CityWalker", title: "CityWalker: Learning Embodied Urban Navigation from Web-Scale City Videos", year: 2025, venue: "CVPR 2025", status: "已发表", url: null,
          summary: "从 2000+ 小时网络城市漫步视频学城市尺度导航。",
          purpose: "城市环境动态复杂，真机采数不现实，网络视频是唯一规模化来源。",
          method: "伪标注动作从城市行走/驾驶视频提取，模仿学习训练城市导航策略。",
          contribution: "把「网络视频→导航策略」路线推到城市尺度，动态都市环境导航显著提升。" }
      ]
    },
    {
      id: "n_mobileman", name: "移动操作一体化",
      question: "底盘、手臂、全身如何在一个策略里协同完成「边走边操作」？",
      papers: [
        { id: "homerobot", name: "HomeRobot", title: "HomeRobot: Open-Vocabulary Mobile Manipulation", year: 2023, venue: "CoRL 2023", status: "已发表", url: "https://arxiv.org/abs/2306.11565",
          summary: "开放词汇移动操作（OVMM）基准：仿真+真机双轨复现。",
          purpose: "定义并标准化「在任意地方拿起任意物体放到任意地方」这一核心难题。",
          method: "Habitat 仿真与低成本真机平台配套，提供 RL 与启发式基线，组织 NeurIPS OVMM 挑战赛。",
          contribution: "OVMM 成为移动操作的标准问题定义与年度竞赛。" },
        { id: "tidybot", name: "TidyBot++", title: "TidyBot++: An Open-Source Holonomic Mobile Manipulator for Robot Learning", year: 2024, venue: "CoRL 2024", status: "已发表", url: null,
          summary: "开源全向移动操作平台 + 电话遥操作，模仿学习友好。",
          purpose: "移动操作研究缺乏便宜好用的标准硬件与数采方案。",
          method: "全向底盘设计消除运动约束，智能手机遥操作接口，模仿学习管线开箱即用。",
          contribution: "大幅降低移动操作研究门槛，家务任务策略可直接学成。" },
        { id: "harmon", name: "BUMBLE", title: "BUMBLE: Unifying Reasoning and Acting with Vision-Language Models for Building-wide Mobile Manipulation", year: 2025, venue: "ICRA 2025", status: "已发表", url: null,
          summary: "楼宇级移动操作：VLM 统一长程推理与技能调用 + 多层记忆。",
          purpose: "楼宇尺度任务（跨房间取物送物）挑战长视野推理与空间记忆。",
          method: "VLM 编排参数化技能库，长短期记忆管理历史观测，真实三层楼评测。",
          contribution: "楼宇级任务 47.1% 端到端成功率（20 分钟/任务），暴露并量化长程移动操作瓶颈。" },
        { id: "wbvima", name: "BRS / WB-VIMA", title: "BEHAVIOR Robot Suite: Streamlining Real-World Whole-Body Manipulation for Everyday Household Activities", year: 2025, venue: "CoRL 2025", status: "已发表", url: "https://arxiv.org/abs/2503.05652",
          summary: "家务全身操作套件：双臂+躯干+底盘全身策略与遥操作接口。",
          purpose: "真实家务需要全身协调（弯腰、伸展、双手），远超固定底座设定。",
          method: "轮式双臂+升降躯干平台，JoyLo 全身遥操接口采数，WB-VIMA 全身自回归策略建模关节间依赖。",
          contribution: "5 项长程家务任务显著超越基线，给出「全身操作」的完整软硬件参考栈。" },
        {"id": "dockanywhere", "name": "DockAnywhere", "title": "DockAnywhere: Data-Efficient Visuomotor Policy Learning for Mobile Manipulation via Novel Demonstration Generation", "year": 2026, "venue": "RA-L 2026", "status": "已发表", "url": "https://arxiv.org/abs/2604.15023", "summary": "新型演示生成让移动操作数据效率大增。", "purpose": "移动操作演示采集成本高，覆盖难。", "method": "演示生成管线扩充数据分布，数据高效训练视觉运动策略。", "contribution": "RA-L 2026 移动操作数据引擎代表。"},
        {"id": "twinvla", "name": "TwinVLA", "title": "TwinVLA: Data-Efficient Bimanual Manipulation with Twin Single-Arm Vision-Language-Action Models", "year": 2026, "venue": "ICLR 2026 (Poster)", "status": "已发表", "url": "https://arxiv.org/abs/2511.05275", "summary": "两个单臂 VLA 拼出数据高效的双臂操作。", "purpose": "双臂数据贵，单臂数据多，直接迁移难。", "method": "孪生单臂 VLA 组合协同完成双臂任务，复用单臂数据生态。", "contribution": "ICLR 2026 双臂新思路：组合优于从零训练。"}
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "memory", type: "loop", order: 7, icon: "🗂", color: "#c04f7c",
  name: "具身记忆与自我改进",
  tagline: "机器人如何记住环境与经验、从失败中学习、终身进化？",
  difficulties: [
    {
      id: "m_spatial", name: "空间与情景记忆",
      question: "长期运行的机器人如何维护「我在哪儿见过什么、发生过什么」？",
      papers: [
        { id: "remembr", name: "ReMEmbR", title: "ReMEmbR: Building and Reasoning Over Long-Horizon Spatio-Temporal Memory for Robot Navigation", year: 2025, venue: "ICRA 2025", status: "已发表", url: "https://arxiv.org/abs/2409.13682",
          summary: "小时级机器人视频记忆库 + LLM 迭代检索问答与导航。",
          purpose: "机器人连续运行数小时后，「刚才那个人把箱子放哪了」类问题无从回答。",
          method: "视频字幕化 + 向量库存储时空事件，LLM Agent 按时间/位置/文本多路检索迭代推理，输出答案或导航目标。",
          contribution: "提出长时程时空记忆基准 NaVQA，真机部署验证，是机器人「情景记忆」方向的代表。" },
        { id: "embodiedrag", name: "Embodied-RAG", title: "Embodied-RAG: General Non-parametric Embodied Memory for Retrieval and Generation", year: 2025, venue: "ICRA 2025", status: "已发表", url: "https://arxiv.org/abs/2409.18313",
          summary: "把 RAG 搬进具身空间：语义森林分层记忆，跨尺度检索与生成。",
          purpose: "通用 RAG 无法处理空间局部性与多尺度查询（「最近的椅子」vs「这层楼的布局」）。",
          method: "拓扑地图上构建层次化语义森林（物体→区域→楼层摘要），查询时按尺度检索并生成回答或导航目标。",
          contribution: "250+ 查询、公里级环境验证，为「具身非参数记忆」给出通用框架。" },
        { id: "sayplan", name: "SayPlan", title: "SayPlan: Grounding Large Language Models using 3D Scene Graphs for Scalable Robot Task Planning", year: 2023, venue: "CoRL 2023 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2307.06135",
          summary: "LLM 在可折叠 3D 场景图上「语义搜索 + 迭代重规划」，扩展到 36 房间。",
          purpose: "把整栋楼的场景图塞进 LLM 上下文不现实，需要图上推理机制。",
          method: "LLM 主动展开/折叠场景图子图做语义搜索，场景图模拟器验证计划并迭代修正。",
          contribution: "36 房间/140 资产规模的可执行规划，确立「场景图即机器人长期记忆」的用法。" },
        { id: "dynamem", name: "DynaMem", title: "DynaMem: Online Dynamic Spatio-Semantic Memory for Open World Mobile Manipulation", year: 2025, venue: "ICRA 2025", status: "已发表", url: null,
          summary: "支持增删改的动态语义记忆，环境变了地图跟着变。",
          purpose: "静态语义地图假设环境不变，真实家庭物品天天挪。",
          method: "动态体素语义库随观测在线更新（新增/移除物体），查询用 VLM+向量混合检索。",
          contribution: "非静态环境拾放成功率 70%，比静态系统提升 2 倍+，把「记忆更新」推入移动操作主流。" },
        { id: "hitmem", name: "HitMem", title: "HitMem: Hierarchical Temporal 3D Memory with Multi-Modal Context-Aware Retrieval for Dynamic Environments", year: 2026, venue: "ECCV 2026", status: "已发表", url: "https://arxiv.org/abs/2609.00950",
          summary: "动态环境的层次时序 3D 记忆：物体动了，记忆跟着动。",
          purpose: "多数 3D 记忆框架假设静态世界，物体被移动后记忆即失效。",
          method: "层次化时序 3D 记忆 + 多模态上下文感知检索，长期任务中自适应维护动态场景表征。",
          contribution: "把「时序维度」补进 3D 具身记忆，2026 动态记忆方向代表。" },
        {"id": "memoryvla", "name": "MemoryVLA", "title": "MemoryVLA: Perceptual-Cognitive Memory in Vision-Language-Action Models for Robotic Manipulation", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2508.19236", "summary": "给 VLA 装感知-认知记忆：12 个真机任务成功率 84%。", "purpose": "VLA 无记忆，跨阶段任务需要重复感知同一物体。", "method": "「认知-记忆-动作」框架引入工作记忆与长期感知-认知记忆库，条件化扩散动作专家。", "contribution": "ICLR 2026，超 CogACT 与 π0，VLA×具身记忆两条线的合流标志。"}
      ]
    },
    {
      id: "m_self", name: "经验积累与自我改进",
      question: "机器人能否从自己的成功与失败中持续变强，而不是每次从零开始？",
      papers: [
        { id: "reflexion_robo", name: "REFLECT", title: "REFLECT: Summarizing Robot Experiences for Failure Explanation and Correction", year: 2023, venue: "CoRL 2023 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2306.15724",
          summary: "多模态经验分层摘要 + LLM 失败推理，解释并修复机器人失败。",
          purpose: "机器人失败后通常只能人工排查，希望系统自己解释「为什么失败、怎么补救」。",
          method: "视觉/声音/动作历史转成分层文本摘要，LLM 逐步推理失败原因并生成纠正计划。",
          contribution: "提出 RoboFail 基准，验证 LLM 可基于经验摘要定位失败并指导重规划。" },
        { id: "expel_robo", name: "RoboMemory", title: "RoboMemory: A Brain-Inspired Multi-Memory Agentic Framework for Lifelong Learning in Physical Embodied Systems", year: 2025, venue: "arXiv 2025", status: "预印本", url: "https://arxiv.org/abs/2508.01415",
          summary: "空间/时间/情景/语义四记忆并行的脑启发终身学习框架。",
          purpose: "单一记忆机制难以同时支撑地图维护、经验复用与知识沉淀。",
          method: "统一世界骨架（动态场景图）+ 四类记忆并行更新与检索，闭环规划器消费记忆输出。",
          contribution: "EmbodiedBench 上较基线 +25%，接近闭源 SOTA，真机验证终身学习能力，是具身多记忆系统的集大成尝试。" },
        { id: "gensim2_self", name: "SOAR", title: "Autonomous Improvement of Instruction Following Skills via Foundation Models (SOAR)", year: 2024, venue: "CoRL 2024", status: "已发表", url: null,
          summary: "VLM 自动出任务、判成败，机器人自采数据自我提升，无人值守。",
          purpose: "让指令跟随策略摆脱人工采数与人工评估，自主变强。",
          method: "VLM 生成语义任务与成功判定，策略自主执行采集，成功经验回流训练，多机器人分布式跑数周。",
          contribution: "3 万+ 自主轨迹使新场景成功率显著提升，展示「自我改进飞轮」的工程可行性。" },
        { id: "demogen_self", name: "Scaling Robot Fleet Learning", title: "RoboFleet / Fleet Learning Line: Autonomous Data Flywheels in Deployment", year: 2025, venue: "行业实践（Waymo/Figure/1X 等）", status: "综述性条目", url: null,
          summary: "部署车队/机器人群的数据飞轮：现场经验回流持续迭代模型。",
          purpose: "单机经验有限，群体部署的经验如何安全高效地聚合成模型改进？",
          method: "远程监控 + 干预数据标注 + 定期再训练发布的运营闭环（各公司实现不一）。",
          contribution: "行业层面验证「部署即数据引擎」，但也暴露隐私、分布偏移与回归测试等开放问题。" }
      ]
    },
    {
      id: "m_lifelong", name: "持续学习与技能库",
      question: "新技能不断进来，旧技能如何不被遗忘、还能组合复用？",
      papers: [
        { id: "libero", name: "LIBERO", title: "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning", year: 2023, venue: "NeurIPS 2023 D&B", status: "已发表", url: "https://arxiv.org/abs/2306.03310",
          summary: "130 任务的终身机器人学习基准：陈述性与程序性知识迁移。",
          purpose: "机器人持续学习缺少受控、可复现的标准测试床。",
          method: "四套任务序列考察前向/后向迁移，提供架构、算法、预训练策略的系统实验。",
          contribution: "成为 VLA 与终身学习论文的默认评测（OpenVLA、π0 等都在用），并揭示朴素 SFT 遗忘严重。" },
        { id: "lotus", name: "LOTUS", title: "LOTUS: Continual Imitation Learning for Robot Manipulation Through Unsupervised Skill Discovery", year: 2024, venue: "ICRA 2024", status: "已发表", url: null,
          summary: "无监督技能发现 + 技能库增量扩展的持续模仿学习。",
          purpose: "持续学习新任务时既要新技能又不能毁掉旧技能。",
          method: "开放词汇视觉特征聚类发现技能单元，经验回放 + 技能库增量更新，元控制器组合调用。",
          contribution: "成功率超 SOTA 基线 11%+，给出「技能库式持续学习」的可行实现。" },
        { id: "sirius_fleet", name: "Sirius-Fleet", title: "Multi-Task Interactive Robot Fleet Learning with Visual World Models (Sirius-Fleet)", year: 2024, venue: "CoRL 2024", status: "已发表", url: null,
          summary: "车队级人机协同持续部署：世界模型预测失败，人及时接管。",
          purpose: "多机器人多任务部署中，如何最小化人类监督又保证安全改进？",
          method: "视觉世界模型 + 异常预测器预判执行风险触发人工干预，干预数据回流持续微调策略。",
          contribution: "把「预测性人机共驾」引入车队学习，部署期间性能与自主度同步上升。" }
      ]
    }
  ]
});
