// 具身智能研究图谱 · 数据文件 4/4：元层模块（系统目标、评测、开放问题、安全对齐）
window.EAI_MODULES = window.EAI_MODULES || [];

window.EAI_MODULES.push({
  id: "goal", type: "meta", order: 0, icon: "🎯", color: "#5b6470",
  name: "系统目标与综述",
  tagline: "具身智能到底要造什么？路线图、立场与全景综述。",
  difficulties: [
    {
      id: "g_survey", name: "路线图与全景综述",
      question: "VLA、世界模型、具身 Agent 三条主线如何汇聚成通用机器人？",
      papers: [
        { id: "vla_survey", name: "VLA Survey (2024)", title: "A Survey on Vision-Language-Action Models for Embodied AI", year: 2024, venue: "arXiv 2024（持续更新）", status: "综述", url: "https://arxiv.org/abs/2405.14093",
          summary: "VLA 领域首篇系统综述：组件分类学（VLM 骨干/动作头/训练配方）。",
          purpose: "为爆炸增长的 VLA 文献建立统一分类框架与术语。",
          method: "按层级（低层控制/高层规划）与组件（感知、动作表示、数据）梳理 300+ 工作。",
          contribution: "领域标准参考文献与文献导航图，配套 GitHub 论文列表持续维护。" },
        { id: "vla_survey25", name: "VLA Survey (2025)", title: "Vision-Language-Action Models: Concepts, Progress, Applications and Challenges", year: 2025, venue: "arXiv 2025", status: "综述", url: "https://arxiv.org/abs/2505.04769",
          summary: "覆盖 2022-2025 的 VLA 概念-进展-应用-挑战全景综述。",
          purpose: "更新至 π0/GR00T 时代的 VLA 版图，梳理 80+ 模型的五年演化。",
          method: "按架构创新、高效训练、实时推理、应用领域四轴组织，附对比表格。",
          contribution: "提供 2025 视角的领域地图与开放问题清单（数据瓶颈、评测碎片化、安全）。" },
        { id: "unified26", name: "统一机器人学习 (2026)", title: "Toward Unified Robot Learning: Bridging Representation, Vision-Language-Action, and World Models", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03927",
          summary: "主张表征学习、VLA 与世界模型三大浪潮汇流为统一机器人学习。",
          purpose: "机器人要可靠运行，必须感知、行动并推理行动后果，但三条研究线各自为政。",
          method: "梳理表征/VLA/WM 三域的互补性，论证统一框架的必要性与路径。",
          contribution: "为「VLA×WM 融合」提供 2026 年的理论纲领，与本图谱 WM/WAM 难点设定互相印证。" },
        { id: "vlatrack26", name: "表征中心持续预训练", title: "Beyond Data Scaling: Representation-Centric Continued Pre-training for Vision-Language-Action Models", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.27550",
          summary: "超越数据规模：以表征为中心的 VLA 持续预训练。",
          purpose: "机器人轨迹比网络数据难规模化几个数量级，单靠堆数据撞墙。",
          method: "把预训练重心从数据量转向表征质量，持续预训练提升 VLA 表征的下游适配性。",
          contribution: "「表征 > 数据」的 2026 强音，与 MINERVA 一起构成对规模叙事的反思线。" },
        { id: "wm_survey", name: "World Models Survey", title: "Understanding World or Predicting Future? A Comprehensive Survey of World Models", year: 2025, venue: "ACM Computing Surveys 2025", status: "综述", url: "https://arxiv.org/abs/2411.14499",
          summary: "世界模型双功能框架：理解世界 vs 预测未来。",
          purpose: "Sora/Genie 之后「世界模型」定义混乱，需要概念澄清与分类。",
          method: "按内部表征（理解）与未来预测（模拟）二分组织文献，覆盖生成式、JEPA、MBRL 三大流派与驾驶/机器人/社会模拟应用。",
          contribution: "给出被广泛引用的世界模型分类学与研究议程。" },
        { id: "wam_survey26", name: "WAM Survey (2026)", title: "World-Action Models for Robot Learning and Control: A Survey", year: 2026, venue: "arXiv 2026.09", status: "综述", url: "https://arxiv.org/abs/2609.16074",
          summary: "WAM 首篇系统综述：厘清与 WM/MBRL/动作条件视频生成/反应式 VLA 的边界。",
          purpose: "WAM 概念随 2026 爆发流行起来，但与传统世界模型、MBRL、VLA 的关系众说纷纭。",
          method: "机器人视角的组织框架：表征、转移建模、动作接口、训练信号与应用场景的统一分类学。",
          contribution: "WAM 领域的定义性参考文献，与本图谱 wm_wam 难点的收录框架互相印证。" },
        { id: "wm_actionable", name: "可行动世界模型分级", title: "World Models for Embodied Intelligence: From Plausible to Controllable to Actionable", year: 2026, venue: "arXiv 2026.09", status: "综述", url: "https://arxiv.org/abs/2609.16697",
          summary: "提出世界模型三级能力刻度：Plausible（合理）→ Controllable（可控）→ Actionable（可行动）。",
          purpose: "世界模型进步常以视觉保真度衡量，但其价值在于改善行为——哪些预测能力真正提升控制？",
          method: "按「预测能力如何转化为行为改进」组织文献，三级递进刻度替代按架构/输出模态/应用域的传统分类。",
          contribution: "把「好看 ≠ 有用」的诊断框架化，呼应 MINERVA/WAM 能力边界研究的批判线。" },
        { id: "embodied_survey", name: "Embodied AI Survey", title: "Aligning Cyber Space with Physical World: A Comprehensive Survey on Embodied AI", year: 2024, venue: "arXiv 2024（持续更新）", status: "综述", url: "https://arxiv.org/abs/2407.06886",
          summary: "具身智能全栈综述：仿真器、感知、交互、智能体、sim-to-real 一网打尽。",
          purpose: "为 MLM/世界模型时代的具身智能建立全栈知识框架。",
          method: "从具身感知/交互/智能体/虚实迁移四层组织数百篇文献并盘点基准与仿真平台。",
          contribution: "具身智能入门与选题的标准起点，中英社区影响力大。" },
        { id: "pi_blog", name: "Physical Intelligence 路线", title: "Foundations for Physical Intelligence: from π0 to π*", year: 2025, venue: "公司技术路线（PI）", status: "综述性条目", url: "https://www.physicalintelligence.company/",
          summary: "「机器人基础模型公司」的路线宣言：通用物理智能而非单一机器人。",
          purpose: "论证物理智能应像 LLM 一样走「通用基础模型 + 后训练」路线。",
          method: "π 系列模型迭代（π0→π0.5→π*0.6 含 RL 后训练 Recap 配方），异构机器人数据共训。",
          contribution: "行业风向标：定义了 VLA 商业化叙事与「数据金字塔+后训练」方法论。" }
      ]
    },
    {
      id: "g_scaling", name: "Scaling Law 与数据战略",
      question: "具身智能有没有自己的 Scaling Law？数据从哪来、比例怎么配？",
      papers: [
        { id: "data_scaling", name: "Data Scaling Laws", title: "Data Scaling Laws in Imitation Learning for Robotic Manipulation", year: 2025, venue: "ICLR 2025 (UC Berkeley等)", status: "已发表", url: "https://arxiv.org/abs/2410.18647",
          summary: "操作模仿学习的数据规模律：环境/物体多样性 > 单纯演示数量。",
          purpose: "回答「采多少数据、怎么采」这一最烧钱的问题。",
          method: "4 万+ 次真实评测的受控实验，拟合泛化性能对环境数、物体数、演示数的幂律。",
          contribution: "给出「32 环境 × 单物体 × 50 演示」类实用采数公式，纠正「盲堆数量」的行业直觉。" },
        { id: "sft_rl_scaling", name: "RL vs SFT 泛化", title: "SFT Memorizes, RL Generalizes: A Comparative Study of Foundation Model Post-training", year: 2025, venue: "ICML 2025 (Meta FAIR等)", status: "已发表", url: "https://arxiv.org/abs/2501.17161",
          summary: "SFT 倾向记忆、RL 带来规则级泛化的对照研究。",
          purpose: "厘清后训练两大范式对分布外泛化的真实贡献。",
          method: "文本与视觉变体任务上严格对照 SFT 与 RL 后训练的 OOD 表现。",
          contribution: "为具身模型「先 SFT 稳格式、再 RL 提泛化」的训练顺序提供机理依据。" },
        { id: "humanoid_data", name: "Humanoid Data Pyramid", title: "GR00T 数据金字塔：真机-人类视频-合成数据的配比方法论", year: 2025, venue: "NVIDIA GR00T 系列", status: "综述性条目", url: null,
          summary: "真机遥操（塔尖）+ 人类视频（塔身）+ 世界模型合成（塔基）的数据战略。",
          purpose: "系统回答人形机器人「数据从哪来」：单一来源都不够。",
          method: "按获取成本与具身相关性分层混合，潜动作/IDM 技术把无标注数据变成训练信号。",
          contribution: "「数据金字塔」成为行业通用语言，牵引潜动作、神经轨迹等技术议程。" }
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "benchmark", type: "meta", order: 8, icon: "📊", color: "#7b52ab",
  name: "Benchmark 与评测",
  tagline: "仿真基准、真机评测与世界模型评测：进步如何被可信地度量？",
  difficulties: [
    {
      id: "b_manip", name: "操作基准",
      question: "操作策略的泛化到底该怎么测？",
      papers: [
        { id: "calvin", name: "CALVIN", title: "CALVIN: A Benchmark for Language-Conditioned Policy Learning for Long-Horizon Robot Manipulation Tasks", year: 2022, venue: "RA-L 2022", status: "已发表", url: "https://arxiv.org/abs/2112.03227",
          summary: "语言条件长程操作标准基准，连续 5 指令链式评测。",
          purpose: "量化「听懂一串指令连续干活」的能力。",
          method: "4 个仿真环境、34 任务、免人工重置的链式任务协议。",
          contribution: "语言条件操作论文的必刷榜（SuSIE、GR-1 等），推动长程一致性研究。" },
        { id: "libero_b", name: "LIBERO", title: "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning", year: 2023, venue: "NeurIPS 2023 D&B", status: "已发表", url: "https://arxiv.org/abs/2306.03310",
          summary: "130 任务终身学习基准，也是 VLA 微调评测的事实标准。",
          purpose: "受控测量知识迁移与遗忘（同时被借用为通用操作评测）。",
          method: "空间/物体/目标/长程四套任务组，统一模仿学习协议。",
          contribution: "OpenVLA-OFT、π0、SimpleVLA-RL 等都以 LIBERO 分数对话，串起整个 VLA 评测生态。" },
        { id: "simpler", name: "SIMPLER", title: "Evaluating Real-World Robot Manipulation Policies in Simulation (SIMPLER)", year: 2024, venue: "CoRL 2024", status: "已发表", url: "https://arxiv.org/abs/2405.05941",
          summary: "用仿真可靠预测真机策略排名：真实-仿真相关性做到可用。",
          purpose: "真机评测又贵又慢又不可复现，能否用仿真替代大部分评测？",
          method: "系统消除视觉与控制的 real-to-sim 差距，验证仿真成绩与真机成绩的排序相关性。",
          contribution: "RT 系/OpenVLA 等模型的仿真代理评测成为社区惯例，评测成本降数量级。" },
        { id: "robocasa", name: "RoboCasa", title: "RoboCasa: Large-Scale Simulation of Everyday Tasks for Generalist Robots", year: 2024, venue: "RSS 2024", status: "已发表", url: "https://arxiv.org/abs/2406.02523",
          summary: "120 厨房场景、2500+ 3D 资产、100 任务的大规模日常任务仿真。",
          purpose: "给通才机器人提供接近真实多样性的训练与评测场。",
          method: "AI 辅助生成场景/纹理/任务，MimicGen 自动扩增 10 万+ 轨迹。",
          contribution: "证明合成数据规模与策略性能正相关，成为通才操作的主力训练场之一。" },
        { id: "behavior1k", name: "BEHAVIOR-1K", title: "BEHAVIOR-1K: A Human-Centered, Embodied AI Benchmark with 1,000 Everyday Activities and Realistic Simulation", year: 2023, venue: "CoRL 2023 / OmniGibson", status: "已发表", url: "https://behavior.stanford.edu",
          summary: "由人类需求调查定义的 1000 项日常活动全栈基准。",
          purpose: "让基准反映「人类真正想让机器人做什么」而非研究者方便测什么。",
          method: "OmniGibson 物理仿真（含流体/柔性体/温度状态）+ 谓词化任务定义，50 场景 9000+ 物体。",
          contribution: "最接近真实家务复杂度的公开基准，长程移动操作的试金石。" },
        { id: "genmanip", name: "RoboTwin 2.0", title: "RoboTwin 2.0: A Scalable Data Generator and Benchmark with Strong Domain Randomization for Robust Bimanual Robotic Manipulation", year: 2025, venue: "arXiv 2025", status: "预印本", url: null,
          summary: "双臂操作可扩展数据生成器与域随机化基准。",
          purpose: "双臂协作策略缺少大规模、可控扰动的评测与数据源。",
          method: "自动任务生成 + 强域随机化 + 50 任务双臂评测协议，配套真机对应。",
          contribution: "双臂 VLA（RDT、π0 类）的主流新兴评测场。" },
        {"id": "vlaarena", "name": "VLA-Arena", "title": "VLA-Arena: An Open-Source Framework for Benchmarking Vision-Language-Action Models", "year": 2026, "venue": "ICML 2026", "status": "已发表", "url": "https://arxiv.org/abs/2512.22539", "summary": "170 任务四维度三档难度的开源 VLA 基准与榜单。", "purpose": "VLA 评测碎片化，泛化/接地/安全缺统一标尺。", "method": "沿任务结构、语言指令、视觉观测三轴系统化构造基准与排行榜。", "contribution": "ICML 2026 VLA 评测基建，暴露主流模型短板。"},
        {"id": "cebench", "name": "CEBench", "title": "Rethinking the Practicality of Vision-Language-Action Model: A Comprehensive Benchmark and An Improved Baseline", "year": 2026, "venue": "ICRA 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.22663", "summary": "VLA 实用性基准：参数规模、预训练开销、本体适配三问。", "purpose": "学术 VLA 与可部署 VLA 之间的实用性鸿沟缺量化。", "method": "覆盖仿真+真机、多本体的综合基准并提出实用改进基线。", "contribution": "ICRA 2026「实用性」维度的系统追问（接 MINERVA 批判线）。"},
        {"id": "wanderland", "name": "Wanderland", "title": "Wanderland: Geometrically Grounded Simulation for Open-World Embodied AI", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2511.20620", "summary": "视频-3DGS 开放世界城市仿真：几何接地的可复现闭环评测。", "purpose": "开放世界具身评测缺高保真可交互环境。", "method": "视频-3DGS 重建城市级环境，照片级渲染 + 几何接地交互。", "contribution": "CVPR 2026 开放世界评测基建。"},
        { id: "robospa", name: "RoboSPA", title: "RoboSPA: Can VLA Models Go Beyond Simple Scenes and Short-Horizon Tasks?", year: 2026, venue: "EMNLP 2026", status: "已发表", url: "https://arxiv.org/abs/2609.05324",
          summary: "细粒度空间推理 × 长程程序规划双维度的大规模 VLA 诊断基准。",
          purpose: "现有基准只测预设设定下的任务完成率，看不出模型在空间歧义与流程复杂度上升时如何失效。",
          method: "10 任务类 56 基础任务按五档难度实例化为 280 变体，采集 52.7 万条多本体轨迹构建 RoboSPA 数据集并系统诊断主流 VLA。",
          contribution: "EMNLP 2026 主会接收；给出「空间-程序」双轴失效画像，LIBERO 近满分之后下一阶段的评测标尺。" },
        { id: "liberorecover", name: "LIBERO-RECOVER", title: "LIBERO-RECOVER: Beyond Task Success Towards Failure Recovery in Robotic Manipulation Models", year: 2026, venue: "arXiv 2026.09 (大连理工等)", status: "预印本", url: "https://arxiv.org/abs/2609.05178",
          summary: "把「失败后能否恢复」变成一等评测维度：从完成率转向可靠性。",
          purpose: "LIBERO 上 SOTA 已近 100% 成功，但预设初始状态下的成功不等于真实鲁棒——抓空、碰撞、物体被碰跑后的恢复能力从未被度量。",
          method: "在 LIBERO 之上系统注入抓取失败、碰撞、物体位移等扰动，构造评测恢复能力的协议并衡量主流 VLA/WAM。",
          contribution: "直指「基准饱和」后的评测空档，与 RoboSPA 一同推动评测从成功率转向过程可靠性。" }
      ]
    },
    {
      id: "b_embodied", name: "具身智能体与 EQA 基准",
      question: "高层推理+低层执行的完整智能体能力如何测？",
      papers: [
        { id: "embodiedbench", name: "EmbodiedBench", title: "EmbodiedBench: Comprehensive Benchmarking Multi-modal Large Language Models for Vision-Driven Embodied Agents", year: 2025, venue: "ICML 2025 (Oral)", status: "已发表", url: "https://arxiv.org/abs/2502.09560",
          summary: "1128 个任务、6 维能力拆解的 MLLM 具身智能体基准。",
          purpose: "细粒度诊断 MLLM 作为具身智能体的短板（空间/长程/复杂指令）。",
          method: "4 个环境（家居/导航/操作）× 能力维度切片，统一评测 24 个前沿 MLLM。",
          contribution: "揭示「高层任务行、低层操作崩」的普遍模式，成为 MLLM 具身评测标配。" },
        { id: "openeqa_b", name: "OpenEQA", title: "OpenEQA: Embodied Question Answering in the Era of Foundation Models", year: 2024, venue: "CVPR 2024 (Meta FAIR)", status: "已发表", url: null,
          summary: "开放词汇 EQA 基准：记忆型与主动探索型双赛道、LLM 评分。",
          purpose: "测「理解并记住一个环境」的能力，语义记忆的标尺。",
          method: "180+ 真实场景、1600+ 人写问答、七类问题分类学。",
          contribution: "暴露前沿 VLM 与人类的巨大差距，被具身记忆工作广泛引用。" },
        { id: "vlabench", name: "VLABench", title: "VLABench: A Large-Scale Benchmark for Language-Conditioned Robotics Manipulation with Long-Horizon Reasoning Tasks", year: 2024, venue: "arXiv 2024", status: "预印本", url: null,
          summary: "100 类任务、2000+ 物体，强调常识与世界知识依赖的操作评测。",
          purpose: "现有基准指令模板化，测不出「利用世界知识完成模糊指令」。",
          method: "任务设计显式要求常识/物理/语义推理，自动化场景生成与技能评分。",
          contribution: "把「知识密集型操作」立为独立评测维度。" },
        { id: "agentbenchreal", name: "RoboArena", title: "RoboArena: Distributed Real-World Evaluation of Generalist Robot Policies", year: 2025, venue: "CoRL 2025", status: "已发表", url: "https://arxiv.org/abs/2506.18123",
          summary: "分布式真机盲测竞技场：跨实验室双盲 A/B + Elo 排名。",
          purpose: "真机评测无法复现与比较，急需「机器人届的 Chatbot Arena」。",
          method: "多所大学 DROID 平台上双盲对比策略，众包偏好聚合成全局排名。",
          contribution: "为通才策略提供首个去中心化、抗作弊的真机排行榜。" },
        {"id": "robovista", "name": "RoboVista", "title": "RoboVista: Evaluating Vision Language Models for Diverse Robot Applications", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2607.04610", "summary": "面向多样机器人应用的 VLM 能力评测基准。", "purpose": "VLM 在机器人管线中的能力边界缺系统测量。", "method": "覆盖多机器人应用场景的 VLM 评测套件。", "contribution": "RSS 2026 VLM×机器人评测代表（Berkeley）。"},
        {"id": "robustvla", "name": "RobustVLA", "title": "RobustVLA: On Robustness of Vision-Language-Action Model against Multi-Modal Perturbations", "year": 2026, "venue": "ICLR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2510.00037", "summary": "VLA 多模态扰动鲁棒性的系统基准。", "purpose": "VLA 对视觉/语言扰动敏感度未知，部署风险难评估。", "method": "系统性多模态扰动协议评测主流 VLA。", "contribution": "ICLR 2026 鲁棒性标尺，与安全模块的攻击线互补。"}
      ]
    },
    {
      id: "b_wm", name: "世界模型评测",
      question: "世界模型的「物理正确性」与「预测忠实度」如何量化？",
      papers: [
        { id: "physbench", name: "Physics-IQ", title: "Do Generative Video Models Understand Physical Laws? (Physics-IQ)", year: 2025, venue: "arXiv 2025 (Google DeepMind)", status: "预印本", url: null,
          summary: "真实拍摄的物理事件基准：生成模型物理理解全线不及格。",
          purpose: "检验「视频生成=世界模拟」宣称的物理正确性。",
          method: "固体力学/流体/光学等真实实验视频，模型续写后与真实结果比对打分。",
          contribution: "量化「视觉逼真 ≠ 物理正确」，视频世界模型评测的清醒剂。" },
        { id: "worldmodelbench", name: "WorldModelBench", title: "WorldModelBench: Judging Video Generation Models As World Models", year: 2025, venue: "arXiv 2025 (北大等)", status: "预印本", url: null,
          summary: "把视频生成模型当世界模型评测：指令跟随+物理守恒+常识。",
          purpose: "为「视频模型当世界模型用」建立系统评分卡。",
          method: "7 个维度（物理/因果/指令一致等）人评+自动评混合协议，覆盖 14 个主流模型。",
          contribution: "给世界模型选型提供可比数字，推动评测标准化。" },
        { id: "ewmbench", name: "EWMBench", title: "EWMBench: Evaluating Scene, Motion, and Semantic Quality in Embodied World Models", year: 2025, venue: "arXiv 2025 (AgiBot)", status: "预印本", url: null,
          summary: "具身世界模型专用评测：场景一致性、运动正确性、语义对齐。",
          purpose: "通用视频指标（FVD 等）与操作任务的实际可用性脱节。",
          method: "机器人操作视频上定义场景/轨迹/语义多轴指标与人评对齐验证。",
          contribution: "为「世界模型服务机器人」提供针对性质检工具。" },
        { id: "robophys3d", name: "RoboPhys-3D", title: "RoboPhys-3D: A Comprehensive Embodied World Model Evaluation via 3D Reconstruction", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.28718",
          summary: "以 3D 重建为统一协议，全面评测具身世界模型的物理正确性。",
          purpose: "视频世界模型已充当数据引擎/动作规划器/模拟器，但缺统一 3D 接地的评测协议。",
          method: "通过 3D 重建统一度量具身世界模型生成内容的几何与物理合理性。",
          contribution: "2026 年具身世界模型评测的新标准候选，接棒 Physics-IQ 议题。" },
        { id: "safewm", name: "Safety-Critical WM", title: "Rethinking World Models for Safety-Critical Embodied Systems", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03774",
          summary: "安全视角重审世界模型：预测似然与视觉保真度 ≠ 安全保证。",
          purpose: "世界模型已从潜动力学进化为可控交互模拟器，但高保真不等于可用于安全关键系统。",
          method: "系统分析世界模型失效模式与安全关键场景的 gap，提出安全导向的评估维度。",
          contribution: "给「世界模型进安全回路」划定前置条件，安全×WM 交叉方向的开创性分析。" },
        { id: "1xwm", name: "1X World Model Challenge", title: "1X World Model Challenge: Evaluating World Models on Real Humanoid Data", year: 2024, venue: "1X Technologies（竞赛） (1X)", status: "综述性条目", url: null,
          summary: "真实人形机器人数据上的世界模型压缩/采样竞赛。",
          purpose: "把世界模型评测锚定到真实人形数据与下游控制价值。",
          method: "EVE 人形真机数据集上评压缩损失与生成质量，公开排行榜。",
          contribution: "行业首个人形世界模型公开竞赛，牵引「世界模型当机器人评估器」议程。" },
        { id: "failbench", name: "FailBench", title: "FailBench: How Reliable are VLMs at Judging Robot Task Success?", year: 2026, venue: "arXiv 2026.09 (CMU等)", status: "预印本", url: "https://arxiv.org/abs/2609.03611",
          summary: "评测「评测者」：VLM 判机器人任务成败到底靠不靠谱？",
          purpose: "VLM 越来越多地被用作机器人操作的自动评估器，其跨域可靠性缺乏证据。",
          method: "构建跨域机器人成败判定基准，系统测量 VLM 裁判的泛化与偏差。",
          contribution: "揭示自动评估器的可信度问题——评测基础设施本身的元评测。" },
        { id: "behaviorskill", name: "Behavior-Skill", title: "Behavior-Skill: A Fine-Grained Benchmark for Evaluating Vision-Language-Action Policies in Long-Horizon Tasks", year: 2026, venue: "arXiv 2026.08", status: "预印本", url: "https://arxiv.org/abs/2608.30536",
          summary: "长程任务细粒化：把总成败拆解到组成技能的逐项评测。",
          purpose: "长程移动操作的总成功率掩盖了具体哪个技能环节失败。",
          method: "细粒度行为-技能标注基准，定位长程任务中的技能级失败。",
          contribution: "评测粒度从任务级细化到技能级，可指导针对性修复。" },
        { id: "simple26", name: "SIMPLE", title: "SIMPLE: Simulation-Based Policy Learning and Evaluation for Humanoid Loco-Manipulation", year: 2026, venue: "arXiv 2026.06 (清华等)", status: "预印本", url: "https://arxiv.org/abs/2606.08278",
          summary: "人形 loco-manipulation 的仿真学习与评测一体化套件。",
          purpose: "人形基础模型进化快于评测能力，真机贵且难复现，仿真基准又偏桌面/轮式。",
          method: "面向人形全身移动操作的仿真学习+评测统一基准。",
          contribution: "填补人形 loco-manipulation 仿真评测空白，与 DeepInsight 共构成评测新基建。" },
        { id: "deepinsight", name: "DeepInsight", title: "DeepInsight: A Unified Evaluation Infrastructure Across the Physical AI Stack", year: 2026, venue: "arXiv 2026.06 (NVIDIA等)", status: "预印本", url: "https://arxiv.org/abs/2606.17574",
          summary: "横跨物理 AI 全栈的统一评测基建：从模型解码到物理 tick。",
          purpose: "物理 AI 栈各环节算子时间尺度差三个数量级，评测设施彼此割裂。",
          method: "统一评测基础设施，正交覆盖基础模型解码到全身控制数千步物理仿真。",
          contribution: "把「全栈级」评测工程化，机器人评测从单点走向系统。" },
        { id: "zeta26", name: "ZETA", title: "ZETA: A Controlled Study of Zero-Shot Cross-Embodiment VLA Transfer for Tabletop Manipulation", year: 2026, venue: "arXiv 2026.09 (上交等)", status: "预印本", url: "https://arxiv.org/abs/2609.02546",
          summary: "受控研究：VLA 零样本跨本体迁移在桌面操作上到底行不行。",
          purpose: "零样本跨具身泛化对 VLA 至关重要，但缺少系统性对照证据。",
          method: "多本体受控实验设计，分离本体差异与任务难度对迁移的影响。",
          contribution: "给「跨具身」宣称提供首个受控证据基线。" }
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "openproblem", type: "meta", order: 9, icon: "🧩", color: "#8a6ec4",
  name: "开放问题与边界",
  tagline: "泛化天花板、评测危机、物理幻觉——领域的诚实清单。",
  difficulties: [
    {
      id: "o_gap", name: "泛化差距与能力边界",
      question: "今天的 VLA/WM 离「真正通用」还差哪些数量级？",
      papers: [
        { id: "vlaeval_critique", name: "VLA 泛化解剖", title: "From Seeing to Doing: Bridging Reasoning and Decision for Robotic Manipulation — and the Generalization Gap", year: 2025, venue: "arXiv 2025（代表性批判线）", status: "综述性条目", url: null,
          summary: "系统梳理 VLA 在视觉/语义/行为三轴上的泛化失效模式。",
          purpose: "回答「demo 很惊艳，为什么换个桌布就崩」。",
          method: "扰动分解实验：光照/背景/新物体/新指令/新动作逐轴消融现有 VLA。",
          contribution: "把「泛化」拆成可测维度，指出语义华丽而空间脆弱的通病。" },
        { id: "sim2real_gap", name: "评测危机", title: "Benchmark Fragmentation and the Reproducibility Crisis in Robot Learning", year: 2025, venue: "社区讨论线（RoboArena/SIMPLER 动机）", status: "综述性条目", url: null,
          summary: "各家自测自榜、真机结果不可复现的系统性问题盘点。",
          purpose: "指出机器人学习缺少 ImageNet/GLUE 式共同标尺的结构性原因。",
          method: "对比各 VLA 论文评测协议差异（任务集、初始条件、成功判据）。",
          contribution: "推动 RoboArena、SIMPLER 等中立评测基础设施诞生。" },
        { id: "physical_halluc", name: "物理幻觉", title: "Physical Hallucination in Video World Models: Photorealism without Physics", year: 2025, venue: "Physics-IQ / 社区研究线", status: "综述性条目", url: null,
          summary: "世界模型「看起来对、物理上错」的系统性失效（穿模、质量守恒破坏）。",
          purpose: "为世界模型进入控制回路前的可靠性问题立项。",
          method: "汇总物理评测中的失效类型学：接触/遮挡/守恒/因果四类幻觉。",
          contribution: "把「物理正确性」立为世界模型的独立研究目标（区别于视觉质量）。" },
        { id: "longhorizon_open", name: "长程与错误恢复", title: "Long-Horizon Autonomy and Error Recovery: The Unsolved Last Mile", year: 2025, venue: "π0.5 / BUMBLE 等失败分析线", status: "综述性条目", url: null,
          summary: "10 分钟+任务的复合误差、死锁与恢复策略仍无系统解法。",
          purpose: "长程任务成功率随步数指数衰减，恢复能力决定实用性。",
          method: "各长程系统（π0.5、BUMBLE、OK-Robot）失败案例的横向归因。",
          contribution: "确立「错误检测-解释-恢复」为独立研究议程（接 REFLECT 一线）。" },
        { id: "ghosttac", name: "GhostTac", title: "GhostTac: Manipulating Tactile Sensors without Physical Contact", year: 2026, venue: "ACM CCS 2026", status: "已发表", url: "https://arxiv.org/abs/2608.20817",
          summary: "不碰就能欺骗触觉传感器：视触觉的物理层安全攻击面。",
          purpose: "触觉传感器已是现代机器人核心部件，其物理层安全性从未被审视。",
          method: "无物理接触的外部操控（声/光/电磁等途径）干扰视触觉读数并评估对策略的影响。",
          contribution: "开辟「触觉安全」新战场，把对抗攻击从数字像素扩展到物理触觉。" }
      ]
    }
  ]
});

window.EAI_MODULES.push({
  id: "safety", type: "meta", order: 10, icon: "🛡", color: "#4f7a63",
  name: "安全与对齐",
  tagline: "会动的 AI 出错会砸到人：物理安全、对抗鲁棒与规则约束。",
  difficulties: [
    {
      id: "s_rules", name: "行为约束与安全规则",
      question: "如何给机器人装上「宪法」与安全护栏？",
      papers: [
        { id: "asimov", name: "ASIMOV / Robot Constitution", title: "Robot Constitutions and the ASIMOV Benchmark: Semantic Safety for Embodied AI", year: 2025, venue: "Google DeepMind (Gemini Robotics 配套)", status: "技术报告", url: null,
          summary: "自然语言「机器人宪法」+ 语义安全基准 ASIMOV。",
          purpose: "机械层安全（限力限速）之外，还需语义层安全（这件事本身该不该做）。",
          method: "宪法式规则自动生成与批判修订，ASIMOV 数据集评测伤害场景判断。",
          contribution: "把 LLM 对齐的「宪法方法」移植到具身域，语义安全评测的开端。" },
        { id: "saferplanner", name: "KnowNo", title: "Robots That Ask For Help: Uncertainty Alignment for Large Language Model Planners (KnowNo)", year: 2023, venue: "CoRL 2023 (Best Paper)", status: "已发表", url: "https://arxiv.org/abs/2307.01928",
          summary: "共形预测校准 LLM 规划器的不确定性：该问人时就问人。",
          purpose: "LLM 规划器过度自信，模糊指令下会「硬猜」出危险动作。",
          method: "共形预测生成带统计保证的候选动作集，集合非单元素时触发求助。",
          contribution: "以最小人类干预实现任务完成率统计保证，「知道自己不知道」成为具身安全标配议题。" },
        { id: "safevla", name: "SafeVLA", title: "SafeVLA: Towards Safety Alignment of Vision-Language-Action Model via Constrained Learning", year: 2025, venue: "NeurIPS 2025 (Spotlight)", status: "已发表", url: "https://arxiv.org/abs/2503.03480",
          summary: "约束马尔可夫决策过程把安全显式注入 VLA 微调。",
          purpose: "VLA 追求成功率时会撞倒无关物体、走危险路径。",
          method: "安全约束 RL（CMDP）集成进 VLA 后训练，安全与任务目标联合优化。",
          contribution: "安全指标提升 83.6% 且成功率不降反升，VLA 安全对齐首个系统方案。" },
        { id: "badvla", name: "VLA 对抗与后门", title: "Adversarial Attacks and Backdoors on Vision-Language-Action Models: A Security Line", year: 2025, venue: "arXiv 2025 研究线（BadVLA 等）", status: "综述性条目", url: null,
          summary: "针对 VLA 的物理贴纸攻击、指令注入与训练期后门研究线。",
          purpose: "VLA 进入真实环境后攻击面从数字扩展到物理世界。",
          method: "白盒/黑盒扰动、场景物体投毒、数据集后门在操作任务上的攻击与防御评估。",
          contribution: "证明现有 VLA 极易被物理扰动劫持，安全防御研究严重滞后于能力研究。" },
        { id: "initiationsafety", name: "Initiation Safety", title: "Initiation Safety: A Missing Dimension in Generalist-Robot Safety", year: 2026, venue: "RSS 2026 Workshop", status: "已发表", url: "https://arxiv.org/abs/2607.07420",
          summary: "提出通用机器人安全的第三维度：第一个难以撤销的社会动作该不该发生？",
          purpose: "机器人安全只讨论运动与对话，缺少「主动发起」层面的约束（如打招呼、主动触碰）。",
          method: "定义「发起安全」问题空间：机器人是否应执行其首个难以回退的社会/物理动作。",
          contribution: "扩展机器人安全的维度定义，对 Helix 类自主人形的部署有直接指导意义。" },
        { id: "evidencereg", name: "Evidence-Gated 多模态鲁棒", title: "Sensing Which Modality Matters: Evidence-Gated Regularization for Robust VLA Policies", year: 2026, venue: "arXiv 2026.09", status: "预印本", url: "https://arxiv.org/abs/2609.03142",
          summary: "证据门控正则：阻止 VLA 学到传感器间的伪相关。",
          purpose: "有限且同质的演示数据让 VLA 学到传感器间伪相关而非任务相关信号，换环境即失效。",
          method: "证据门控正则化，强制各模态贡献与其任务证据对齐。",
          contribution: "多模态 VLA 鲁棒性训练的 2026 代表，与触觉模态可信使用议题直接相关。" },
        {"id": "flowhijack", "name": "FlowHijack", "title": "FlowHijack: A Dynamics-Aware Backdoor Attack on Flow-Matching Vision-Language-Action Models", "year": 2026, "venue": "CVPR 2026", "status": "已发表", "url": "https://arxiv.org/abs/2604.09651", "summary": "首个针对流匹配 VLA（π0 类）的动力学感知后门攻击。", "purpose": "流匹配动作生成的向量场机制带来新攻击面。", "method": "利用向量场动作生成机制注入触发器的后门攻击。", "contribution": "CVPR 2026，VLA 安全从扩散模型扩展到流匹配系。"},
        {"id": "certifiedmanip", "name": "Certified Contact-Rich", "title": "Certified Gradient-Based Contact-Rich Manipulation via Smoothing-Error Reachable Tubes", "year": 2026, "venue": "RSS 2026", "status": "已发表", "url": "https://arxiv.org/abs/2602.09368", "summary": "平滑误差可达管：接触密集操作的首个认证式梯度方法。", "purpose": "学习型接触控制缺乏形式化安全证书。", "method": "平滑误差可达管构造证书，约束梯度类接触控制。", "contribution": "RSS 2026 形式化安全×接触操作的交汇。"}
      ]
    },
    {
      id: "s_hri", name: "人机共存与物理安全",
      question: "与人共享空间的机器人如何保证不伤人、可预期、可干预？",
      papers: [
        { id: "safe_control", name: "安全控制栈", title: "Control Barrier Functions Meet Learned Policies: Safety Filters for Learning-Based Robots", year: 2024, venue: "CBF/安全滤波研究线", status: "综述性条目", url: null,
          summary: "控制屏障函数（CBF）等安全滤波器包裹学习策略的最后防线。",
          purpose: "神经策略无形式保证，需要独立安全层兜底。",
          method: "CBF/可达性分析实时监督并最小修正策略输出，保证碰撞/速度约束。",
          contribution: "「学习策略 + 形式化安全滤波」成为部署级系统的标准架构。" },
        { id: "rt2_safety", name: "人形安全标准", title: "Towards Safety Standards for Humanoid Robots: ISO/IEEE Efforts and Industry Practice", year: 2025, venue: "标准化进程（IEEE HSC / ISO TC299）", status: "综述性条目", url: null,
          summary: "人形机器人安全标准的制定动态与产业自律实践。",
          purpose: "人形进厂进家前，行业需要可认证的安全规范。",
          method: "梳理 ISO 10218/ISO 13482 向人形扩展的议题：稳定性、跌倒、力控、紧急停止。",
          contribution: "把「可认证安全」引入具身智能研究视野，连接学界与监管。" },
        { id: "interruptible", name: "可纠正性", title: "Real-Time Human Intervention and Corrigibility in Robot Policies (YAY Robot 一线)", year: 2024, venue: "CoRL 2024 等", status: "已发表", url: null,
          summary: "「边干边听人喊停/纠正」：语言实时干预并从干预中学习。",
          purpose: "自主执行中的人类口头纠正应立即生效并沉淀为改进。",
          method: "语言纠正实时注入分层策略（Yell At Your Robot），干预历史用于迭代微调。",
          contribution: "长程灵巧任务成功率 +20%+，把「可纠正性」做成了训练信号。" }
      ]
    }
  ]
});

// 模块间的环形流转关系（首页环形图用）
window.EAI_FLOW = [
  { from: "perception", to: "worldmodel", label: "状态表征" },
  { from: "worldmodel", to: "vla", label: "预测供决策" },
  { from: "vla", to: "learning", label: "策略需训练" },
  { from: "learning", to: "planning", label: "技能可编排" },
  { from: "planning", to: "navigation", label: "计划落地" },
  { from: "navigation", to: "memory", label: "经验沉淀" },
  { from: "memory", to: "perception", label: "记忆引导感知 ↺" }
];
